export type NavigationSearchPriority = "P0" | "P1" | "P2";
export type NavigationSearchStatus = "selected" | "queued" | "monitor";
export type NavigationSearchDomain = {
  id: string; title: string; priority: NavigationSearchPriority; status: NavigationSearchStatus;
  playerQuestion: string; evidence: readonly string[]; strengths: readonly string[]; gaps: readonly string[]; exitCriteria: readonly string[];
};
export const NAVIGATION_SEARCH_DOMAINS: readonly NavigationSearchDomain[] = [
  {id:"route-search-parity",title:"Route Registry and Search Parity",priority:"P0",status:"selected",playerQuestion:"Can every player-facing route be found through navigation or global search using its visible name?",evidence:["src/shared/navigation/navItems.ts","src/features/legacy/AppRoutes.tsx","src/features/search/globalSearchEngine.ts","src/shared/commands/CommandPalette.tsx"],strengths:["Central navigation registry, route table, global search and command palette exist."],gaps:["No release gate proves zero orphan routes, zero dead search targets and parity across registries."],exitCriteria:["Canonical route reference","Navigation/search/command differential matrix","Zero orphan and zero dead-target contract"]},
  {id:"natural-language-aliases",title:"Natural Language and Alias Coverage",priority:"P1",status:"queued",playerQuestion:"Can I find a tool using Turkish, English, abbreviations and table language I naturally remember?",evidence:["src/features/search/globalSearchEngine.ts","src/shared/i18n/i18n.ts","src/shared/navigation/navItems.ts"],strengths:["Search normalization already handles Turkish casing and diacritics."],gaps:["Aliases, abbreviations and mixed-language synonyms are not centrally modeled or mutation-tested."],exitCriteria:["Alias dictionary","Edition-aware synonym matrix","No ambiguous top-result regressions"]},
  {id:"empty-result-recovery",title:"Empty Result Recovery",priority:"P1",status:"queued",playerQuestion:"When nothing matches, does search explain why and offer useful nearby actions?",evidence:["src/features/search/GlobalSearchPage.tsx","src/features/help/HelpCenter.tsx","src/features/collections/CollectionsPage.tsx"],strengths:["Search has an empty state and help content exists."],gaps:["No deterministic typo, category-reset or help fallback contract exists."],exitCriteria:["Typo recovery policy","Category reset action","Help and create-content fallback"]},
  {id:"result-ranking-intent",title:"Result Ranking and Intent",priority:"P1",status:"queued",playerQuestion:"Does the most likely thing appear first instead of being buried under similarly named content?",evidence:["src/features/search/globalSearchEngine.ts","src/features/search/globalSearch.test.ts","src/features/search/GlobalSearchPage.tsx"],strengths:["Search entries contain title, subtitle, description and keywords."],gaps:["Ranking weights, exact-title precedence and category intent are not independently certified."],exitCriteria:["Independent ranking oracle","Exact/prefix/keyword precedence","Stable tie-break contract"]},
  {id:"keyboard-mobile-discovery",title:"Keyboard and Mobile Discovery",priority:"P1",status:"queued",playerQuestion:"Can I open search, move through results and reach a destination with keyboard or touch on small screens?",evidence:["src/shared/commands/CommandPalette.tsx","src/shared/layout/PageShell.tsx","src/styles/28-global-search.css","e2e/mobile-accessibility-performance.spec.ts"],strengths:["Command palette and responsive search UI exist."],gaps:["Keyboard focus order, Enter activation, touch containment and back navigation are not closed together."],exitCriteria:["Keyboard journey E2E","Mobile touch E2E","Focus and horizontal containment contract"]},
  {id:"deep-link-query-continuity",title:"Deep Link and Query Continuity",priority:"P2",status:"monitor",playerQuestion:"Do search query, category and destination filters survive reload and shareable links?",evidence:["src/features/search/GlobalSearchPage.tsx","src/features/help/HelpCenter.tsx","src/features/characters/Characters.tsx"],strengths:["Global search and help already use URL search parameters."],gaps:["Cross-route query handoff and reload continuity are not measured as one policy."],exitCriteria:["Query schema","Reload/share matrix","Destination filter parity"]},
  {id:"recent-favorite-navigation",title:"Recent and Favorite Navigation",priority:"P2",status:"monitor",playerQuestion:"Can I quickly return to recently opened or favorite content without repeating a search?",evidence:["src/shared/favorites/FavoritesProvider.tsx","src/features/search/GlobalSearchPage.tsx","src/features/collections/CollectionsPage.tsx"],strengths:["Favorites, recents and collections foundations exist."],gaps:["Ordering, stale-target cleanup and cross-surface continuity are not release-gated."],exitCriteria:["Recent ordering contract","Dead favorite cleanup","Search/collections continuity"]},
] as const;
export function buildNavigationSearchDiscovery(version="5.123.0") {
 const selected=NAVIGATION_SEARCH_DOMAINS.filter(d=>d.status==="selected");
 const evidenceCount=new Set(NAVIGATION_SEARCH_DOMAINS.flatMap(d=>d.evidence)).size;
 const counts={P0:NAVIGATION_SEARCH_DOMAINS.filter(d=>d.priority==="P0").length,P1:NAVIGATION_SEARCH_DOMAINS.filter(d=>d.priority==="P1").length,P2:NAVIGATION_SEARCH_DOMAINS.filter(d=>d.priority==="P2").length};
 const blockers=NAVIGATION_SEARCH_DOMAINS.filter(d=>d.priority!=="P2").flatMap(d=>d.gaps.map(g=>`${d.id}: ${g}`));
 return {package:"v5.123A",version,status:selected.length===1&&blockers.length>0?"READY_FOR_ROUTE_SEARCH_MATRIX":"BLOCKED",selectedDomain:selected[0]?.id??null,nextPackage:"v5.123B",domainCount:NAVIGATION_SEARCH_DOMAINS.length,evidenceCount,counts,blockers,domains:NAVIGATION_SEARCH_DOMAINS} as const;
}
