import { describe, expect, it } from "vitest";
import type { DndItemData } from "./ruleset.types";
import { getBarbarianCombatFeatures, getBrutalCriticalExtraDice, getBrutalStrike, getPrimalChampion, getRageDamageBonus, getRageUses, getRelentlessRageRecoveryHp, getWeaponMasteryCount, isRageDamageWeapon, reduceRageDamage } from "./barbarianRules";
describe("barbarian rules",()=>{
 it("scales Rage damage and uses by edition",()=>{expect(getRageDamageBonus(1)).toBe(2);expect(getRageDamageBonus(9)).toBe(3);expect(getRageDamageBonus(16)).toBe(4);expect(getRageUses(20,"dnd_2014")).toBe("unlimited");expect(getRageUses(20,"dnd_2024")).toBe(6)});
 it("limits Rage damage by edition and attack ability",()=>{const melee={category:"weapon",properties:["Heavy"]}as DndItemData;const thrown={category:"weapon",range:"20/60",properties:["Thrown"]}as DndItemData;expect(isRageDamageWeapon(melee,"dnd_2014","str")).toBe(true);expect(isRageDamageWeapon(thrown,"dnd_2014","str")).toBe(false);expect(isRageDamageWeapon(thrown,"dnd_2024","str")).toBe(true);expect(isRageDamageWeapon(thrown,"dnd_2024","dex")).toBe(false)});
 it("halves physical damage and separates Brutal Critical from Brutal Strike",()=>{expect(reduceRageDamage(9,true,true)).toBe(4);expect(reduceRageDamage(9,true,false)).toBe(9);expect(getBrutalCriticalExtraDice(17,"dnd_2014")).toBe(3);expect(getBrutalCriticalExtraDice(17,"dnd_2024")).toBe(0);expect(getBrutalStrike(17,"dnd_2024")).toMatchObject({dice:2,effectCount:2})});
 it("matches 2024 weapon mastery progression",()=>{expect(getWeaponMasteryCount(1,"dnd_2024")).toBe(2);expect(getWeaponMasteryCount(4,"dnd_2024")).toBe(3);expect(getWeaponMasteryCount(10,"dnd_2024")).toBe(4)});
 it("matches Relentless Rage and Primal Champion edition differences",()=>{expect(getRelentlessRageRecoveryHp(11,"dnd_2014")).toBe(1);expect(getRelentlessRageRecoveryHp(11,"dnd_2024")).toBe(22);expect(getPrimalChampion(20,"dnd_2014").maximum).toBe(24);expect(getPrimalChampion(20,"dnd_2024").maximum).toBe(25)});
 it("exposes edition-specific combat features",()=>{expect(getBarbarianCombatFeatures(7,"dnd_2024")).toMatchObject({primalKnowledge:true,instinctivePounce:true});expect(getBarbarianCombatFeatures(7,"dnd_2014")).toMatchObject({primalKnowledge:false,instinctivePounce:false})});
});
