import type { Character } from "../character/character.types";
import { normalizeClassLevels } from "./multiclassRules";
import type { RulesetData } from "./ruleset.types";
import { getCharacterFeatures } from "./characterSheetRules";
import { getCharacterSpellcastingClasses } from "./multiclassSpellcastingSeparation";
export interface CharacterSheetCertificationSnapshot { classCount:number;classSummary:string;featureCount:number;usableResourceCount:number;exhaustedResourceCount:number;knownSpellCount:number;preparedSpellCount:number;spellcastingClassCount:number;activeConditionCount:number;activeEffectCount:number;equippedItemCount:number;attunedItemCount:number;sectionCoverage:Record<"identity"|"combat"|"skills"|"features"|"equipment"|"spells"|"resources",boolean> }
export function getCharacterSheetCertificationSnapshot(character:Character,rulesetData:RulesetData|null):CharacterSheetCertificationSnapshot {
 const classLevels=normalizeClassLevels(character.classLevels,character.className,character.level);const resources=character.resources??[];const inventory=character.inventory??[];const features=getCharacterFeatures(character,rulesetData);const spellcastingClasses=getCharacterSpellcastingClasses(character,rulesetData);
 return {classCount:classLevels.length,classSummary:classLevels.map(entry=>`${entry.className} ${entry.level}`).join(" · "),featureCount:features.length,usableResourceCount:resources.filter(r=>r.unlimited||r.used<r.max).length,exhaustedResourceCount:resources.filter(r=>!r.unlimited&&r.used>=r.max).length,knownSpellCount:(character.knownSpellIds??[]).length,preparedSpellCount:(character.preparedSpellIds??[]).length,spellcastingClassCount:spellcastingClasses.length,activeConditionCount:character.conditions.length,activeEffectCount:character.activeSpellEffects?.length??0,equippedItemCount:(character.equippedArmorId?1:0)+(character.equippedShieldId?1:0)+character.equippedWeaponIds.length,attunedItemCount:inventory.filter(e=>e.attuned).length,sectionCoverage:{identity:Boolean(character.name&&character.className&&character.level>0),combat:character.maxHp>0&&Number.isFinite(character.armorClass),skills:Array.isArray(character.skillProficiencies),features:Boolean(character.className),equipment:Array.isArray(character.inventory),spells:spellcastingClasses.length===0||Array.isArray(character.knownSpellIds),resources:Array.isArray(character.resources)}};
}
