import type { DndClassData,DndRaceData,DndSubclassData } from "./ruleset.types";
import { getChannelDivinityUses,getClericCantripCount,getClericCombatFeatures,getClericPreparedSpellLimit,getClericSubclassFeatureLevels,getClericSubclassLevel,getDestroyUndeadCr,getDivineSparkDice,type ClericEdition } from "./clericRules";

export type ClericCertificationRow={ruleset:ClericEdition;raceId:string;raceName:string;subclassId:string;subclassName:string;level:number;ready:boolean;blockers:string[];warnings:string[];expected:{channelDivinityUses:number;cantripCount:number;preparedSpellLimit:number;divineSparkDice:number;destroyUndeadCr:number|null;searUndead:boolean;blessedStrikes:boolean;improvedBlessedStrikes:boolean;divineIntervention:boolean;capstone:"improved-divine-intervention"|"greater-divine-intervention"|null}};
const special2024=new Set(["Human","Dragonborn","Elf","Gnome","Goliath","Tiefling","Aasimar"]);
export function certifyClericBuilder(ruleset:ClericEdition,cleric:DndClassData,races:DndRaceData[],subclasses:DndSubclassData[],wisdomModifier=4):ClericCertificationRow[]{
 const clericSubs=subclasses.filter(s=>s.className.toLowerCase()==="cleric"&&s.ruleset===ruleset);const rows:ClericCertificationRow[]=[];const subclassLevel=getClericSubclassLevel(ruleset);const requiredLevels=getClericSubclassFeatureLevels(ruleset);
 for(const race of races)for(const subclass of clericSubs)for(let level=1;level<=20;level+=1){const blockers:string[]=[];const warnings:string[]=[];const progression=cleric.levels.find(x=>x.level===level);
  if(!progression)blockers.push(`Level ${level} progression satırı eksik.`);if(cleric.hitDie!==8)blockers.push("Cleric Hit Die d8 olmalı.");if(!cleric.savingThrows.includes("wis")||!cleric.savingThrows.includes("cha"))blockers.push("WIS/CHA saving throw proficiency eksik.");if(cleric.skillChoices.choose!==2)blockers.push("Cleric başlangıçta iki skill seçebilmeli.");if(cleric.subclassLevel!==subclassLevel)blockers.push(`${ruleset} Cleric subclass seviyesi ${subclassLevel} olmalı.`);if(subclass.selectionLevel!==subclassLevel)blockers.push(`${subclass.name} selection level ${subclassLevel} olmalı.`);
  const featureLevels=[...new Set(subclass.features.map(f=>f.level))].sort((a,b)=>a-b);for(const req of requiredLevels)if(!featureLevels.includes(req))blockers.push(`${subclass.name} level ${req} özelliği eksik.`);if(level<subclassLevel&&subclass.features.some(f=>f.level<=level))blockers.push("Subclass özelliği seçim seviyesinden önce açılıyor.");
  if(ruleset==="dnd_2014"&&race.subraces?.length)warnings.push(`${race.name} için subrace seçimi zorunlu tutulmalı.`);if(ruleset==="dnd_2014"&&race.name==="Half-Elf")warnings.push("Half-Elf +1/+1, skill ve language seçimleri doğrulanmalı.");if(ruleset==="dnd_2024"&&Object.keys(race.abilityBonuses).length)blockers.push(`${race.name} 2024 ability bonusunu species üzerinden vermemeli.`);if(ruleset==="dnd_2024"&&special2024.has(race.name))warnings.push(`${race.name} species alt seçimleri Cleric Builder choice debt içinde çözülmeli.`);
  if(ruleset==="dnd_2014"&&subclass.id!=="life-domain")warnings.push(`${subclass.name} lisans/source ve domain-specific runtime ayrıntıları ayrıca doğrulanmalı.`);if(ruleset==="dnd_2024"&&subclass.id!=="life-domain-2024")warnings.push(`${subclass.name} tam PHB içeriğidir; varsayılan dağıtım lisansı ayrıca doğrulanmalı.`);
  const features=getClericCombatFeatures(level,ruleset);rows.push({ruleset,raceId:race.id,raceName:race.name,subclassId:subclass.id,subclassName:subclass.name,level,ready:blockers.length===0,blockers,warnings,expected:{channelDivinityUses:getChannelDivinityUses(level,ruleset),cantripCount:getClericCantripCount(level),preparedSpellLimit:getClericPreparedSpellLimit(level,ruleset,wisdomModifier),divineSparkDice:ruleset==="dnd_2024"&&level>=2?getDivineSparkDice(level):0,destroyUndeadCr:ruleset==="dnd_2014"?getDestroyUndeadCr(level):null,searUndead:features.searUndead,blessedStrikes:features.blessedStrikes,improvedBlessedStrikes:features.improvedBlessedStrikes,divineIntervention:features.divineIntervention,capstone:level>=20?(ruleset==="dnd_2024"?"greater-divine-intervention":"improved-divine-intervention"):null}})}return rows;
}
export function summarizeClericCertification(rows:ClericCertificationRow[]){const blockers=rows.flatMap(r=>r.blockers.map(m=>`${r.ruleset}/${r.raceName}/${r.subclassName}/L${r.level}: ${m}`));const warnings=rows.flatMap(r=>r.warnings.map(m=>`${r.ruleset}/${r.raceName}/${r.subclassName}/L${r.level}: ${m}`));return{ready:blockers.length===0,scenarioCount:rows.length,readyCount:rows.filter(r=>r.ready).length,blockerCount:blockers.length,warningCount:warnings.length,blockers:[...new Set(blockers)],warnings:[...new Set(warnings)]}}
