import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import type{DndClassData,DndRaceData,DndSubclassData}from"./ruleset.types";import{SUBCLASS_EXPANSION_2014,SUBCLASS_EXPANSION_2024}from"./subclassExpansion";import{certifyClericBuilder,summarizeClericCertification}from"./clericBuilderCertification";import{getChannelDivinityUses,getClericCombatFeatures,getClericPreparedSpellLimit,getDivineSparkDice}from"./clericRules";import{getSpellcastingProfile}from"./spellcastingRules";
const load=<T,>(path:string):T=>JSON.parse(readFileSync(new URL(`../../../${path}`,import.meta.url),"utf8")) as T;const merged=(edition:"2014"|"2024")=>{const base=load<DndSubclassData[]>(`public/data/dnd_${edition}/subclasses.json`);const exp=edition==="2014"?SUBCLASS_EXPANSION_2014:SUBCLASS_EXPANSION_2024;return[...base,...exp.filter(c=>!base.some(e=>e.id===c.id))]};function rows(edition:"2014"|"2024"){const classes=load<DndClassData[]>(`public/data/dnd_${edition}/classes.json`);const races=load<DndRaceData[]>(`public/data/dnd_${edition}/races.json`);return certifyClericBuilder(`dnd_${edition}`,classes.find(x=>x.id==="cleric")!,races,merged(edition));}const abilities={str:10,dex:12,con:14,int:10,wis:18,cha:10};
describe("Cleric full builder certification",()=>{
 it("certifies every 2014 race × domain × level combination",()=>{const result=rows("2014");expect(result).toHaveLength(9*14*20);expect(summarizeClericCertification(result)).toMatchObject({ready:true,scenarioCount:2520,blockerCount:0})});
 it("certifies every 2024 species × domain × level combination",()=>{const result=rows("2024");expect(result).toHaveLength(10*4*20);expect(summarizeClericCertification(result)).toMatchObject({ready:true,scenarioCount:800,blockerCount:0})});
 it("matches official Channel Divinity and Divine Spark progressions",()=>{expect(getChannelDivinityUses(2,"dnd_2014")).toBe(1);expect(getChannelDivinityUses(18,"dnd_2014")).toBe(3);expect(getChannelDivinityUses(2,"dnd_2024")).toBe(2);expect(getChannelDivinityUses(18,"dnd_2024")).toBe(4);expect(getDivineSparkDice(2)).toBe(1);expect(getDivineSparkDice(18)).toBe(4)});
 it("matches 2024 prepared spell table instead of WIS plus level",()=>{const cleric=load<DndClassData[]>("public/data/dnd_2024/classes.json").find(x=>x.id==="cleric")!;expect(getClericPreparedSpellLimit(10,"dnd_2024",4)).toBe(15);expect(getSpellcastingProfile(cleric,10,abilities,"dnd_2024")).toMatchObject({cantripLimit:5,preparedSpellLimit:15})});
 it("distinguishes Destroy Undead from Sear Undead",()=>{expect(getClericCombatFeatures(8,"dnd_2014")).toMatchObject({destroyUndead:1,searUndead:false});expect(getClericCombatFeatures(8,"dnd_2024")).toMatchObject({destroyUndead:null,searUndead:true,blessedStrikes:true})});
 it("contains complete domain checkpoints",()=>{const s14=merged("2014").filter(x=>x.className==="Cleric");const s24=merged("2024").filter(x=>x.className==="Cleric");expect(s14).toHaveLength(14);expect(s24).toHaveLength(4);for(const s of s14)expect([...new Set(s.features.map(x=>x.level))]).toEqual([1,2,6,8,17]);for(const s of s24)expect([...new Set(s.features.map(x=>x.level))]).toEqual([3,6,17])});
});
