import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import type{DndClassData,DndRaceData,DndSubclassData}from"./ruleset.types";import{SUBCLASS_EXPANSION_2014,SUBCLASS_EXPANSION_2024}from"./subclassExpansion";import{certifyDruidBuilder,summarizeDruidCertification}from"./druidBuilderCertification";import{getDruidCombatFeatures,getDruidPreparedSpellLimit,getNaturalRecoveryBudget,getWildShapeKnownForms,getWildShapeMaxCr,getWildShapeUses}from"./druidRules";import{getSpellcastingProfile}from"./spellcastingRules";
const load=<T,>(p:string):T=>JSON.parse(readFileSync(new URL(`../../../${p}`,import.meta.url),"utf8"))as T;const merged=(e:"2014"|"2024")=>{const base=load<DndSubclassData[]>(`public/data/dnd_${e}/subclasses.json`);const exp=e==="2014"?SUBCLASS_EXPANSION_2014:SUBCLASS_EXPANSION_2024;return[...base,...exp.filter(x=>!base.some(b=>b.id===x.id))]};function rows(e:"2014"|"2024"){const classes=load<DndClassData[]>(`public/data/dnd_${e}/classes.json`);const races=load<DndRaceData[]>(`public/data/dnd_${e}/races.json`);return certifyDruidBuilder(`dnd_${e}`,classes.find(x=>x.id==="druid")!,races,merged(e))}const abilities={str:10,dex:12,con:14,int:10,wis:18,cha:10};
describe("Druid full builder certification",()=>{
it("certifies every 2014 race × circle × level combination",()=>{const r=rows("2014");expect(r).toHaveLength(9*3*20);expect(summarizeDruidCertification(r)).toMatchObject({ready:true,scenarioCount:540,blockerCount:0})});
it("certifies every 2024 species × circle × level combination",()=>{const r=rows("2024");expect(r).toHaveLength(10*4*20);expect(summarizeDruidCertification(r)).toMatchObject({ready:true,scenarioCount:800,blockerCount:0})});
it("matches Wild Shape uses and form progression",()=>{expect(getWildShapeUses(20,"dnd_2014")).toBe(Infinity);expect(getWildShapeUses(6,"dnd_2024")).toBe(3);expect(getWildShapeUses(17,"dnd_2024")).toBe(4);expect(getWildShapeKnownForms(2,"dnd_2024")).toBe(4);expect(getWildShapeKnownForms(8,"dnd_2024")).toBe(8);expect(getWildShapeMaxCr(6,"dnd_2014","Circle of the Moon")).toBe(2)});
it("matches 2024 prepared spell table",()=>{const druid=load<DndClassData[]>("public/data/dnd_2024/classes.json").find(x=>x.id==="druid")!;expect(getDruidPreparedSpellLimit(10,"dnd_2024",4)).toBe(15);expect(getSpellcastingProfile(druid,20,abilities,"dnd_2024")).toMatchObject({cantripLimit:4,preparedSpellLimit:22})});
it("separates edition capstones",()=>{expect(getDruidCombatFeatures(20,"dnd_2014")).toMatchObject({unlimitedWildShape:true,evergreenWildShape:false,natureMagician:false});expect(getDruidCombatFeatures(20,"dnd_2024")).toMatchObject({unlimitedWildShape:false,evergreenWildShape:true,natureMagician:true})});
it("matches Land recovery and subclass checkpoints",()=>{expect(getNaturalRecoveryBudget(5,"dnd_2014")).toBe(3);expect(getNaturalRecoveryBudget(6,"dnd_2024")).toBe(3);const s14=merged("2014").filter(x=>x.className==="Druid");const s24=merged("2024").filter(x=>x.className==="Druid");expect(s14).toHaveLength(3);expect(s24).toHaveLength(4);expect([...new Set(s14.find(x=>/Land/.test(x.name))!.features.map(x=>x.level))]).toEqual([2,3,6,10,14]);for(const s of s24)expect([...new Set(s.features.map(x=>x.level))]).toEqual([3,6,10,14])});
});
