import type{AbilityScores,CharacterInventoryItem}from"../character/character.types";import type{DndClassData,DndItemData}from"./ruleset.types";
export type EquipmentLegality={proficient:boolean;meetsStrength:boolean;speedPenalty:number;stealthDisadvantage:boolean;issues:string[]};
const normalized=(values:string[])=>(values??[]).map(value=>value.toLowerCase());
export function getEquipmentLegality(item:DndItemData,classProfiles:DndClassData[],abilities:AbilityScores):EquipmentLegality{const armor=classProfiles.flatMap(item=>normalized(item.armorProficiencies));const weapons=classProfiles.flatMap(item=>normalized(item.weaponProficiencies));let proficient=true;if(item.category==="armor")proficient=armor.some(value=>value.includes(item.armorType??"")||value.includes(item.name.toLowerCase())||value.includes("all armor"));if(item.category==="shield")proficient=armor.some(value=>value.includes("shield"));if(item.category==="weapon")proficient=weapons.some(value=>value.includes(item.weaponCategory??"")||value.includes(item.name.toLowerCase())||value.includes("all weapon"));const meetsStrength=!item.strengthRequirement||abilities.str>=item.strengthRequirement;const issues:string[]=[];if(!proficient)issues.push("Proficiency yok");if(!meetsStrength)issues.push(`STR ${item.strengthRequirement} gerekli`);return{proficient,meetsStrength,speedPenalty:meetsStrength?0:10,stealthDisadvantage:Boolean(item.stealthDisadvantage),issues}}
export function getCarryingCapacity(strength:number){return Math.max(0,Math.floor(strength))*15}
export function getInventoryWeight(inventory:CharacterInventoryItem[],items:DndItemData[]){return inventory.reduce((sum,entry)=>sum+(items.find(item=>item.id===entry.itemId)?.weight??0)*entry.quantity,0)}
export function getEncumbrance(strength:number,weight:number){const capacity=getCarryingCapacity(strength);return{weight,capacity,encumbered:weight>capacity,overloaded:weight>capacity*2,speedPenalty:weight>capacity*2?20:weight>capacity?10:0}}
export function findAmmunitionId(weapon:DndItemData,items:DndItemData[]){if(!weapon.properties?.some(value=>/ammunition/i.test(value))&&!weapon.tags?.includes("ammunition"))return null;const name=weapon.name.toLowerCase();const pattern=name.includes("crossbow")?/(bolt)/:name.includes("blowgun")?/(needle)/:/(arrow)/;return items.find(item=>item.category==="ammunition"&&pattern.test(item.name.toLowerCase()))?.id??null}
export function consumeAmmunition(inventory:CharacterInventoryItem[],ammoId:string|null){if(!ammoId)return inventory;const entry=inventory.find(item=>item.itemId===ammoId);if(!entry||entry.quantity<=0)return null;return entry.quantity===1?inventory.filter(item=>item.itemId!==ammoId):inventory.map(item=>item.itemId===ammoId?{...item,quantity:item.quantity-1}:item)}
