import { describe, expect, it } from "vitest";
import type { Character } from "../character/character.types";
import type { DndItemData } from "./ruleset.types";
import { addInventoryItem, equipInventoryItem, setInventoryQuantity, spendItemCharge, toggleItemAttunement, useInventoryItem } from "./inventoryActionRuntime-N-MEGA8";
const character = (): Character => ({ id:"c",name:"Hero",playerName:"P",ruleset:"dnd_2024",race:"Human",className:"Fighter",subclass:"",background:"Soldier",featIds:[],skillProficiencies:[],expertiseSkills:[],toolProficiencies:[],languages:[],level:5,abilities:{str:16,dex:14,con:14,int:10,wis:10,cha:10},maxHp:40,currentHp:20,tempHp:0,armorClass:10,armorClassMode:"auto",knownSpellIds:[],preparedSpellIds:[],spellSlots:[],inventory:[],equippedArmorId:null,equippedShieldId:null,equippedWeaponIds:[],gold:10,deathSaves:{successes:0,failures:0},hitDice:[],resources:[],exhaustion:0,conditionDurations:{},conditions:[],notes:"",createdAt:"x",updatedAt:"x" });
const item = (patch: Partial<DndItemData>): DndItemData => ({id:"sword",name:"Sword",category:"weapon",cost:"10 gp",weight:3,description:"",...patch});
describe("N-MEGA8 inventory actions",()=>{
 it("adds, equips and removes inventory safely",()=>{const added=addInventoryItem(character(),"sword",2);expect(added.ok).toBe(true);if(!added.ok)return;const equipped=equipInventoryItem(added.character,item({}));expect(equipped.ok&&equipped.character.equippedWeaponIds).toEqual(["sword"]);const removed=setInventoryQuantity(equipped.character,"sword",0);expect(removed.ok&&removed.character.equippedWeaponIds).toEqual([])});
 it("enforces three attunement slots",()=>{const base={...character(),inventory:[1,2,3,4].map(n=>({itemId:`i${n}`,quantity:1,attuned:n<4}))};const result=toggleItemAttunement(base,item({id:"i4",requiresAttunement:true}));expect(result.ok).toBe(false)});
 it("spends charges without overdrawing",()=>{const charged=item({id:"wand",category:"gear",charges:3,chargeCost:2});const base={...character(),inventory:[{itemId:"wand",quantity:1,chargesUsed:1}]};expect(spendItemCharge(base,charged).ok).toBe(true);const exhausted={...base,inventory:[{itemId:"wand",quantity:1,chargesUsed:2}]};expect(spendItemCharge(exhausted,charged).ok).toBe(false)});
 it("uses healing consumables and decrements quantity",()=>{const potion=item({id:"potion",category:"gear",tags:["consumable"],healingFormula:"2d4+2"});const base={...character(),inventory:[{itemId:"potion",quantity:2}]};const result=useInventoryItem(base,potion,()=>0);expect(result.ok).toBe(true);if(!result.ok)return;expect(result.character.currentHp).toBe(24);expect(result.character.inventory[0].quantity).toBe(1)});
});
