import type { DndItemData, WeaponMastery } from "./ruleset.types";

type WeaponSeed = [string, string, string, number, string, string, "simple" | "martial", string[], string?, WeaponMastery?];
const weaponSeeds: WeaponSeed[] = [
  ["greatclub","Greatclub","2 sp",10,"1d8","bludgeoning","simple",["Two-Handed"],undefined,"Push"],
  ["javelin","Javelin","5 sp",2,"1d6","piercing","simple",["Thrown"],"30/120","Slow"],
  ["light-hammer","Light Hammer","2 gp",2,"1d4","bludgeoning","simple",["Light","Thrown"],"20/60","Nick"],
  ["sickle","Sickle","1 gp",2,"1d4","slashing","simple",["Light"],undefined,"Nick"],
  ["spear","Spear","1 gp",3,"1d6","piercing","simple",["Thrown","Versatile 1d8"],"20/60","Sap"],
  ["dart","Dart","5 cp",0.25,"1d4","piercing","simple",["Finesse","Thrown"],"20/60","Vex"],
  ["battleaxe","Battleaxe","10 gp",4,"1d8","slashing","martial",["Versatile 1d10"],undefined,"Topple"],
  ["flail","Flail","10 gp",2,"1d8","bludgeoning","martial",[],undefined,"Sap"],
  ["glaive","Glaive","20 gp",6,"1d10","slashing","martial",["Heavy","Reach","Two-Handed"],undefined,"Graze"],
  ["greataxe","Greataxe","30 gp",7,"1d12","slashing","martial",["Heavy","Two-Handed"],undefined,"Cleave"],
  ["halberd","Halberd","20 gp",6,"1d10","slashing","martial",["Heavy","Reach","Two-Handed"],undefined,"Cleave"],
  ["lance","Lance","10 gp",6,"1d12","piercing","martial",["Reach","Special"],undefined,"Topple"],
  ["maul","Maul","10 gp",10,"2d6","bludgeoning","martial",["Heavy","Two-Handed"],undefined,"Topple"],
  ["morningstar","Morningstar","15 gp",4,"1d8","piercing","martial",[],undefined,"Sap"],
  ["pike","Pike","5 gp",18,"1d10","piercing","martial",["Heavy","Reach","Two-Handed"],undefined,"Push"],
  ["scimitar","Scimitar","25 gp",3,"1d6","slashing","martial",["Finesse","Light"],undefined,"Nick"],
  ["trident","Trident","5 gp",4,"1d6","piercing","martial",["Thrown","Versatile 1d8"],"20/60","Topple"],
  ["war-pick","War Pick","5 gp",2,"1d8","piercing","martial",[],undefined,"Sap"],
  ["warhammer","Warhammer","15 gp",2,"1d8","bludgeoning","martial",["Versatile 1d10"],undefined,"Push"],
  ["whip","Whip","2 gp",3,"1d4","slashing","martial",["Finesse","Reach"],undefined,"Slow"],
  ["blowgun","Blowgun","10 gp",1,"1","piercing","martial",["Ammunition","Loading"],"25/100","Vex"],
  ["crossbow-hand","Hand Crossbow","75 gp",3,"1d6","piercing","martial",["Ammunition","Light","Loading"],"30/120","Vex"],
  ["crossbow-heavy","Heavy Crossbow","50 gp",18,"1d10","piercing","martial",["Ammunition","Heavy","Loading","Two-Handed"],"100/400","Push"],
  ["net","Net","1 gp",3,"0","special","martial",["Special","Thrown"],"5/15","Slow"],
];

const weapons: DndItemData[] = weaponSeeds.map(([id,name,cost,weight,damage,damageType,weaponCategory,properties,range,mastery]) => ({
  id,name,cost,weight,damage,damageType,weaponCategory,properties,range,mastery,category:"weapon",
  description:`${weaponCategory === "simple" ? "Simple" : "Martial"} weapon; ${damage} ${damageType} damage.`,
}));

const common: DndItemData[] = [
  {id:"arrows-20",name:"Arrows (20)",category:"ammunition",cost:"1 gp",weight:1,quantityInBundle:20,tags:["consumable","arrow"],description:"Shortbow ve longbow için 20 ok."},
  {id:"crossbow-bolts-20",name:"Crossbow Bolts (20)",category:"ammunition",cost:"1 gp",weight:1.5,quantityInBundle:20,tags:["consumable","bolt"],description:"Crossbow türleri için 20 bolt."},
  {id:"blowgun-needles-50",name:"Blowgun Needles (50)",category:"ammunition",cost:"1 gp",weight:1,quantityInBundle:50,tags:["consumable","needle"],description:"Blowgun için 50 needle."},
  {id:"thieves-tools",name:"Thieves' Tools",category:"tool",cost:"25 gp",weight:1,tags:["tool"],description:"Kilit, tuzak ve benzeri hassas mekanizmalar üzerinde çalışmak için araç seti."},
  {id:"herbalism-kit",name:"Herbalism Kit",category:"tool",cost:"5 gp",weight:3,tags:["kit"],description:"Bitkileri tanımlama ve bitkisel ürün hazırlama araçları."},
  {id:"disguise-kit",name:"Disguise Kit",category:"tool",cost:"25 gp",weight:3,tags:["kit"],description:"Görünüşü geçici olarak değiştiren makyaj ve aksesuar seti."},
  {id:"poisoners-kit",name:"Poisoner's Kit",category:"tool",cost:"50 gp",weight:2,tags:["kit"],description:"Zehirleri inceleme ve güvenli biçimde işleme araçları."},
  {id:"navigators-tools",name:"Navigator's Tools",category:"tool",cost:"25 gp",weight:2,tags:["tool"],description:"Harita, yön ve rota belirleme için kullanılan araçlar."},
  {id:"backpack",name:"Backpack",category:"gear",cost:"2 gp",weight:5,tags:["container"],description:"Ekipman ve erzak taşımaya uygun sırt çantası."},
  {id:"bedroll",name:"Bedroll",category:"gear",cost:"1 gp",weight:7,tags:["camping"],description:"Yolculuk sırasında dinlenmek için taşınabilir yatak takımı."},
  {id:"crowbar",name:"Crowbar",category:"gear",cost:"2 gp",weight:5,tags:["adventuring"],description:"Kaldırma ve zorlama işlerinde mekanik avantaj sağlayan sağlam çubuk."},
  {id:"tinderbox",name:"Tinderbox",category:"gear",cost:"5 sp",weight:1,tags:["camping"],description:"Meşale, kamp ateşi ve benzeri ateşleri yakma seti."},
  {id:"waterskin",name:"Waterskin",category:"gear",cost:"2 sp",weight:5,tags:["container"],description:"Yolculukta içme suyu taşımak için deri kap."},
];

const magicItems: DndItemData[] = [
  {id:"potion-greater-healing",name:"Potion of Greater Healing",category:"gear",cost:"rare",weight:0.5,magical:true,rarity:"uncommon",tags:["consumable","potion"],description:"Restores 4d4 + 4 hit points when consumed."},
  {id:"bag-of-holding",name:"Bag of Holding",category:"gear",cost:"uncommon",weight:15,magical:true,rarity:"uncommon",tags:["container"],description:"Büyülü iç hacmi ağırlık ve taşıma kapasitesini olağan sınırların ötesine taşır."},
  {id:"boots-of-elvenkind",name:"Boots of Elvenkind",category:"gear",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",description:"Adımların sesini bastırarak sessiz hareketi destekler."},
  {id:"cloak-of-protection",name:"Cloak of Protection",category:"gear",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",requiresAttunement:true,armorBonus:1,description:"Attuned kullanıcının AC ve saving throw değerlerini 1 artırır."},
  {id:"ring-of-protection",name:"Ring of Protection",category:"gear",cost:"rare",weight:0,magical:true,rarity:"rare",requiresAttunement:true,armorBonus:1,description:"Attuned kullanıcının AC ve saving throw değerlerini 1 artırır."},
  {id:"pearl-of-power",name:"Pearl of Power",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",requiresAttunement:true,charges:1,chargeRecovery:"daily",description:"Bir charge harcayarak kullanılmış düşük seviyeli spell slotlarından birini yeniler."},
  {id:"wand-of-magic-detection",name:"Wand of Magic Detection",category:"gear",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",charges:3,chargeRecovery:"1d3 daily",grantedSpellName:"Detect Magic",chargeCost:1,description:"Bir charge harcayarak Detect Magic etkisi üretir."},
  {id:"wand-of-magic-missiles",name:"Wand of Magic Missiles",category:"gear",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Magic Missile",chargeCost:1,description:"Charge harcayarak Magic Missile etkisi üretir."},
  {id:"staff-of-healing",name:"Staff of Healing",category:"weapon",cost:"rare",weight:4,magical:true,rarity:"rare",requiresAttunement:true,charges:10,chargeRecovery:"1d6+4 daily",grantedSpellName:"Cure Wounds",chargeCost:1,damage:"1d6",damageType:"bludgeoning",weaponCategory:"simple",properties:["Versatile 1d8"],description:"Charge harcayarak Cure Wounds uygulayabilen büyülü staff."},
  {id:"longsword-plus-1",name:"Longsword +1",category:"weapon",cost:"uncommon",weight:3,magical:true,rarity:"uncommon",attackBonus:1,damageBonus:1,damage:"1d8",damageType:"slashing",weaponCategory:"martial",properties:["Versatile 1d10"],description:"Attack ve damage roll değerlerine +1 veren büyülü longsword."},
  {id:"potion-superior-healing",name:"Potion of Superior Healing",category:"gear",cost:"rare",weight:0.5,magical:true,rarity:"rare",tags:["consumable","potion"],description:"Restores 8d4 + 8 hit points when consumed."},
  {id:"potion-climbing",name:"Potion of Climbing",category:"gear",cost:"common",weight:0.5,magical:true,rarity:"common",tags:["consumable","potion"],description:"Bir saat boyunca tırmanma hareketini destekler."},
  {id:"dust-of-disappearance",name:"Dust of Disappearance",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",tags:["consumable"],description:"Yakındaki hedefleri kısa süre görünmez yapan büyülü toz."},
  {id:"eyes-of-charming",name:"Eyes of Charming",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",requiresAttunement:true,charges:3,chargeRecovery:"daily",grantedSpellName:"Charm Person",chargeCost:1,description:"Charge harcayarak charm etkisi dener."},
  {id:"gem-of-brightness",name:"Gem of Brightness",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",charges:50,description:"Charge harcayarak ışık veya kör edici ışın oluşturur."},
  {id:"ring-of-swimming",name:"Ring of Swimming",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",description:"Kullanıcıya hızlı yüzme hareketi sağlar."},
  {id:"shield-plus-1",name:"Shield +1",category:"shield",cost:"uncommon",weight:6,magical:true,rarity:"uncommon",armorClassBonus:3,description:"Kuşanıldığında toplam +3 AC sağlayan büyülü shield."},
  {id:"chain-mail-plus-1",name:"Chain Mail +1",category:"armor",cost:"rare",weight:55,magical:true,rarity:"rare",armorClass:17,armorType:"heavy",strengthRequirement:13,stealthDisadvantage:true,description:"AC 17 sağlayan büyülü heavy armor."},
  {id:"dagger-plus-1",name:"Dagger +1",category:"weapon",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",attackBonus:1,damageBonus:1,damage:"1d4",damageType:"piercing",weaponCategory:"simple",properties:["Finesse","Light","Thrown"],range:"20/60",description:"Attack ve damage roll değerlerine +1 veren büyülü dagger."},
  {id:"longbow-plus-1",name:"Longbow +1",category:"weapon",cost:"uncommon",weight:2,magical:true,rarity:"uncommon",attackBonus:1,damageBonus:1,damage:"1d8",damageType:"piercing",weaponCategory:"martial",properties:["Ammunition","Heavy","Two-Handed"],range:"150/600",description:"Attack ve damage roll değerlerine +1 veren büyülü longbow."},
  {id:"wand-of-web",name:"Wand of Web",category:"gear",cost:"uncommon",weight:1,magical:true,rarity:"uncommon",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Web",chargeCost:1,description:"Charge harcayarak Web büyüsü kullanır."},
  {id:"wand-of-fireballs",name:"Wand of Fireballs",category:"gear",cost:"rare",weight:1,magical:true,rarity:"rare",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Fireball",chargeCost:1,description:"Charge harcayarak Fireball büyüsü kullanır."},
  {id:"wand-of-lightning-bolts",name:"Wand of Lightning Bolts",category:"gear",cost:"rare",weight:1,magical:true,rarity:"rare",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Lightning Bolt",chargeCost:1,description:"Charge harcayarak Lightning Bolt büyüsü kullanır."},
  {id:"wand-of-fear",name:"Wand of Fear",category:"gear",cost:"rare",weight:1,magical:true,rarity:"rare",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Fear",chargeCost:1,description:"Charge harcayarak Fear büyüsü kullanır."},
  {id:"wand-of-paralysis",name:"Wand of Paralysis",category:"gear",cost:"rare",weight:1,magical:true,rarity:"rare",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Hold Person",chargeCost:1,description:"Charge harcayarak Hold Person etkisi kullanır."},
  {id:"wand-of-polymorph",name:"Wand of Polymorph",category:"gear",cost:"very-rare",weight:1,magical:true,rarity:"very-rare",requiresAttunement:true,charges:7,chargeRecovery:"1d6+1 daily",grantedSpellName:"Polymorph",chargeCost:1,description:"Charge harcayarak Polymorph büyüsü kullanır."},
  {id:"scroll-detect-magic",name:"Spell Scroll: Detect Magic",category:"gear",cost:"common",weight:0,magical:true,rarity:"common",tags:["consumable","scroll"],grantedSpellName:"Detect Magic",description:"Tek kullanımlık Detect Magic spell scroll."},
  {id:"scroll-cure-wounds",name:"Spell Scroll: Cure Wounds",category:"gear",cost:"common",weight:0,magical:true,rarity:"common",tags:["consumable","scroll"],grantedSpellName:"Cure Wounds",description:"Tek kullanımlık Cure Wounds spell scroll."},
  {id:"scroll-shield",name:"Spell Scroll: Shield",category:"gear",cost:"common",weight:0,magical:true,rarity:"common",tags:["consumable","scroll"],grantedSpellName:"Shield",description:"Tek kullanımlık Shield spell scroll."},
  {id:"scroll-invisibility",name:"Spell Scroll: Invisibility",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",tags:["consumable","scroll"],grantedSpellName:"Invisibility",description:"Tek kullanımlık Invisibility spell scroll."},
  {id:"scroll-lesser-restoration",name:"Spell Scroll: Lesser Restoration",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",tags:["consumable","scroll"],grantedSpellName:"Lesser Restoration",description:"Tek kullanımlık Lesser Restoration spell scroll."},
  {id:"scroll-fireball",name:"Spell Scroll: Fireball",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",tags:["consumable","scroll"],grantedSpellName:"Fireball",description:"Tek kullanımlık Fireball spell scroll."},
  {id:"scroll-revivify",name:"Spell Scroll: Revivify",category:"gear",cost:"uncommon",weight:0,magical:true,rarity:"uncommon",tags:["consumable","scroll"],grantedSpellName:"Revivify",description:"Tek kullanımlık Revivify spell scroll."},
  {id:"scroll-polymorph",name:"Spell Scroll: Polymorph",category:"gear",cost:"rare",weight:0,magical:true,rarity:"rare",tags:["consumable","scroll"],grantedSpellName:"Polymorph",description:"Tek kullanımlık Polymorph spell scroll."},
  {id:"scroll-greater-restoration",name:"Spell Scroll: Greater Restoration",category:"gear",cost:"rare",weight:0,magical:true,rarity:"rare",tags:["consumable","scroll"],grantedSpellName:"Greater Restoration",description:"Tek kullanımlık Greater Restoration spell scroll."},
  {id:"scroll-raise-dead",name:"Spell Scroll: Raise Dead",category:"gear",cost:"rare",weight:0,magical:true,rarity:"rare",tags:["consumable","scroll"],grantedSpellName:"Raise Dead",description:"Tek kullanımlık Raise Dead spell scroll."},
];

export const ITEM_EXPANSION_2014: DndItemData[] = [...weapons, ...common, ...magicItems];
export const ITEM_EXPANSION_2024: DndItemData[] = ITEM_EXPANSION_2014.map((item) => ({ ...item }));
