import type{DndClassData,RulesetData}from"./ruleset.types";import{auditClassProgression}from"./classProgressionAudit";
export type CertificationStatus="pass"|"warning"|"fail";export type CertificationCheck={id:string;label:string;status:CertificationStatus;detail:string};export type ClassCertification={className:string;coveredLevels:number;subclassCount:number;ready:boolean;issues:string[]};
const unique=(values:string[])=>new Set(values).size===values.length;
export function certifyClass(classData:DndClassData,subclassCount:number,ruleset:RulesetData["id"]):ClassCertification{const audit=auditClassProgression(classData,ruleset);const issues=[...audit.issues];if(subclassCount<1)issues.push("Seçilebilir subclass yok.");return{className:classData.name,coveredLevels:audit.coveredLevels,subclassCount,ready:issues.length===0,issues}}
export function getLevel20Certification(data:RulesetData|null){if(!data)return{score:0,certified:false,checks:[] as CertificationCheck[],classes:[] as ClassCertification[],blockers:["Ruleset yüklenemedi."]};const classes=data.classes.map(item=>certifyClass(item,data.subclasses.filter(sub=>sub.className===item.name).length,data.id));const classNames=new Set(data.classes.map(item=>item.name));const spellNames=new Set(data.spells.map(item=>item.name.toLowerCase()));const itemIds=new Set(data.items.map(item=>item.id));const unresolvedBonusSpells=data.subclasses.flatMap(sub=>(sub.bonusSpells??[]).filter(name=>!spellNames.has(name.toLowerCase())).map(name=>`${sub.name}: ${name}`));const unresolvedItemSpells=data.items.filter(item=>item.grantedSpellName&&!spellNames.has(item.grantedSpellName.toLowerCase())).map(item=>item.name);const brokenPackContents=data.items.flatMap(item=>(item.contents??[]).filter(content=>!itemIds.has(content.itemId)).map(content=>`${item.name}: ${content.itemId}`));const invalidFeatClasses=data.feats.flatMap(feat=>(feat.prerequisite?.classNames??[]).filter(name=>!classNames.has(name)).map(name=>`${feat.name}: ${name}`));const groups=[data.classes,data.subclasses,data.races,data.backgrounds,data.feats,data.spells,data.items];const idCount=groups.reduce((sum,group)=>sum+group.length,0);const idsUnique=groups.every(group=>unique(group.map(item=>item.id)));const levelCoverage=new Set(data.spells.map(item=>item.level));const checks:CertificationCheck[]=[
 {id:"classes",label:"12 class × level 1–20",status:data.classes.length===12&&classes.every(item=>item.ready)?"pass":"fail",detail:`${classes.filter(item=>item.ready).length}/${data.classes.length} class sertifikalı`},
 {id:"subclasses",label:"Her class için subclass",status:classes.every(item=>item.subclassCount>0)?"pass":"fail",detail:`${data.subclasses.length} subclass paketi`},
 {id:"spells",label:"Cantrip ve level 1–9 spell kapsamı",status:[0,1,2,3,4,5,6,7,8,9].every(level=>levelCoverage.has(level))?"pass":"fail",detail:`${data.spells.length} spell · ${unresolvedBonusSpells.length} çözülmemiş bonus spell`},
 {id:"references",label:"İçerik referans bütünlüğü",status:unresolvedBonusSpells.length||unresolvedItemSpells.length||brokenPackContents.length||invalidFeatClasses.length?"fail":"pass",detail:`Bonus spell ${unresolvedBonusSpells.length} · item spell ${unresolvedItemSpells.length} · pack ${brokenPackContents.length} · feat class ${invalidFeatClasses.length}`},
 {id:"ids",label:"Benzersiz entity kimlikleri",status:idsUnique?"pass":"fail",detail:`${idCount} entity kontrol edildi`},
 {id:"equipment",label:"Oynanabilir ekipman havuzu",status:data.items.some(item=>item.category==="weapon")&&data.items.some(item=>item.category==="armor")?"pass":"fail",detail:`${data.items.length} item`},
 {id:"origins",label:data.id==="dnd_2024"?"Species ve background":"Race ve background",status:data.races.length&&data.backgrounds.length?"pass":"fail",detail:`${data.races.length} köken · ${data.backgrounds.length} background`},
 ];const score=data.classes.length?Math.round(checks.reduce((sum,item)=>sum+(item.status==="pass"?1:item.status==="warning"?0.5:0),0)/checks.length*100):0;const blockers=[...checks.filter(item=>item.status==="fail").map(item=>`${item.label}: ${item.detail}`),...unresolvedBonusSpells,...unresolvedItemSpells.map(item=>`Item spell: ${item}`),...brokenPackContents,...invalidFeatClasses];return{score,certified:checks.every(item=>item.status!=="fail"),checks,classes,blockers}}
