import type{AbilityScores,CharacterClassLevel,CharacterHitDiePool,CharacterSpellSlot}from"../character/character.types";import type{DndClassData}from"./ruleset.types";
const requirements:Record<string,Partial<Record<keyof AbilityScores,number>>>={barbarian:{str:13},bard:{cha:13},cleric:{wis:13},druid:{wis:13},fighter:{str:13,dex:13},monk:{dex:13,wis:13},paladin:{str:13,cha:13},ranger:{dex:13,wis:13},rogue:{dex:13},sorcerer:{cha:13},warlock:{cha:13},wizard:{int:13}};
const hitDice:Record<string,number>={barbarian:12,fighter:10,paladin:10,ranger:10,bard:8,cleric:8,druid:8,monk:8,rogue:8,warlock:8,sorcerer:6,wizard:6};
const slots:Record<number,number[]>={1:[2],2:[3],3:[4,2],4:[4,3],5:[4,3,2],6:[4,3,3],7:[4,3,3,1],8:[4,3,3,2],9:[4,3,3,3,1],10:[4,3,3,3,2],11:[4,3,3,3,2,1],12:[4,3,3,3,2,1],13:[4,3,3,3,2,1,1],14:[4,3,3,3,2,1,1],15:[4,3,3,3,2,1,1,1],16:[4,3,3,3,2,1,1,1],17:[4,3,3,3,2,1,1,1,1],18:[4,3,3,3,3,1,1,1,1],19:[4,3,3,3,3,2,1,1,1],20:[4,3,3,3,3,2,2,1,1]};
export function normalizeClassLevels(value:CharacterClassLevel[]|undefined,className:string,totalLevel:number){const valid=(value??[]).filter(item=>item&&typeof item.className==="string"&&item.level>0).map(item=>({...item,level:Math.max(1,Math.min(20,Math.floor(item.level)))}));if(!valid.length)return[{className,level:Math.max(1,Math.min(20,totalLevel))}];const total=valid.reduce((sum,item)=>sum+item.level,0);return total===totalLevel?valid:[{className,level:Math.max(1,Math.min(20,totalLevel))}]}
export function getClassLevel(levels:CharacterClassLevel[],className:string){return levels.find(item=>item.className===className)?.level??0}
export function getMulticlassEligibility(className:string,abilities:AbilityScores){const req=requirements[className.toLowerCase()]??{};const missing=Object.entries(req).filter(([ability,min])=>abilities[ability as keyof AbilityScores]<(min??0)).map(([ability,min])=>`${ability.toUpperCase()} ${min}`);return{eligible:missing.length===0,missing}}
export function addClassLevel(levels:CharacterClassLevel[],className:string,subclass?:string){const found=levels.find(item=>item.className===className);return found?levels.map(item=>item.className===className?{...item,level:item.level+1,subclass:subclass??item.subclass}:item):[...levels,{className,level:1,subclass}]}
export function getCombinedCasterLevel(levels:CharacterClassLevel[],classes:DndClassData[]){return Math.min(20,levels.reduce((sum,item)=>{const progression=classes.find(candidate=>candidate.name===item.className)?.spellProgression;return sum+(progression==="full"?item.level:progression==="half"?Math.floor(item.level/2):progression==="third"?Math.floor(item.level/3):0)},0))}
export function getMulticlassSpellSlots(levels:CharacterClassLevel[],classes:DndClassData[],current:CharacterSpellSlot[]=[]){const casterLevel=getCombinedCasterLevel(levels,classes);const currentMap=new Map(current.map(item=>[item.level,item]));return(slots[casterLevel]??[]).map((max,index)=>({level:index+1,max,used:Math.min(max,currentMap.get(index+1)?.used??0)}))}
export function getMulticlassPactMagicSlots(levels:CharacterClassLevel[],classes:DndClassData[],current:CharacterSpellSlot[]=[]){const pactClass=levels.map(level=>({level,data:classes.find(item=>item.name===level.className)})).find(item=>item.data?.spellProgression==="pact");if(!pactClass?.data)return[];const pact=pactClass.data.levels.find(row=>row.level===pactClass.level.level)?.pactMagic;if(!pact)return[];return[{level:pact.slotLevel,max:pact.slots,used:Math.min(pact.slots,current[0]?.used??0)}]}
export function getMulticlassHitDice(levels:CharacterClassLevel[],current:CharacterHitDiePool[]=[]){const grouped=new Map<number,number>();for(const item of levels){const die=hitDice[item.className.toLowerCase()]??8;grouped.set(die,(grouped.get(die)??0)+item.level)}return[...grouped].sort((a,b)=>b[0]-a[0]).map(([die,max])=>({die,max,used:Math.min(max,current.find(item=>item.die===die)?.used??0)}))}
export function getMulticlassAttacksPerAction(levels:CharacterClassLevel[]){let attacks=1;for(const item of levels){const key=item.className.toLowerCase();if(key==="fighter")attacks=Math.max(attacks,item.level>=20?4:item.level>=11?3:item.level>=5?2:1);else if(["barbarian","monk","paladin","ranger"].includes(key)&&item.level>=5)attacks=Math.max(attacks,2)}return attacks}
