import type{RulesetId}from"../character/character.types";
export type PaladinEdition=Extract<RulesetId,"dnd_2014"|"dnd_2024">;
const prep2024=[0,2,3,4,5,6,6,7,7,9,9,10,10,11,11,12,12,14,14,15,15];
export function isPaladin(className:string){return className.trim().toLowerCase()==="paladin"}
export function getLayOnHandsPool(level:number){return Math.max(1,Math.min(20,Math.floor(level)))*5}
export function getLayOnHandsActionType(ruleset:PaladinEdition){return ruleset==="dnd_2024"?"bonus-action":"action" as const}
export function getPaladinPreparedSpellLimit(level:number,ruleset:PaladinEdition,charismaModifier=0){const safe=Math.max(1,Math.min(20,Math.floor(level)));return ruleset==="dnd_2024"?prep2024[safe]:safe<2?0:Math.max(1,charismaModifier+Math.floor(safe/2))}
export function getPaladinChannelDivinityUses(level:number,ruleset:PaladinEdition){const safe=Math.max(1,Math.min(20,Math.floor(level)));if(ruleset==="dnd_2014")return safe>=3?1:0;return safe<3?0:safe>=11?3:2}
export function getPaladinWeaponMasteryCount(level:number,ruleset:PaladinEdition){return ruleset==="dnd_2024"&&level>=1?2:0}
export function getDivineSmiteDice(slotLevel:number,ruleset:RulesetId,holyTarget=false){const safe=Math.max(1,Math.floor(slotLevel));if(ruleset==="dnd_2014")return Math.min(5,safe+1)+(holyTarget?1:0);return safe+1+(holyTarget?1:0)}
export function getPaladinSubclassLevel(){return 3}
export function getPaladinSubclassFeatureLevels(){return[3,7,15,20]}
export function getPaladinCoreFeatures(level:number,ruleset:PaladinEdition,charismaModifier=0){const safe=Math.max(1,Math.min(20,Math.floor(level)));const auraRadius=safe>=18?30:safe>=6?10:0;return{layOnHandsPool:getLayOnHandsPool(safe),layOnHandsAction:getLayOnHandsActionType(ruleset),preparedSpells:getPaladinPreparedSpellLimit(safe,ruleset,charismaModifier),weaponMasteryCount:getPaladinWeaponMasteryCount(safe,ruleset),fightingStyle:safe>=2,divineSmite:safe>=2,freeDivineSmite:ruleset==="dnd_2024"&&safe>=2,channelDivinityUses:getPaladinChannelDivinityUses(safe,ruleset),extraAttack:safe>=5,faithfulSteed:ruleset==="dnd_2024"&&safe>=5,auraProtection:safe>=6,auraRadius,abjureFoes:ruleset==="dnd_2024"&&safe>=9,auraCourage:safe>=10,radiantStrikes:safe>=11,restoringTouch:ruleset==="dnd_2024"&&safe>=14,cleansingTouch:ruleset==="dnd_2014"&&safe>=14,cleansingTouchUses:ruleset==="dnd_2014"&&safe>=14?Math.max(1,charismaModifier):0,auraExpansion:safe>=18}}
export function getPaladinAuraSummary(level:number,ruleset:PaladinEdition="dnd_2024"){const core=getPaladinCoreFeatures(level,ruleset);return{protection:core.auraProtection?{radius:core.auraRadius,summary:"Yakındaki müttefik saving throw sonuçlarına Charisma modifier desteği alır."}:null,courage:core.auraCourage?{radius:core.auraRadius,summary:"Yakındaki müttefikler frightened durumuna karşı korunur."}:null,radiantStrikes:core.radiantStrikes?`${ruleset==="dnd_2014"?"Melee weapon":"Melee weapon veya Unarmed Strike"} isabetleri ilave 1d8 radiant hasar taşır.`:null}}
