import type{DndFeatData,DndItemData,DndSpellData,DndSubclassData,RulesetData}from"./ruleset.types";
export type RuntimeTier="automatic"|"assisted"|"manual"|"missing";
export type RuntimeEntity={id:string;name:string;tier:RuntimeTier;reason:string};
export type RuntimeCategory={id:"classes"|"subclasses"|"feats"|"spells"|"items";label:string;total:number;automatic:number;assisted:number;manual:number;missing:number;score:number;entities:RuntimeEntity[]};
export type RuntimeCoverageCertification={score:number;status:"certified"|"needs-work";categories:RuntimeCategory[];priorities:string[]};
const CLASS_ENGINES=new Set(["barbarian","bard","cleric","druid","fighter","monk","paladin","ranger","rogue","sorcerer","warlock","wizard"]);
const FEAT_AUTOMATIC=[/alert/i,/mobile/i,/tough/i,/lucky/i,/observant/i,/defensive duelist/i,/inspiring leader/i,/shield master/i,/polearm master/i,/telekinetic/i,/sentinel/i,/mage slayer/i,/dual wielder/i,/war caster/i,/crossbow expert/i,/spell sniper/i,/great weapon master/i,/sharpshooter/i,/charger/i,/dungeon delver/i,/elemental adept/i,/keen mind/i,/martial adept/i,/medium armor master/i,/resilient/i,/ritual caster/i,/skulker/i,/weapon master/i,/fey.?touched/i,/piercer/i,/slasher/i,/skill expert/i];
const SUBCLASS_AUTOMATIC=/radiance of the dawn|invoke duplicity|improved warding flare|projected ward|branches of the tree|opportunist|entropic ward|shadow step|moonlight step|transposition|combat wild shape|circle forms|tides of chaos|elder champion|improved critical|superior critical|extra attack|draconic resilience|spell resistance|avatar of battle|thought shield|destructive wrath|guided strike|touch of death|arcane abjuration|path to the grave|twilight sanctuary|emboldening bond|order's demand|war priest|arcane ward|bend luck|wild magic surge/i;
const mechanicalItem=(item:DndItemData)=>Boolean(item.attackBonus||item.damageBonus||item.extraDamageDice||item.criticalExtraDamageDice||item.resistanceDamageType||item.preventsCriticalDamage||item.abilityMinimums||item.savingThrowBonus||item.skillCheckBonus||item.speedBonus||item.healingFormula||item.curesConditions?.length||item.clearsExhaustion||item.restoresHitDice||item.itemDamageFormula||item.armorBonus||item.grantedSpellName||item.charges||item.damage||item.armorClass||item.armorClassBonus||item.mastery);
export function classifyFeat(feat:DndFeatData):RuntimeEntity{if(FEAT_AUTOMATIC.some(pattern=>pattern.test(feat.name)))return{id:feat.id,name:feat.name,tier:"automatic",reason:"Play Mode hesap veya action motoruna bağlı."};if(feat.choiceType||feat.abilityOptions?.length)return{id:feat.id,name:feat.name,tier:"assisted",reason:"Seçim ve prerequisite doğrulanıyor; özel sonuç rehberli."};return{id:feat.id,name:feat.name,tier:feat.benefits.length?"manual":"missing",reason:feat.benefits.length?"Kural özeti mevcut; oyuncu/DM uygular.":"Runtime ve açıklama bulunamadı."}}
export function classifySpell(spell:DndSpellData):RuntimeEntity{const resolved=spell.effectType==="damage"||spell.effectType==="healing";if(resolved&&(spell.damageDice||spell.healingDice||spell.attackType))return{id:spell.id,name:spell.name,tier:"automatic",reason:"Global spell runtime roll, save, upcast, target ve effect çözümüne bağlı."};if(spell.effectType||spell.area||spell.target||spell.concentration||spell.ritual||spell.scaling||spell.tags?.length||spell.conditionEffect||spell.reactionTrigger)return{id:spell.id,name:spell.name,tier:"assisted",reason:"Global spell runtime davranış planı ve masa yönlendirmesi mevcut."};return{id:spell.id,name:spell.name,tier:spell.description.trim()?"manual":"missing",reason:spell.description.trim()?"Açıklama üzerinden oyuncu/DM çözümü.":"Davranış verisi bulunamadı."}}
export function classifyItem(item:DndItemData):RuntimeEntity{if(mechanicalItem(item))return{id:item.id,name:item.name,tier:"automatic",reason:"Inventory/attack/effect motoruna bağlı."};if(["weapon","armor","shield","ammunition","pack"].includes(item.category)||item.tags?.length)return{id:item.id,name:item.name,tier:"assisted",reason:"Equip, miktar veya kategori davranışı otomatik; özel etki rehberli."};return{id:item.id,name:item.name,tier:item.description.trim()?"manual":"missing",reason:item.description.trim()?"Eşya açıklaması manuel uygulanır.":"Eşya davranışı bulunamadı."}}
export function classifySubclass(subclass:DndSubclassData):RuntimeEntity{const features=subclass.features??[];if(features.some(feature=>SUBCLASS_AUTOMATIC.test(feature.name)))return{id:subclass.id,name:subclass.name,tier:"automatic",reason:"En az bir benzersiz feature Play Mode runtime'a bağlı."};if(features.length)return{id:subclass.id,name:subclass.name,tier:"assisted",reason:"Level progression ve feature notları otomatik açılıyor."};return{id:subclass.id,name:subclass.name,tier:"missing",reason:"Subclass feature progression bulunamadı."}}
const category=(id:RuntimeCategory["id"],label:string,entities:RuntimeEntity[]):RuntimeCategory=>{const count=(tier:RuntimeTier)=>entities.filter(item=>item.tier===tier).length;const automatic=count("automatic"),assisted=count("assisted"),manual=count("manual"),missing=count("missing"),total=entities.length;const score=total?Math.round((automatic+assisted*.65+manual*.25)/total*100):0;return{id,label,total,automatic,assisted,manual,missing,score,entities}};
export function getRuntimeCoverageCertification(data:RulesetData|null):RuntimeCoverageCertification{if(!data)return{score:0,status:"needs-work",categories:[],priorities:["Ruleset verisi yüklenemedi."]};const categories:RuntimeCategory[]=[category("classes","Class engines",data.classes.map(item=>({id:item.id,name:item.name,tier:CLASS_ENGINES.has(item.name.toLowerCase())?"automatic":"missing",reason:CLASS_ENGINES.has(item.name.toLowerCase())?"Dedicated class runtime ve progression motoru mevcut.":"Dedicated class runtime bulunamadı."}))),category("subclasses","Subclass features",data.subclasses.map(classifySubclass)),category("feats","Feat behavior",data.feats.map(classifyFeat)),category("spells","Spell behavior",data.spells.map(classifySpell)),category("items","Item behavior",data.items.map(classifyItem))];const total=categories.reduce((sum,item)=>sum+item.total,0);const score=total?Math.round(categories.reduce((sum,item)=>sum+item.score*item.total,0)/total):0;const priorities=categories.flatMap(group=>group.entities.filter(item=>item.tier==="missing"||item.tier==="manual").map(item=>`${group.label} · ${item.name}: ${item.reason}`)).slice(0,30);return{score,status:categories.every(item=>item.missing===0)&&score>=65?"certified":"needs-work",categories,priorities}}
