import type { DndSpellData } from "./ruleset.types";

type Edition = "dnd_2014" | "dnd_2024";
type Seed = [string, number, string, DndSpellData["effectType"], string[], string, Partial<DndSpellData>?];
const seeds: Seed[] = [
  ["Blade Ward",0,"Abjuration","defense",["Bard","Sorcerer","Warlock","Wizard"],"Kısa süreli büyülü koruma sağlayarak gelen saldırılara karşı savunmayı güçlendirir.",{castingTime:"1 action",duration:"1 round"}],
  ["Dancing Lights",0,"Evocation","utility",["Bard","Sorcerer","Wizard"],"Kontrol edilebilen küçük ışık kaynakları oluşturur.",{concentration:true,duration:"Up to 1 minute"}],
  ["Eldritch Blast",0,"Evocation","damage",["Warlock"],"Uzak bir hedefe force enerjisi taşıyan spell attack gönderir.",{attackType:"spell-attack",damageDice:"1d10",damageType:"force",scaling:{mode:"character-level",dicePerStep:"1d10"}}],
  ["Friends",0,"Enchantment","utility",["Bard","Sorcerer","Warlock","Wizard"],"Kısa süre boyunca sosyal etkileşimde seçilen hedefe karşı avantaj sağlar.",{concentration:true,duration:"Up to 1 minute"}],
  ["Message",0,"Transmutation","utility",["Bard","Sorcerer","Wizard"],"Yakındaki bir hedefe yalnızca onun duyabileceği kısa bir mesaj iletir.",{duration:"1 round"}],
  ["True Strike",0,"Divination","utility",["Bard","Sorcerer","Warlock","Wizard"],"Büyülü öngörüyle takip eden saldırının isabet potansiyelini destekler.",{}],
  ["Vicious Mockery",0,"Enchantment","damage",["Bard"],"Hedefe psychic hasar verir ve sonraki saldırısını zayıflatır.",{saveAbility:"wis",damageDice:"1d4",damageType:"psychic",scaling:{mode:"character-level",dicePerStep:"1d4"}}],
  ["Banishment",4,"Abjuration","control",["Cleric","Paladin","Sorcerer","Warlock","Wizard"],"Bir hedefi geçici olarak başka bir düzleme uzaklaştırır.",{concentration:true,saveAbility:"cha",conditionEffect:"Banished",target:"One creature"}],
  ["Death Ward",4,"Abjuration","defense",["Cleric","Paladin"],"Hedefi ölümcül bir darbeye veya ani ölüm etkisine karşı bir kez korur.",{duration:"8 hours"}],
  ["Freedom of Movement",4,"Abjuration","movement",["Cleric","Druid","Ranger"],"Hedefin büyülü hareket engellerini aşmasını kolaylaştırır.",{duration:"1 hour"}],
  ["Guardian of Faith",4,"Conjuration","summoning",["Cleric"],"Belirlenen alanı koruyan sabit bir kutsal muhafız oluşturur.",{damageType:"radiant",saveAbility:"dex",area:"10-foot radius"}],
  ["Commune",5,"Divination","utility",["Cleric"],"İlahi bir kaynaktan sınırlı sayıda kısa yanıt almaya çalışırsın.",{ritual:true}],
  ["Dispel Evil and Good",5,"Abjuration","defense",["Cleric","Paladin"],"Düzlemsel yaratıklara karşı koruma ve etki sonlandırma seçenekleri sağlar.",{concentration:true,duration:"Up to 1 minute"}],
  ["Flame Strike",5,"Evocation","damage",["Cleric"],"Dikey bir kutsal ateş sütunu alandaki hedeflere fire ve radiant hasar verir.",{damageDice:"8d6",damageType:"fire/radiant",saveAbility:"dex",area:"10-foot radius, 40-foot-high cylinder",scaling:{mode:"slot",dicePerStep:"1d6"}}],
  ["Hallow",5,"Evocation","utility",["Cleric"],"Geniş bir alanı uzun süreli kutsal veya yasaklı bölgeye dönüştürür.",{castingTime:"24 hours",duration:"Until dispelled",materialCost:"1,000 gp",materialConsumed:true,area:"60-foot radius"}],
  ["Raise Dead",5,"Necromancy","healing",["Bard","Cleric","Paladin"],"Kısa süre önce ölen bir yaratığı bedensel eksikleri yoksa hayata döndürür.",{castingTime:"1 hour",materialCost:"500 gp",materialConsumed:true}],
  ["Blade Barrier",6,"Evocation","damage",["Cleric"],"Dönen bıçaklardan oluşan tehlikeli ve görüşü zorlaştıran bir duvar kurar.",{concentration:true,damageDice:"6d10",damageType:"slashing",saveAbility:"dex",area:"Wall",duration:"Up to 10 minutes"}],
  ["Create Undead",6,"Necromancy","summoning",["Cleric","Warlock","Wizard"],"Cesetlerden sınırlı süre kontrol edilebilen undead hizmetkârlar oluşturur.",{castingTime:"1 minute",duration:"24 hours",materialCost:"150 gp"}],
  ["Find the Path",6,"Divination","utility",["Bard","Cleric","Druid"],"Aynı düzlemde bilinen sabit bir konuma giden en doğrudan rotayı gösterir.",{concentration:true,duration:"Up to 1 day",materialCost:"100 gp"}],
  ["Forbiddance",6,"Abjuration","defense",["Cleric"],"Büyük bir alanı planar travel ve seçilen yaratık türlerine karşı korur.",{ritual:true,castingTime:"10 minutes",duration:"24 hours",area:"40,000 square feet",materialCost:"1,000 gp"}],
  ["Harm",6,"Necromancy","damage",["Cleric"],"Tek bir hedefin yaşam gücünü ağır necrotic hasarla azaltır.",{damageDice:"14d6",damageType:"necrotic",saveAbility:"con",target:"One creature"}],
  ["Heal",6,"Abjuration","healing",["Cleric","Druid"],"Tek hedefe yüksek miktarda sabit healing verir ve bazı durumları kaldırır.",{healingDice:"70",target:"One creature",scaling:{mode:"slot",flatPerStep:10}}],
  ["Heroes' Feast",6,"Conjuration","defense",["Cleric","Druid"],"Partinin uzun süreli savunma ve dayanıklılığını artıran büyülü bir ziyafet oluşturur.",{castingTime:"10 minutes",duration:"24 hours",materialCost:"1,000 gp",materialConsumed:true}],
  ["Conjure Celestial",7,"Conjuration","summoning",["Cleric"],"Sınırlı challenge seviyesinde celestial bir müttefik çağırır.",{concentration:true,duration:"Up to 1 hour",castingTime:"1 minute"}],
  ["Divine Word",7,"Evocation","control",["Cleric"],"Düşük HP'li düşmanlara giderek ağırlaşan ilahi etkiler uygular.",{castingTime:"1 bonus action",saveAbility:"cha",area:"30-foot radius",conditionEffect:"Deafened/Stunned"}],
  ["Etherealness",7,"Transmutation","movement",["Bard","Cleric","Sorcerer","Warlock","Wizard"],"Kullanıcıyı Ethereal Plane sınırına geçirerek maddi engelleri aşmasını sağlar.",{duration:"Up to 8 hours",scaling:{mode:"slot",additionalTargetsPerStep:2}}],
  ["Fire Storm",7,"Evocation","damage",["Cleric","Druid","Sorcerer"],"Birden fazla bitişik alanda şekillendirilebilen büyük bir ateş fırtınası oluşturur.",{damageDice:"7d10",damageType:"fire",saveAbility:"dex",area:"Ten 10-foot cubes"}],
  ["Plane Shift",7,"Conjuration","movement",["Cleric","Druid","Sorcerer","Warlock","Wizard"],"Bir grubu başka bir düzleme taşır veya tek hedefi planar olarak sürgün etmeye çalışır.",{materialCost:"250 gp",saveAbility:"cha",target:"Up to eight creatures"}],
  ["Regenerate",7,"Transmutation","healing",["Bard","Cleric","Druid"],"Hedefe süre boyunca yenilenme verir ve kayıp uzuvların geri gelmesini sağlar.",{healingDice:"4d8+15",duration:"1 hour"}],
  ["Resurrection",7,"Necromancy","healing",["Bard","Cleric"],"Uzun süre önce ölmüş bir yaratığı uygun bedeni varsa hayata döndürür.",{castingTime:"1 hour",materialCost:"1,000 gp",materialConsumed:true}],
  ["Symbol",7,"Abjuration","control",["Bard","Cleric","Wizard"],"Tetiklendiğinde seçilen güçlü büyülü etkiyi yayan kalıcı bir glyph oluşturur.",{castingTime:"1 minute",duration:"Until dispelled",materialCost:"1,000 gp",materialConsumed:true,area:"60-foot radius"}],
  ["Antimagic Field",8,"Abjuration","defense",["Cleric","Wizard"],"Yakındaki büyüleri ve magic item etkilerini geçici olarak baskılayan alan oluşturur.",{concentration:true,duration:"Up to 1 hour",area:"10-foot-radius sphere"}],
  ["Control Weather",8,"Transmutation","utility",["Cleric","Druid","Wizard"],"Geniş bölgenin hava koşullarını kademeli biçimde değiştirir.",{concentration:true,castingTime:"10 minutes",duration:"Up to 8 hours",area:"5-mile radius"}],
  ["Earthquake",8,"Transmutation","damage",["Cleric","Druid","Sorcerer"],"Geniş alanda zemin, yapılar ve concentration üzerinde yıkıcı sarsıntı oluşturur.",{concentration:true,saveAbility:"dex",area:"100-foot radius",duration:"Up to 1 minute"}],
  ["Holy Aura",8,"Abjuration","defense",["Cleric"],"Yakındaki müttefikleri saldırılara ve bazı extraplanar etkilere karşı güçlendirir.",{concentration:true,duration:"Up to 1 minute",area:"30-foot radius",materialCost:"1,000 gp"}],
  ["Astral Projection",9,"Necromancy","movement",["Cleric","Warlock","Wizard"],"Grubun astral bedenlerini Astral Plane'e gönderir.",{castingTime:"1 hour",duration:"Special",materialCost:"1,100 gp",materialConsumed:true,target:"Up to nine creatures"}],
  ["Gate",9,"Conjuration","movement",["Cleric","Sorcerer","Wizard"],"Başka bir düzleme geçit açar veya bilinen bir varlığı geçide çağırır.",{concentration:true,duration:"Up to 1 minute",materialCost:"5,000 gp"}],
  ["Mass Heal",9,"Abjuration","healing",["Cleric"],"Görüş alanındaki hedefler arasında çok büyük bir healing havuzu paylaştırır.",{healingDice:"700",target:"Multiple creatures"}],
  ["True Resurrection",9,"Necromancy","healing",["Cleric","Druid"],"Çok uzun süre önce ölen bir yaratığı yeni beden oluşturarak hayata döndürebilir.",{castingTime:"1 hour",materialCost:"25,000 gp",materialConsumed:true}],
  ["Arcane Eye",4,"Divination","utility",["Wizard"],"Uzakta hareket ettirilebilen görünmez bir göz oluşturur.",{concentration:true,duration:"Up to 1 hour"}],
  ["Charm Person",1,"Enchantment","control",["Bard","Druid","Sorcerer","Warlock","Wizard"],"Bir humanoid hedefi geçici olarak dostça davranmaya zorlar.",{saveAbility:"wis",duration:"1 hour"}],
  ["Commune with Nature",5,"Divination","utility",["Druid","Ranger"],"Çevredeki arazi ve canlılar hakkında doğadan bilgi alır.",{ritual:true}],
  ["Confusion",4,"Enchantment","control",["Bard","Druid","Sorcerer","Wizard"],"Bir alandaki yaratıkların davranışlarını düzensizleştirir.",{concentration:true,saveAbility:"wis",area:"10-foot radius"}],
  ["Crusader's Mantle",3,"Evocation","damage",["Paladin"],"Yakındaki müttefiklerin silah saldırılarına radiant hasar ekler.",{concentration:true,area:"30-foot radius"}],
  ["Daylight",3,"Evocation","utility",["Cleric","Druid","Paladin","Ranger","Sorcerer"],"Geniş bir alanı parlak ışıkla doldurur.",{duration:"1 hour",area:"60-foot radius"}],
  ["Disguise Self",1,"Illusion","utility",["Bard","Sorcerer","Wizard"],"Görünüşünü kısa süreliğine illüzyonla değiştirir.",{duration:"1 hour"}],
  ["Divine Favor",1,"Evocation","damage",["Paladin"],"Silah saldırılarına geçici radiant hasar ekler.",{concentration:true,duration:"Up to 1 minute"}],
  ["Dominate Person",5,"Enchantment","control",["Bard","Sorcerer","Wizard"],"Bir humanoid hedef üzerinde güçlü zihinsel kontrol kurar.",{concentration:true,saveAbility:"wis",duration:"Up to 1 minute"}],
  ["Ensnaring Strike",1,"Conjuration","control",["Ranger"],"İsabet eden saldırının hedefini büyülü sarmaşıklarla bağlar.",{concentration:true,saveAbility:"str",conditionEffect:"Restrained"}],
  ["Hold Monster",5,"Enchantment","control",["Bard","Sorcerer","Warlock","Wizard"],"Bir yaratığı paralyzed durumda tutmaya çalışır.",{concentration:true,saveAbility:"wis",conditionEffect:"Paralyzed"}],
  ["Ice Storm",4,"Evocation","damage",["Druid","Sorcerer","Wizard"],"Buz ve dolu yağışıyla geniş bir alanı vurur.",{damageDice:"2d8+4d6",damageType:"bludgeoning/cold",saveAbility:"dex",area:"20-foot radius"}],
  ["Magic Weapon",2,"Transmutation","utility",["Paladin","Wizard"],"Bir silahı geçici olarak büyülü ve daha etkili hâle getirir.",{concentration:true,duration:"Up to 1 hour"}],
  ["Modify Memory",5,"Enchantment","control",["Bard","Wizard"],"Bir hedefin yakın geçmişteki anılarını değiştirmeye çalışır.",{concentration:true,saveAbility:"wis"}],
  ["Moonbeam",2,"Evocation","damage",["Druid"],"Hareket ettirilebilen ay ışığı sütunu radiant hasar verir.",{concentration:true,damageDice:"2d10",damageType:"radiant",saveAbility:"con",area:"5-foot radius"}],
  ["Nondetection",3,"Abjuration","defense",["Bard","Ranger","Wizard"],"Hedefi divination büyülerinden gizler.",{duration:"8 hours",materialCost:"25 gp"}],
  ["Pass without Trace",2,"Abjuration","utility",["Druid","Ranger"],"Yakındaki grubun gizlilik hareketlerini güçlendirir.",{concentration:true,area:"30-foot radius"}],
  ["Plant Growth",3,"Transmutation","control",["Bard","Druid","Ranger"],"Bitkileri hızla büyüterek alanı zor araziye dönüştürür.",{area:"100-foot radius"}],
  ["Protection from Energy",3,"Abjuration","defense",["Cleric","Druid","Ranger","Sorcerer","Wizard"],"Hedefe seçilen enerji hasarı türüne resistance verir.",{concentration:true,duration:"Up to 1 hour"}],
  ["Protection from Evil and Good",1,"Abjuration","defense",["Cleric","Paladin","Warlock","Wizard"],"Hedefi belirli extraplanar yaratıklara karşı korur.",{concentration:true,duration:"Up to 10 minutes"}],
  ["Sanctuary",1,"Abjuration","defense",["Cleric"],"Saldıranların hedefe yönelmeden önce irade save'i yapmasını gerektirir.",{castingTime:"1 bonus action",saveAbility:"wis"}],
  ["Scrying",5,"Divination","utility",["Bard","Cleric","Druid","Warlock","Wizard"],"Aynı düzlemdeki bilinen bir hedefi uzaktan gözlemlemeye çalışır.",{concentration:true,saveAbility:"wis",duration:"Up to 10 minutes"}],
  ["See Invisibility",2,"Divination","utility",["Bard","Sorcerer","Wizard"],"Görünmez yaratıkları ve Ethereal varlıkları görmeyi sağlar.",{duration:"1 hour"}],
  ["Shield of Faith",1,"Abjuration","defense",["Cleric","Paladin"],"Bir hedefin Armor Class değerini geçici olarak yükseltir.",{castingTime:"1 bonus action",concentration:true,duration:"Up to 10 minutes"}],
  ["Speak with Animals",1,"Divination","utility",["Bard","Druid","Ranger"],"Hayvanlarla iletişim kurmayı sağlar.",{ritual:true,duration:"10 minutes"}],
  ["Stoneskin",4,"Transmutation","defense",["Druid","Ranger","Sorcerer","Wizard"],"Hedefe fiziksel silah hasarına karşı direnç kazandırır.",{concentration:true,duration:"Up to 1 hour",materialCost:"100 gp"}],
  ["Tree Stride",5,"Conjuration","movement",["Druid","Ranger"],"Ağaçlar arasında kısa mesafeli geçişler sağlar.",{concentration:true,duration:"Up to 1 minute"}],
  ["Wall of Fire",4,"Evocation","damage",["Druid","Sorcerer","Wizard"],"Temas eden veya yakındaki hedeflere fire hasarı veren bir duvar oluşturur.",{concentration:true,damageDice:"5d8",damageType:"fire",saveAbility:"dex",area:"Wall"}],
  ["Zone of Truth",2,"Enchantment","control",["Bard","Cleric","Paladin"],"Bir alandaki yaratıkların bilerek yalan söylemesini zorlaştırır.",{saveAbility:"cha",area:"15-foot radius",duration:"10 minutes"}],
];

function build(seed:Seed, ruleset:Edition):DndSpellData {
  const [name,level,school,effectType,classes,description,extra={}] = seed;
  return { id:`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}${ruleset === "dnd_2024" ? "-2024" : ""}`, name, level, school,
    castingTime:"1 action", range:"60 feet", components:["V","S"], duration:"Instantaneous", concentration:false, ritual:false,
    classes, description, effectType, source: ruleset === "dnd_2024" ? "2024 expansion" : "2014 expansion", ...extra };
}
export const SPELL_EXPANSION_2014 = seeds.map((seed)=>build(seed,"dnd_2014"));
export const SPELL_EXPANSION_2024 = seeds.map((seed)=>build(seed,"dnd_2024"));
