import type{Character}from"../../core/character/character.types";import type{RulesetData}from"../../core/rulesets/ruleset.types";import{getCharacterChoiceDebt}from"../../core/rulesets/choiceDebt";import{getFightingStyles,getFightingStyleChoiceCount}from"../../core/rulesets/fightingStyleRules";import{getWeaponMastery,getWeaponMasteryChoiceCount}from"../../core/rulesets/equipmentRules";import{getMetamagicChoiceCount,getMetamagicOptions}from"../../core/rulesets/metamagicRules";import{getEldritchInvocations,getInvocationChoiceCount,isInvocationEligible}from"../../core/rulesets/invocationRules";import{getWildShapeForms,getWildShapeKnownCount,isWildShapeFormEligible}from"../../core/rulesets/wildShapeRules";import{getBattleMasterManeuvers,getManeuverChoiceCount}from"../../core/rulesets/maneuverRules";import{getRangerCompanions}from"../../core/rulesets/companionRules";import{getMysticArcanumLevels}from"../../core/rulesets/pactMagicRules";
type ArrayField="fightingStyleIds"|"masteredWeaponIds"|"metamagicIds"|"invocationIds"|"wildShapeFormIds"|"maneuverIds";
export function ChoiceDebtResolver({character,rulesetData,onUpdateCharacter}:{character:Character;rulesetData:RulesetData|null;onUpdateCharacter:(character:Character)=>void}){const debts=getCharacterChoiceDebt(character,rulesetData);const classData=rulesetData?.classes.find(x=>x.name===character.className);const commit=(patch:Partial<Character>)=>onUpdateCharacter({...character,...patch,updatedAt:new Date().toISOString()});const toggle=(field:ArrayField,id:string,limit:number)=>{const selected=(character[field]??[]) as string[];commit({[field]:selected.includes(id)?selected.filter(x=>x!==id):selected.length<limit?[...selected,id]:selected} as Partial<Character>)};
 const configs:Partial<Record<string,{field:ArrayField;limit:number;options:{id:string;name:string;detail?:string}[]}>>={
  "fighting-styles":{field:"fightingStyleIds",limit:getFightingStyleChoiceCount(character.className,character.level,character.subclass),options:getFightingStyles(character.ruleset)},
  "weapon-mastery":{field:"masteredWeaponIds",limit:getWeaponMasteryChoiceCount(classData,character.level,character.ruleset),options:(rulesetData?.items??[]).filter(x=>getWeaponMastery(x,character.ruleset)).map(x=>({id:x.id,name:x.name,detail:getWeaponMastery(x,character.ruleset)??""}))},
  metamagic:{field:"metamagicIds",limit:getMetamagicChoiceCount(character.className,character.level,character.ruleset),options:getMetamagicOptions(character.ruleset).map(x=>({id:x.id,name:x.name,detail:`${x.cost} SP`}))},
  invocations:{field:"invocationIds",limit:getInvocationChoiceCount(character.className,character.level,character.ruleset),options:getEldritchInvocations(character.ruleset).filter(x=>isInvocationEligible(x,character)).map(x=>({id:x.id,name:x.name,detail:x.summary}))},
  "wild-shape":{field:"wildShapeFormIds",limit:getWildShapeKnownCount(character.className,character.level,character.ruleset),options:getWildShapeForms().filter(x=>isWildShapeFormEligible(x,character.level,character.ruleset,character.subclass)).map(x=>({id:x.id,name:x.name,detail:`CR ${x.challengeRating}`}))},
  maneuvers:{field:"maneuverIds",limit:getManeuverChoiceCount(character.className,character.subclass,character.level,character.ruleset),options:getBattleMasterManeuvers().map(x=>({id:x.id,name:x.name,detail:x.trigger}))},
 };
 if(!debts.length)return <div className="empty-panel">Zorunlu seçim borcu yok.</div>;
 return <div className="level-up-panel">{debts.map(debt=>{if(debt.id==="subclass")return <section className="level-up-section" key={debt.id}><h3>Subclass seç</h3><div className="level-up-choice-grid">{(rulesetData?.subclasses??[]).filter(x=>x.className===character.className).map(x=><button type="button" key={x.id} onClick={()=>commit({subclass:x.name})}>{x.name}</button>)}</div></section>;if(debt.id==="companion")return <section className="level-up-section" key={debt.id}><h3>Companion seç</h3><div className="level-up-choice-grid">{getRangerCompanions(character.ruleset).map(x=><button type="button" key={x.id} onClick={()=>commit({companionId:x.id})}>{x.name}</button>)}</div></section>;if(debt.id==="arcanum"){const levels=getMysticArcanumLevels(character.className,character.level,character.ruleset);return <section className="level-up-section" key={debt.id}><h3>Mystic Arcanum seç</h3>{levels.map(level=><label key={level}>Level {level}<select value={(character.arcanumSpellIds??[]).find(id=>rulesetData?.spells.find(x=>x.id===id)?.level===level)??""} onChange={event=>{const same=new Set((rulesetData?.spells??[]).filter(x=>x.level===level).map(x=>x.id));commit({arcanumSpellIds:[...(character.arcanumSpellIds??[]).filter(id=>!same.has(id)),event.target.value].filter(Boolean)})}}><option value="">Seç...</option>{(rulesetData?.spells??[]).filter(x=>x.level===level&&x.classes.some(c=>c.toLowerCase()==="warlock")).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}</section>}const config=configs[debt.id];if(!config)return null;const selected=(character[config.field]??[]) as string[];return <section className="level-up-section" key={debt.id}><div className="panel-heading-row"><h3>{debt.label}</h3><span>{selected.length}/{config.limit}</span></div><div className="level-up-choice-grid">{config.options.map(option=><button type="button" className={selected.includes(option.id)?"active":""} key={option.id} onClick={()=>toggle(config.field,option.id,config.limit)}>{option.name}{option.detail?<small>{option.detail}</small>:null}</button>)}</div></section>})}</div>}
