const ENGLISH_UI_TEXT: Record<string,string>={
  "Karakterler":"Characters","Karakter Oluştur":"Create Character","Yeni Karakter":"New Character","Karakteri Düzenle":"Edit Character","Karakteri aç →":"Open character →","Listeye Dön":"Back to list","Düzenle":"Edit","Sil":"Delete","Kaydet":"Save","İptal":"Cancel","Kaldır":"Remove","Seç":"Select","Kilitli":"Locked","Ekle":"Add","Temizle":"Clear","Sıfırla":"Reset","Şimdi aç":"Open now","Geri":"Back","İleri":"Next","Ara":"Search","Tümü":"All","Hazır":"Ready","Kullanıldı":"Used","Kullan":"Use","Detay":"Details","Açıklama":"Description","Notlar":"Notes","Adet":"Quantity","Durum":"Status","Tür":"Type","Kaynak":"Source","Seviye":"Level","İsim":"Name","Oyuncu adı":"Player name","Kurallar":"Rules","Özellikler":"Features","Yetenekler":"Abilities","Büyüler":"Spells","Eşyalar":"Items","Silahlar":"Weapons","Zırhlar":"Armor","Araçlar":"Tools","Diller":"Languages","Altın":"Gold","Hasar":"Damage","İyileştirme":"Healing","Hareket":"Movement","Menzil":"Range","Süre":"Duration","Bileşenler":"Components","Yoğunlaşma":"Concentration","Ritüel":"Ritual","Aksiyon":"Action","Tepki":"Reaction","Bonus Aksiyon":"Bonus Action",
  "Karakter yönetimi":"Character management","Karakter Detayı":"Character Detail","Karakter karşılaştırma":"Character comparison","Level Up Assistant":"Level Up Assistant","Seviye artırma, HP ve ASI işlemleri":"Level progression, HP, and ASI operations","Temel bilgiler":"Basic information","Class seçimi":"Class selection","Ability skorları":"Ability scores","Skill seçimleri":"Skill choices","Savaş seçenekleri":"Combat choices","Ekipman seçimi":"Equipment selection","Büyü seçimi":"Spell selection","Son kontrol":"Final review","İlk karakterini oluştur":"Create your first character","Karakter Bulunamadı":"Character Not Found","Karakterlere Dön":"Back to Characters","Play Mode'u Aç":"Open Play Mode","Zar At":"Roll Dice",
  "Ayarlar":"Settings","Uygulama tercihleri":"Application preferences","Görünüm":"Appearance","Arayüz tarzı":"Interface style","Canlı uygulanır":"Applied live","Vurgu rengi":"Accent color","Bilgi yoğunluğu":"Information density","Yazı boyutu":"Font size","Hareketler":"Motion","Başlangıç":"Startup","Açılış davranışı":"Startup behavior","Karakter kuralları":"Character rules","Varsayılan ruleset":"Default ruleset","DM varsayılanları":"DM defaults","Yeni campaign araç profili":"New campaign tool profile","Sıfırlama":"Reset","Tercihleri varsayılana döndür":"Restore default preferences","Ayarları sıfırla":"Reset settings",
  "Mor":"Violet","Mavi":"Blue","Zümrüt":"Emerald","Kehribar":"Amber","Rahat":"Comfortable","Kompakt":"Compact","Küçük":"Small","Büyük":"Large","Sisteme uy":"Follow system","Tam":"Full","Azaltılmış":"Reduced","Sade":"Simple","Dengeli":"Balanced",
  "Spellbook":"Spellbook","Büyü Kütüphanesi":"Spell Library","Inventory":"Inventory","Ekipman Kütüphanesi":"Equipment Library","Class Kataloğu":"Class Catalog","Subclass Kataloğu":"Subclass Catalog","Feat Kataloğu":"Feat Catalog","Ruleset Center":"Ruleset Center","Yardım Merkezi":"Help Center","Yedek & Kurtarma":"Backup & Recovery","Sürüm Geçmişi":"Release History","Global Arama":"Global Search","Koleksiyonlar":"Collections","Favoriler":"Favorites","Son açılanlar":"Recently opened","Hızlı araçlar":"Quick tools","Hızlı erişim":"Quick access","Tam yedek al →":"Create full backup →",
  "Büyü ara":"Search spells","Class ara":"Search classes","Subclass veya feature ara...":"Search subclasses or features...","Race, species, trait, background veya feat ara...":"Search race, species, traits, backgrounds, or feats...","İsim, class, race, background...":"Name, class, race, background...","Longsword, armor, potion...":"Longsword, armor, potion...","Tüm classlar":"All classes","Tüm leveller":"All levels","Tüm kategoriler":"All categories","Hazırlananlar":"Prepared","Bilinenler":"Known","Kuşanılmış":"Equipped","Sadece favoriler":"Favorites only",
  "Karakter masaya hazır":"Character ready for the table","Eksikleri düzelt":"Fix issues","Doğrulama Raporu":"Validation Report","Tamamlanmalı":"Must be completed","İsteğe bağlı":"Optional","Oynamaya hazır":"Ready to play","Zorunlu kontroller tamam":"Required checks complete","Kaydetmeden önce düzeltme gerekli":"Fix required before saving","İlk hataya git":"Go to first error","Karakteri kaydet":"Save character","Karakter kurallı biçimde kaydedilmeye hazır.":"The character is ready to be saved with valid rules.",
  "Yükleniyor...":"Loading...","Veri hazır":"Data ready","Manuel içerik":"Manual content","Altyapı hazır":"Foundation ready","Kontrol gereken bloklar var":"Some blocks require review","Oynanış matrisi sertifikalı":"Play matrix certified","Blocker raporu":"Blocker report","12 Class Matrisi":"12 Class Matrix","Ruleset verisi yüklenemedi.":"Ruleset data could not be loaded.",
  "Veri yedekleme":"Data backup","Tam yedek":"Full backup","Yedeği indir":"Download backup","Yedeği içe aktar":"Import backup","Birleştir":"Merge","Üzerine yaz":"Replace","Verileri koru":"Protect your data","Kurtarma Merkezi":"Recovery Center","Dosya seç":"Choose file","Yardım ve güvenlik":"Help and safety","Sık sorulan sorular":"Frequently asked questions","Başlangıç rehberi":"Getting started","Sorun giderme":"Troubleshooting",
  "Henüz kayıt yok":"No records yet","Henüz karakter yok":"No characters yet","Henüz campaign yok":"No campaigns yet","Campaign oluştur":"Create campaign","Campaign'i aç →":"Open campaign →","Builder'a git →":"Go to Builder →","Ruleset Library":"Ruleset Library","Yerel sistem":"Local system","Çevrimdışı":"Offline","Güncelleme":"Update","Yeniden başlat":"Restart","Ana sayfada yeniden başlat":"Restart on home page","Acil veri kopyasını indir":"Download emergency data copy"
};

const PATTERNS:Array<[RegExp,(match:RegExpMatchArray)=>string]>=[
  [/^(\d+) hata · (\d+) uyarı$/,(m)=>`${m[1]} errors · ${m[2]} warnings`],
  [/^(\d+) zorunlu seçim eksik$/,(m)=>`${m[1]} required choices missing`],
  [/^(\d+) içerik hazır$/,(m)=>`${m[1]} entries ready`],
  [/^Seviye (\d+)$/,(m)=>`Level ${m[1]}`],
  [/^(\d+)% hazır$/,(m)=>`${m[1]}% ready`],
  [/^(\d+) aktif encounter$/,(m)=>`${m[1]} active encounters`],
  [/^(\d+) karakter$/,(m)=>`${m[1]} characters`],
  [/^(\d+) condition$/,(m)=>`${m[1]} conditions`]
  ,[/^Hata · (.+)$/,(m)=>`Error · ${m[1]}`],[/^Uyarı · (.+)$/,(m)=>`Warning · ${m[1]}`],[/^Düzelt →$/,()=>"Fix →"]
];

export function translateUiText(locale:"tr"|"en",value:string){
  if(locale==="tr")return value;
  const leading=value.match(/^\s*/)?.[0]??"";const trailing=value.match(/\s*$/)?.[0]??"";const clean=value.trim();
  const exact=ENGLISH_UI_TEXT[clean];if(exact)return`${leading}${exact}${trailing}`;
  for(const[pattern,render]of PATTERNS){const match=clean.match(pattern);if(match)return`${leading}${render(match)}${trailing}`}
  return value;
}

export function getUiCatalogCoverage(values:string[]){const unique=[...new Set(values.map(value=>value.trim()).filter(Boolean))];const translated=unique.filter(value=>translateUiText("en",value)!==value);return{total:unique.length,translated:translated.length,missing:unique.filter(value=>!translated.includes(value))}}
