import {describe,expect,it} from "vitest";
import {makeCharacter} from "../../test/fixtures";
import type {RulesetData} from "../rulesets/ruleset.types";
import {compareSheetAndPlayMode,getSheetPlayModeConsistencySnapshot,getWeaponConsistencyRows} from "./sheetPlayModeConsistency";
const data={classes:[{name:"Fighter",savingThrows:["str","con"]}],races:[{name:"Tiefling",speed:30,traits:["Hellish Resistance"]}],backgrounds:[],feats:[],spells:[],subclasses:[],monsters:[],items:[{id:"longbow",name:"Longbow",category:"weapon",cost:"",weight:2,description:"",damage:"1d8",damageType:"piercing",weaponCategory:"martial-ranged",range:"150/600"},{id:"rapier",name:"Rapier",category:"weapon",cost:"",weight:2,description:"",damage:"1d8",damageType:"piercing",weaponCategory:"martial-melee",properties:["Finesse"]},{id:"ring",name:"Ring",category:"wondrous",cost:"",weight:0,description:"",requiresAttunement:true,resistanceDamageType:"cold"}]} as unknown as RulesetData;
describe("sheet and play mode final consistency",()=>{
 it("uses the same ranged attack math including Archery",()=>{const c=makeCharacter({className:"Fighter",level:5,equippedWeaponIds:["longbow"],fightingStyleIds:["archery"],abilities:{str:12,dex:18,con:12,int:10,wis:10,cha:10}});expect(getWeaponConsistencyRows(c,data.items)[0]).toMatchObject({attackAbility:"dex",attackBonus:9,damageBonus:4})});
 it("uses finesse ability consistently",()=>{const c=makeCharacter({equippedWeaponIds:["rapier"],abilities:{str:10,dex:16,con:10,int:10,wis:10,cha:10}});expect(getWeaponConsistencyRows(c,data.items)[0]).toMatchObject({attackAbility:"dex",damageBonus:3})});
 it("combines ancestry and attuned item resistances",()=>{const c=makeCharacter({race:"Tiefling",inventory:[{itemId:"ring",quantity:1,attuned:true}]});expect(getSheetPlayModeConsistencySnapshot(c,data).damageResistances).toEqual(["cold","fire"])});
 it("keeps conditions effects slots and resources in one snapshot",()=>{const c=makeCharacter({conditions:["Blessed"],activeSpellEffects:[{id:"a",spellId:"bless",name:"Bless",remainingRounds:9,concentration:true,summary:""}],spellSlots:[{level:1,max:4,used:1}]});const x=getSheetPlayModeConsistencySnapshot(c,data);expect(x).toMatchObject({conditions:["Blessed"],concentration:{active:true,valid:true},spellSlots:[{level:1,max:4,used:1,remaining:3}]})});
 it("reports a divergent play snapshot",()=>{const c=makeCharacter();const sheet=getSheetPlayModeConsistencySnapshot(c,data);const play={...sheet,armorClass:sheet.armorClass+1};expect(compareSheetAndPlayMode(c,data,sheet,play)).toMatchObject({consistent:false,differences:["armorClass"]})});
 it("blocks multiple concentration effects",()=>{const c=makeCharacter({activeSpellEffects:[{id:"a",spellId:"a",name:"A",remainingRounds:1,concentration:true,summary:""},{id:"b",spellId:"b",name:"B",remainingRounds:1,concentration:true,summary:""}]});expect(compareSheetAndPlayMode(c,data)).toMatchObject({consistent:false,score:85})});
});
