import type { ReferenceCombatant, ReferenceInventoryEntry, ReferenceItem, ReferenceSpell } from "../reference/equipmentCombat.reference";
export const abilityModifier=(score:number)=>Math.floor((score-10)/2);
export function proficiencyBonus(level:number){const n=Math.max(1,Math.min(20,Math.floor(level)));return 2+Math.floor((n-1)/4)}
export function setInventoryQuantity(inventory:ReferenceInventoryEntry[],itemId:string,quantity:number){const q=Math.max(0,Math.floor(quantity));if(q<=0)return inventory.filter(e=>e.itemId!==itemId);return inventory.some(e=>e.itemId===itemId)?inventory.map(e=>e.itemId===itemId?{...e,quantity:q}:e):[...inventory,{itemId,quantity:q}]}
export function inventoryWeight(inventory:ReferenceInventoryEntry[],items:ReferenceItem[]){const m=new Map(items.map(i=>[i.id,i]));return inventory.reduce((t,e)=>t+(m.get(e.itemId)?.weight??0)*e.quantity,0)}
const props=(item:ReferenceItem)=>(item.properties??[]).map(x=>x.toLowerCase());
export function weaponAbilityModifier(c:ReferenceCombatant,w:ReferenceItem){const p=props(w),s=abilityModifier(c.abilities.str),d=abilityModifier(c.abilities.dex);if(p.includes("finesse"))return Math.max(s,d);const ranged=Boolean(w.range)||p.includes("ammunition")||p.includes("thrown");return ranged?d:s}
export function weaponAttackBonus(c:ReferenceCombatant,w:ReferenceItem,proficient=true){const p=props(w);const ranged=p.includes("ammunition")||w.id.includes("bow")||w.id.includes("crossbow");const archery=ranged&&c.fightingStyleIds.includes("archery")?2:0;return weaponAbilityModifier(c,w)+(proficient?proficiencyBonus(c.level):0)+archery+(w.attackBonus??0)}
export function weaponDamageSummary(c:ReferenceCombatant,w:ReferenceItem,useVersatile=false){const p=props(w);const two=p.includes("two-handed")||(useVersatile&&Boolean(w.versatileDamage));const dice=useVersatile&&w.versatileDamage?w.versatileDamage:(w.damage??"1");const duel=c.fightingStyleIds.includes("dueling")&&!w.range&&!two&&c.equippedWeaponIds.length===1?2:0;const thrown=c.fightingStyleIds.includes("thrown-weapon-fighting")&&p.includes("thrown")?2:0;const mod=weaponAbilityModifier(c,w)+duel+thrown+(w.damageBonus??0);return `${dice}${mod===0?"":` ${mod>0?`+${mod}`:mod}`} ${w.damageType??"damage"}`}
export function automaticArmorClass(c:ReferenceCombatant,items:ReferenceItem[]){const m=new Map(items.map(i=>[i.id,i]));const inv=new Set(c.inventory.filter(e=>e.quantity>0).map(e=>e.itemId));const dex=abilityModifier(c.abilities.dex);const armor=c.equippedArmorId&&inv.has(c.equippedArmorId)?m.get(c.equippedArmorId)??null:null;const shield=c.equippedShieldId&&inv.has(c.equippedShieldId)?m.get(c.equippedShieldId)??null:null;let ac=10+dex;if(armor?.category==="armor"){if(armor.armorType==="heavy")ac=armor.armorClass??10;else if(armor.armorType==="medium")ac=(armor.armorClass??10)+Math.min(dex,armor.dexBonusMax??2);else ac=(armor.armorClass??10)+dex}if(shield?.category==="shield")ac+=shield.armorClassBonus??2;if(c.fightingStyleIds.includes("defense")&&armor)ac+=1;return ac}
export const effectiveArmorClass=(c:ReferenceCombatant,items:ReferenceItem[])=>c.armorClassMode==="manual"?c.armorClass:automaticArmorClass(c,items);
export const weaponMastery=(item:ReferenceItem,rulesetId:string)=>rulesetId==="dnd_2024"&&item.category==="weapon"?(item.mastery??null):null;
export function combatReadiness(c:ReferenceCombatant,items:ReferenceItem[],spells:ReferenceSpell[],always:string[]=[]){const blockers:string[]=[],notices:string[]=[],primary:string[]=[];const inv=new Set(c.inventory.filter(e=>e.quantity>0).map(e=>e.itemId));const m=new Map(items.map(i=>[i.id,i]));const refs=[c.equippedArmorId,c.equippedShieldId,...c.equippedWeaponIds].filter((x):x is string=>Boolean(x));const missing=refs.filter(id=>!inv.has(id));if(missing.length)blockers.push(`Kuşanılmış ${missing.length} eşya envanterde bulunmuyor.`);for(const id of c.equippedWeaponIds.filter(id=>inv.has(id))){const i=m.get(id);if(i?.category==="weapon")primary.push(i.name)}for(const id of new Set([...c.knownSpellIds,...c.preparedSpellIds,...always])){const s=spells.find(x=>x.id===id);if(s&&(s.effectType==="damage"||s.attackType==="spell-attack"||Boolean(s.damageDice)))primary.push(s.name)}if(c.className==="Monk")primary.push("Martial Arts / Unarmed Strike");if(!primary.length)notices.push("Hazır bir silah veya saldırı büyüsü görünmüyor; ilk çatışma öncesi loadout kontrol edilmeli.");if(!Number.isFinite(c.armorClass)||c.armorClass<10)blockers.push("Armor Class geçerli bir savaş değeri değil.");if(!Number.isFinite(c.maxHp)||c.maxHp<=0)blockers.push("Max HP en az 1 olmalı.");if(!c.inventory.some(e=>e.quantity>0)&&c.gold<=0)notices.push("Ekipman ve altın bulunmuyor; karakter savaş dışı hazırlıkta da eksik kalabilir.");return{ready:blockers.length===0&&primary.length>0,blockers,notices,primaryOptions:[...new Set(primary)]}}
