
  export type ReleaseCategory = "Özellik" | "İyileştirme" | "Düzeltme" | "Teknik";

export type ReleaseChange = {
  text: string;
  category: ReleaseCategory;
};

export type ReleaseEntry = {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: ReleaseChange[];
};

export const RELEASE_NOTES: readonly ReleaseEntry[] = [
  {version:"5.14.0",date:"2026-07-17",title:"Homebrew Package Sharing, Dependency & Migration",summary:"Homebrew packages now support dependency-aware sharing manifests, compatibility gates and safe legacy migration.",changes:[{text:"Dependency-aware multi-package sharing manifest",category:"Özellik"},{text:"Semantic version range and install-order resolution",category:"Teknik"},{text:"Required, optional and circular dependency validation",category:"Düzeltme"},{text:"Legacy package and entity migration",category:"İyileştirme"},{text:"Compatibility gate and downgrade-safe merge",category:"Düzeltme"},{text:"Homebrew sharing and migration certification tests",category:"Teknik"}]},

  {version:"5.13.0",date:"2026-07-17",title:"Homebrew Spell, Item & Feat Runtime Integration",summary:"Selected Homebrew feats, spells and items now expose certified runtime behavior in Character Sheet and Play Mode.",changes:[{text:"Homebrew feat choice and passive runtime certification",category:"Özellik"},{text:"Homebrew spell damage, healing, save, concentration and reaction readiness",category:"Özellik"},{text:"Homebrew item attunement, charge and granted-spell runtime",category:"Özellik"},{text:"Ability bonus, self-effect and item-charge helpers",category:"Teknik"},{text:"Feat, spell and item runtime blocker reporting",category:"İyileştirme"},{text:"Homebrew content runtime integration tests",category:"Teknik"}]},

  {version:"5.12.0",date:"2026-07-17",title:"Homebrew Character Builder & Level-Up Integration",summary:"Versioned Homebrew class, subclass, species, background and feat packages now participate directly in Builder and Level Up catalogs.",changes:[{text:"Homebrew packages merged into live ruleset catalogs",category:"Özellik"},{text:"Homebrew class, subclass, species and background Builder choices",category:"Özellik"},{text:"Homebrew class and feat Level Up choices",category:"Özellik"},{text:"Duplicate-ID replacement instead of duplicated options",category:"Düzeltme"},{text:"Live package-change refresh event",category:"İyileştirme"},{text:"Builder and Level Up integration certification tests",category:"Teknik"}]},
  {version:"5.11.0",date:"2026-07-17",title:"Homebrew Progression & Play Mode Integration",summary:"Homebrew class/subclass progression, custom resources, recovery and runtime actions now participate in the live character journey.",changes:[{text:"Character-aware Homebrew entity matching",category:"Özellik"},{text:"Level-scaled custom resource synchronization",category:"Özellik"},{text:"Play Mode runtime action execution",category:"Özellik"},{text:"Partial short/long-rest resource recovery",category:"Düzeltme"},{text:"Homebrew progression feature visibility",category:"İyileştirme"},{text:"Homebrew integration certification tests",category:"Teknik"}]},

  {version:"5.10.0",date:"2026-07-17",title:"Homebrew Creator & Runtime Action Builder",summary:"Homebrew Lab now creates versioned class, subclass, species, background, feat, spell and item packages through one visual resource/action builder.",changes:[{text:"Visual seven-type homebrew package creator",category:"Özellik"},{text:"Custom resource and recovery builder",category:"Özellik"},{text:"Action economy and resource-cost builder",category:"Özellik"},{text:"Package preview, storage, import and export UI",category:"Özellik"},{text:"Creator validation and stable ID generation",category:"Düzeltme"},{text:"Homebrew creator certification tests",category:"Teknik"}]},

  {version:"5.9.0",date:"2026-07-17",title:"Homebrew Foundation Upgrade",summary:"Class, subclass, species, background, feat, spell and item homebrew content now shares one versioned package schema with validation, runtime resources and safe import/export.",changes:[{text:"Unified seven-type homebrew entity schema",category:"Özellik"},{text:"Versioned package import/export and duplicate-ID validation",category:"Özellik"},{text:"Custom resource scaling and recovery definitions",category:"Özellik"},{text:"Runtime action economy and resource-cost metadata",category:"Teknik"},{text:"Safe package storage and replacement merge",category:"Düzeltme"},{text:"Homebrew foundation certification tests",category:"Teknik"}]},

  {version:"5.8.0",date:"2026-07-17",title:"UI, Mobile & Accessibility Polish",summary:"Responsive overflow guards, safe-area mobile layouts and reusable dialog focus management complete the player-facing polish pass.",changes:[{text:"Reusable dialog focus trap, Escape close and opener restoration",category:"Düzeltme"},{text:"Release notes and recovery dialogs connected to focus management",category:"İyileştirme"},{text:"44 px touch, safe-area and compact mobile layout guards",category:"İyileştirme"},{text:"Horizontal overflow and responsive media safeguards",category:"Düzeltme"},{text:"Reduced-motion and validation focus polish",category:"İyileştirme"},{text:"UI/mobile/accessibility certification tests",category:"Teknik"}]},

  {version:"5.7.0",date:"2026-07-17",title:"Equipment & Magic Item Final Coverage",summary:"Equipment and magic item families are certified with explicit automation, guidance, table-ruling and blocker outcomes.",changes:[{text:"Weapon, armor and ammunition metadata certification",category:"Teknik"},{text:"Attunement, charge and recharge edge-case coverage",category:"Düzeltme"},{text:"Consumable, restoration and item-spell guidance",category:"İyileştirme"},{text:"Curse and extradimensional table-ruling policy",category:"İyileştirme"},{text:"Duplicate item and malformed metadata release blockers",category:"Düzeltme"},{text:"Final equipment coverage tests",category:"Teknik"}]},

  {version:"5.6.0",date:"2026-07-17",title:"Character Sheet & Play Mode Final Consistency",summary:"Character Sheet and Play Mode now share one final snapshot for combat math, effects, resources and survivability state.",changes:[{text:"Unified weapon attack and damage rows",category:"Düzeltme"},{text:"Shared resistance, condition and active-effect state",category:"İyileştirme"},{text:"Concentration integrity blocker",category:"Düzeltme"},{text:"Spell slot, Pact Magic and resource parity",category:"Teknik"},{text:"Sheet versus Play Mode divergence report",category:"Teknik"},{text:"Final consistency certification tests",category:"Teknik"}]},

  {version:"5.5.0",date:"2026-07-17",title:"Level Up, Feat & Choice Completion",summary:"Level-up milestones, structured feat sub-choices and unified class choice debts are certified in one completion flow.",changes:[{text:"Structured feat ability sub-choice in Level Up Assistant",category:"Özellik"},{text:"Feat choice persistence and capped ability increase",category:"Düzeltme"},{text:"Unified pending choice and blocker report",category:"Teknik"},{text:"Subclass, Mastery, Metamagic, Invocation, Maneuver, Expertise and Arcanum debt coverage",category:"İyileştirme"},{text:"Level-up completion certification tests",category:"Teknik"}]},
  {version:"5.2.0",date:"2026-07-17",title:"Runtime Coverage Closure",summary:"Automatic, Assisted, Manual and Missing behavior is converted into a release closure report with explicit blockers, guidance and table-ruling policy.",changes:[{text:"Central runtime closure report",category:"Teknik"},{text:"Missing behavior release blockers",category:"Düzeltme"},{text:"Assisted behavior guidance",category:"İyileştirme"},{text:"Manual table-ruling documentation",category:"İyileştirme"},{text:"Per-entity closure lookup",category:"Teknik"},{text:"Runtime closure certification tests",category:"Teknik"}]},
  {version:"5.1.0",date:"2026-07-17",title:"Stable Player Post-Release QA & Bug Closure",summary:"Critical player journeys are tracked in one post-release QA matrix so crashes, restore mismatches and gameplay regressions cannot hide behind the stable label.",changes:[{text:"Eleven required player journey QA scenarios",category:"Teknik"},{text:"Critical failure release blockers",category:"Düzeltme"},{text:"Missing scenario warning visibility",category:"İyileştirme"},{text:"Worst-result merge for duplicate QA evidence",category:"Düzeltme"},{text:"Non-critical regression review notes",category:"İyileştirme"},{text:"Post-release QA certification tests",category:"Teknik"}]},
  {version:"5.0.0",date:"2026-07-17",title:"Stable Player Release",summary:"The certified D&D 2014/2024 player journey is promoted to the stable release channel with unified release gates and an explicit runtime guarantee manifest.",changes:[{text:"Stable player release manifest and version gate",category:"Teknik"},{text:"Runtime missing-behavior blocker",category:"Düzeltme"},{text:"Player journey and character integrity certification gates",category:"Teknik"},{text:"Unified hardening, localization, accessibility and licensing readiness",category:"İyileştirme"},{text:"Compact stable release status summary",category:"Özellik"},{text:"v5.0 stable release certification tests",category:"Teknik"}]},
  {version:"4.12.0",date:"2026-07-17",title:"Stable Player Release Hardening Mega Pack",summary:"Crash recovery, migration, backup restore and release gates are certified before the v5.0 stable player release.",changes:[{text:"Unified stable release blocker and warning report",category:"Teknik"},{text:"Current and legacy backup restore certification",category:"Düzeltme"},{text:"Detached rollback backup generation",category:"Özellik"},{text:"Migration failure and unresolved crash release blockers",category:"Düzeltme"},{text:"Recovery quarantine records surfaced as release warnings",category:"İyileştirme"},{text:"Unit, production and browser E2E release gates",category:"Teknik"}]},
  {version:"4.11.0",date:"2026-07-17",title:"Localization, Accessibility & Licensing Audit Mega Pack",summary:"TR/EN navigation coverage, route announcements, coarse-pointer targets, reduced-motion behavior and SRD attribution policy are certified in one release audit.",changes:[{text:"Navigation translation completeness and duplicate-route audit",category:"Teknik"},{text:"Localized document titles and screen-reader route announcements",category:"İyileştirme"},{text:"Image alt attributes included in interface translation bridge",category:"İyileştirme"},{text:"44 px coarse-pointer targets and reduced-motion safeguards",category:"İyileştirme"},{text:"SRD 5.1 / 5.2.1 and CC BY 4.0 attribution policy expansion",category:"Teknik"},{text:"Release readiness audit with blocker-free certification",category:"Teknik"}]},
  {version:"4.4.0",date:"2026-07-17",title:"Arcane Classes Mega Pack",summary:"Bard, Sorcerer, Warlock ve Wizard 2014/2024 kaynak, progression ve subclass davranışları ortak arcane runtime sertifikasında birleştirildi.",changes:[{text:"Sekiz edition-class kombinasyonu için ortak arcane runtime matrisi",category:"Teknik"},{text:"Bardic Inspiration die, kullanım ve recovery progression",category:"Özellik"},{text:"Sorcery Points ve Metamagic seçim progression",category:"Özellik"},{text:"Pact Magic, Eldritch Invocation ve Mystic Arcanum progression",category:"Özellik"},{text:"Arcane Recovery, Spell Mastery ve Signature Spells sertifikası",category:"Özellik"},{text:"Valor, Wild Magic, Great Old One ve Abjurer subclass bağlantıları",category:"Özellik"}]},
  {version:"4.3.0",date:"2026-07-17",title:"Martial Classes Mega Pack",summary:"Fighter, Barbarian, Rogue ve Monk 2014/2024 savaş progression ve subclass davranışları ortak martial runtime altında genişletildi.",changes:[{text:"Sekiz edition-class kombinasyonu için martial runtime matrisi",category:"Teknik"},{text:"Battle Master, Shadow Monk ve Assassin subclass aksiyonları",category:"Özellik"},{text:"Fighter, Rage, Sneak Attack ve Martial Arts kritik level sertifikası",category:"Teknik"}]},
  {version:"4.2.0",date:"2026-07-17",title:"Divine Classes Mega Pack",summary:"Cleric, Paladin, Druid ve Ranger 2014/2024 kaynak ve subclass davranışları ortak divine runtime sertifikasında birleştirildi.",changes:[{text:"Sekiz edition-class kombinasyonu için ortak divine runtime",category:"Teknik"},{text:"Cleric domain Channel Divinity aksiyon ailesi genişletmesi",category:"Özellik"},{text:"Paladin oath Channel Divinity ve Aura of Warding bağlantısı",category:"Özellik"},{text:"Druid 2014/2024 Wild Shape kullanım progression ayrımı",category:"Düzeltme"},{text:"Ranger Hunter's Mark, Favored Enemy ve Beast Master companion progression",category:"Özellik"},{text:"Divine class kritik level regresyon matrisi",category:"Teknik"}]},
  {version:"4.0.0",date:"2026-07-17",title:"Character Management Hub",summary:"Karakter kasası tek karakter taşıma, güvenli kimlik çakışması ve sade kart işlemleriyle tam yönetim merkezine dönüştürüldü.",changes:[{text:"Sürümlü E4 D&D tek karakter JSON formatı",category:"Özellik"},{text:"Karakter kartından tek tık dışa aktarma",category:"Özellik"},{text:"Doğrulamalı ve hydration korumalı tek karakter içe aktarma",category:"Düzeltme"},{text:"Aynı ID durumunda mevcut kaydı ezmeden güvenli kimlik çatallama",category:"Düzeltme"},{text:"Dışa aktar, kopyala ve sil için erişilebilir üç nokta menüsü",category:"İyileştirme"},{text:"Mobil işlem menüsü ve klavye odak görünürlüğü",category:"İyileştirme"}]},
  {version:"3.90.0",date:"2026-07-17",title:"Character Edit Completion",summary:"Kayıtlı karakter düzenleme akışı Builder kurallarıyla eşitlendi; bağımlı seçimler doğrulanır ve multiclass/runtime havuzları kaybolmadan korunur.",changes:[{text:"Kaydetmeyi engelleyen canlı karakter doğrulama raporu",category:"Düzeltme"},{text:"Ruleset bağlantılı race/species, alt soy, class, subclass ve background seçimleri",category:"Özellik"},{text:"2024 background +2/+1 ability seçimleri",category:"Özellik"},{text:"Background ve class skill kotasını ayrı yöneten proficiency editörü",category:"Düzeltme"},{text:"Bard/Rogue expertise kotası ve proficiency bağı doğrulaması",category:"Düzeltme"},{text:"Multiclass classLevels, spell slot, Hit Dice ve Pact Magic veri koruması",category:"Düzeltme"}]},
  {version:"3.80.0",date:"2026-07-17",title:"Player Test Release Candidate",summary:"Oyuncu test turu otomatik release denetimi, kalıcı senaryo listesi ve gizlilik korumalı tanı raporuyla tek merkezden yürütülür.",changes:[{text:"Otomatik ruleset, level 20, runtime ve karakter bütünlük skoru",category:"Özellik"},{text:"2014/2024, multiclass, combat, inventory, backup ve offline test senaryoları",category:"Özellik"},{text:"Cihazda kalıcı gerçek oyuncu test checklist'i",category:"İyileştirme"},{text:"Tekrarlama adımları, beklenen ve gerçek sonuç hata formu",category:"Özellik"},{text:"Karakter/oyuncu isimleri ve serbest notları dışlayan güvenli JSON raporu",category:"Teknik"},{text:"Mobil dokunma hedefleri, responsive düzen ve görünür klavye odağı",category:"İyileştirme"}]},
  {version:"3.70.0",date:"2026-07-17",title:"Character Lifecycle E2E",summary:"2014 ve 2024 karakterleri oluşturma, level 20, rest, multiclass, backup ve migration zincirinde uçtan uca doğrulandı.",changes:[{text:"2014/2024 create → level 20 → rest → backup restore senaryoları",category:"Teknik"},{text:"Multiclass level-up sırasında doğru target class resource üretimi",category:"Düzeltme"},{text:"Multiclass spell slot ve ayrı Hit Die havuzu senaryosu",category:"Teknik"},{text:"Long Rest Pact Magic, Mystic Arcanum ve geçici spell effect reseti",category:"Düzeltme"},{text:"Backup import karakterlerini güvenli hydration katmanından geçirme",category:"Düzeltme"},{text:"Legacy sayaç, inventory ve equipment referans onarımı",category:"Düzeltme"}]},
  {version:"3.60.0",date:"2026-07-17",title:"Rules Runtime Gap Closure",summary:"Runtime sertifikasının öncelikli feat, subclass ve spell material boşlukları gerçek Play Mode davranışlarına yükseltildi.",changes:[{text:"Charger ve Fey-Touched action economy seçenekleri",category:"Özellik"},{text:"Medium Armor Master AC/Stealth, Elemental Adept ve damage-type feat runtime",category:"Özellik"},{text:"Dungeon Delver, Keen Mind, Skulker, Martial Adept, Resilient ve Ritual Caster rehberleri",category:"Özellik"},{text:"Domain Channel Divinity, Arcane Ward, Bend Luck ve Wild Magic Surge action bağlantıları",category:"Özellik"},{text:"Spell focus, costly ve consumed material inventory readiness",category:"Özellik"},{text:"Runtime sertifikasında yeni automatic feat/subclass aileleri ve regresyon testleri",category:"Teknik"}]},
  {version:"3.50.0",date:"2026-07-17",title:"Runtime Coverage Certification",summary:"Class, subclass, feat, spell ve item içerikleri gerçek mekanik çalışma seviyelerine göre ölçülüp Ruleset Center'da raporlanır.",changes:[{text:"Automatic, Assisted, Manual ve Missing runtime sınıfları",category:"Teknik"},{text:"12 dedicated class motoru için otomatik kapsam denetimi",category:"Teknik"},{text:"Subclass feature ve feat behavior bağlantı analizi",category:"Özellik"},{text:"Spell çözüm metadata ve item mechanical field sertifikası",category:"Teknik"},{text:"Kategori puanları, entity detayları ve öncelikli açık listesi",category:"Özellik"},{text:"Gerçek 2014/2024 birleşik veri paketleriyle entegrasyon testleri",category:"Teknik"}]},
  {version:"3.40.0",date:"2026-07-16",title:"Player Journey Localization",summary:"Merkezi arayüz sözlüğü Builder'dan Backup'a kadar oyuncu yolculuğundaki statik ve dinamik metinleri İngilizce seçimine bağladı.",changes:[{text:"100+ ortak UI etiketi ve oyuncu aksiyonu için merkezi EN katalog",category:"Özellik"},{text:"Dinamik sayı, hata, uyarı ve level metinleri için pattern çevirisi",category:"Özellik"},{text:"Placeholder, title ve aria-label çeviri desteği",category:"İyileştirme"},{text:"Dil değişiminde Türkçe metinleri kayıpsız geri yükleme",category:"Düzeltme"},{text:"Kullanıcı/homebrew içeriklerini değiştirmeyen güvenli exact-match yaklaşımı",category:"Teknik"},{text:"Ölçülebilir çeviri kapsam ve fallback regresyon testleri",category:"Teknik"}]},
  {version:"3.30.0",date:"2026-07-16",title:"Turkish & English Interface",summary:"Türkçe varsayılan korunurken kalıcı İngilizce arayüz seçeneği ve güvenli çeviri fallback altyapısı eklendi.",changes:[{text:"Ayarlar üzerinden anında TR/EN dil seçimi",category:"Özellik"},{text:"Eski ayar kayıtlarını Türkçe varsayılanla geriye uyumlu taşıma",category:"Düzeltme"},{text:"Sidebar, mobil navigasyon ve erişilebilirlik etiketleri çevirisi",category:"Özellik"},{text:"Dashboard ana akış ve locale-aware tarih/sayı biçimleme",category:"Özellik"},{text:"Play Mode oynanabilirlik kartı İngilizce desteği",category:"İyileştirme"},{text:"Çeviri interpolation, fallback ve locale regresyon testleri",category:"Teknik"}]},
  {version:"3.20.0",date:"2026-07-16",title:"Playable Character Validation",summary:"Kayıtlı karakterlerin kimlikten combat sayaçlarına kadar oynanabilirliği tek merkezden sertifikalanır ve düzeltme noktaları gösterilir.",changes:[{text:"Kimlik, ability, class-level ve subclass bütünlük denetimi",category:"Düzeltme"},{text:"Feat prerequisite, spell class ve ruleset referans kontrolü",category:"Düzeltme"},{text:"Inventory, equipment, attunement ve quantity güvenlik kontrolleri",category:"Düzeltme"},{text:"Spell slot, HP, exhaustion ve death save aralık doğrulaması",category:"Düzeltme"},{text:"Character Detail bölüm bazlı doğrulama raporu",category:"Özellik"},{text:"Play Mode hata sayısı ve doğrudan edit yönlendirmesi",category:"İyileştirme"}]},
  {version:"3.10.0",date:"2026-07-16",title:"Level 1–20 Certification",summary:"2014 ve 2024 karakter yaşam döngüsü makine tarafından denetlenen class, içerik ve referans matrisiyle sertifikalandı.",changes:[{text:"12 class × 2 edition × 20 level progression matrisi",category:"Teknik"},{text:"Subclass, spell level ve equipment coverage kontrolleri",category:"Teknik"},{text:"Bonus spell, item spell, pack ve feat prerequisite referans denetimi",category:"Düzeltme"},{text:"Kategori bazlı benzersiz entity kimliği kontrolü",category:"Teknik"},{text:"Ruleset Center certification skoru ve blocker dashboard",category:"Özellik"},{text:"Gerçek 2014/2024 veri paketleriyle entegrasyon testleri",category:"Teknik"}]},
  {version:"3.0.0",date:"2026-07-16",title:"Equipment & Multiclass",summary:"Geriye uyumlu multiclass progression ile ekipman uygunluk ve taşıma kuralları karakter yaşam döngüsüne bağlandı.",changes:[{text:"Eski karakterleri classLevels modeline otomatik taşıma",category:"Düzeltme"},{text:"Multiclass prerequisite ve class seçmeli level-up",category:"Özellik"},{text:"Birleşik caster level, spell slot ve ayrı Hit Dice havuzları",category:"Özellik"},{text:"Extra Attack stacking engeli",category:"Düzeltme"},{text:"Armor/weapon proficiency ve heavy armor Strength kontrolü",category:"Özellik"},{text:"Encumbrance, taşıma kapasitesi ve hız cezaları",category:"Özellik"},{text:"Ranged saldırıda otomatik ammunition tüketimi",category:"Özellik"},{text:"Multiclass ve equipment için altı otomatik test",category:"Teknik"}]},
  {version:"2.90.0",date:"2026-07-16",title:"Feats & Spell Behavior",summary:"Gelişmiş feat etkileri ile ritual, alan, hedef, summon ve movement spell davranışları ortak runtime'a bağlandı.",changes:[{text:"Defensive Duelist, Inspiring Leader, Shield/Polearm Master ve Telekinetic eylemleri",category:"Özellik"},{text:"Dual Wielder AC, Spell Sniper range ve Crossbow loading pasifleri",category:"Özellik"},{text:"2014 power attack −5/+10 seçeneği",category:"Özellik"},{text:"Feat kaynaklı concentration ve mental save advantage",category:"Düzeltme"},{text:"Ritual cast ile slot harcamadan kullanım",category:"Özellik"},{text:"AoE, upcast target, repeat save, summon, movement ve material göstergeleri",category:"Özellik"},{text:"Feat ve spell behavior için altı otomatik test",category:"Teknik"}]},
  {version:"2.80.0",date:"2026-07-16",title:"Complete Subclass Runtime",summary:"Subclass progression tek bir ortak motorla Play Mode action, reaction ve pasif hesaplarına bağlandı.",changes:[{text:"Level bazlı unlocked subclass feature runtime",category:"Özellik"},{text:"Domain, school, path, college, patron ve oath ortak motoru",category:"Teknik"},{text:"Subclass Action/Bonus Action/Reaction ve kaynak tüketimi",category:"Özellik"},{text:"Champion geniş critical range",category:"Özellik"},{text:"College of Valor Extra Attack ve Draconic AC floor",category:"Özellik"},{text:"Subclass psychic/physical resistance ve Assassin initiative",category:"Özellik"},{text:"Subclass runtime için üç otomatik davranış testi",category:"Teknik"}]},
  {version:"2.70.0",date:"2026-07-16",title:"Rules & Character Completion",summary:"Kapsam sertifikası, SRD bildirimi, ancestry runtime ve level 20 class davranışları tek büyük pakette birleştirildi.",changes:[{text:"Ruleset Center otomatik runtime coverage skoru",category:"Özellik"},{text:"SRD 5.1 / 5.2.1 CC BY 4.0 attribution paneli",category:"Teknik"},{text:"Race/species speed, darkvision, resistance ve save advantage runtime",category:"Özellik"},{text:"Dwarven Toughness, Savage Attacks ve ancestry feature özeti",category:"Özellik"},{text:"Rogue Reliable Talent minimum roll entegrasyonu",category:"Düzeltme"},{text:"Barbarian level 20 STR/CON capstone hesapları",category:"Özellik"},{text:"Yeni coverage, ancestry ve class completion testleri",category:"Teknik"}]},
  {version:"2.62.0",date:"2026-07-16",title:"Fighting Style Runtime",summary:"Kalan core Fighting Style seçimleri weapon damage, reaction ve unarmed action sistemlerine bağlandı.",changes:[{text:"Great Weapon Fighting 1–2 damage die reroll",category:"Özellik"},{text:"Off-hand damage ve Two-Weapon Fighting ayrımı",category:"Düzeltme"},{text:"Unarmed Fighting d6/d8 attack runtime",category:"Özellik"},{text:"Protection Reaction ve ally attack disadvantage",category:"Özellik"},{text:"Interception 1d10 + PB damage reduction",category:"Özellik"},{text:"Fighting Style runtime için dört otomatik test",category:"Teknik"}]},
  {version:"2.61.0",date:"2026-07-16",title:"Weapon Mastery Runtime",summary:"2024 Weapon Mastery seçimleri gerçek weapon attack çözümüne ve takip günlüğüne bağlandı.",changes:[{text:"Yalnızca seçilmiş 2024 mastery silahlarında çalışma",category:"Düzeltme"},{text:"Vex ile sonraki attack'a otomatik advantage",category:"Özellik"},{text:"Graze ile miss durumunda ability modifier damage",category:"Özellik"},{text:"Push, Sap, Slow ve Topple takip çıktıları",category:"Özellik"},{text:"Cleave ve Nick action economy hatırlatmaları",category:"İyileştirme"},{text:"Weapon Mastery için dört otomatik test",category:"Teknik"}]},
  {version:"2.60.0",date:"2026-07-16",title:"Ruleset Code Splitting",summary:"Büyük spell, item, feat ve subclass veri modülleri ilk açılış paketinden ayrıldı.",changes:[{text:"Spell expansion için ayrı lazy chunk",category:"Teknik"},{text:"Item expansion için ayrı lazy chunk",category:"Teknik"},{text:"Feat ve subclass expansion lazy loading",category:"Teknik"},{text:"Ruleset JSON ve expansion yüklemelerini koruma",category:"Düzeltme"},{text:"İlk JavaScript bundle boyutunu belirgin azaltma",category:"İyileştirme"},{text:"Dynamic import regresyon testi",category:"Teknik"}]},
  {version:"2.59.0",date:"2026-07-16",title:"Offensive Consumables",summary:"Thrown, poison ve magical offensive consumable'lar damage/save çözümüyle Play Mode'a bağlandı.",changes:[{text:"10 yeni offensive consumable",category:"Özellik"},{text:"Acid, fire, radiant, poison, thunder ve force damage rolları",category:"Özellik"},{text:"Item bazlı CON/DEX save DC",category:"Özellik"},{text:"Başarılı save'de half veya zero damage çözümü",category:"Özellik"},{text:"Holy Water için Undead/Fiend hedef türü kontrolü",category:"Düzeltme"},{text:"Offensive item metadata regresyon testi",category:"Teknik"}]},
  {version:"2.58.0",date:"2026-07-16",title:"Restorative Consumables",summary:"Healing, condition cure, exhaustion ve Hit Dice restoration ürünleri gerçek karakter durumuna bağlandı.",changes:[{text:"10 yeni restorative consumable",category:"Özellik"},{text:"Structured healing formula ile açıklamadan bağımsız HP yenileme",category:"İyileştirme"},{text:"Blinded, Deafened, Paralyzed, Poisoned ve hareket condition cure",category:"Özellik"},{text:"Vitality ürünleriyle exhaustion temizleme",category:"Özellik"},{text:"Harcanmış Hit Dice havuzlarını yenileme",category:"Özellik"},{text:"Restoration metadata için iki yeni otomatik kontrol",category:"Teknik"}]},
  {version:"2.57.0",date:"2026-07-16",title:"Accessory Combat Integration",summary:"Magic accessory effective ability değerleri tüm temel Play Mode zar ve spell hesaplarına taşındı.",changes:[{text:"STR-setting item'ları weapon attack ve damage hesaplarına bağlama",category:"Düzeltme"},{text:"CON-setting item'ları concentration ve Hit Die rollarına bağlama",category:"Düzeltme"},{text:"Effective ability değerlerini raw ability quick rollarına bağlama",category:"İyileştirme"},{text:"Class bazlı INT/WIS/CHA spellcasting ability seçimi",category:"Düzeltme"},{text:"Effective ability ile spell attack ve save DC hesaplama",category:"Düzeltme"},{text:"Play Mode combat dosyasında okunabilir weapon runtime düzeni",category:"Teknik"}]},
  {version:"2.56.0",date:"2026-07-16",title:"Magic Accessory Runtime",summary:"Ability-setting ve passive bonus magic item'ları attunement kontrollü Play Mode hesaplarına bağlandı.",changes:[{text:"10 yeni magic accessory",category:"Özellik"},{text:"Gauntlets, Headband, Amulet ve Giant Belt ability minimumları",category:"Özellik"},{text:"Ability değerini doğal skorun altına düşürmeme",category:"Düzeltme"},{text:"Stone of Good Luck save ve ability check +1",category:"Özellik"},{text:"Striding boots ile walking speed +10 ft.",category:"Özellik"},{text:"Magic accessory birleşimleri için üç otomatik test",category:"Teknik"}]},
  {version:"2.55.0",date:"2026-07-16",title:"Magic Armor Runtime",summary:"Magic armor AC, damage resistance ve critical protection davranışları Play Mode hasar motoruna bağlandı.",changes:[{text:"10 yeni magic armor ve shield",category:"Özellik"},{text:"Plate +1/+2/+3 ve Shield +2/+3 auto-AC desteği",category:"Özellik"},{text:"Fire, cold, lightning ve poison resistance armor",category:"Özellik"},{text:"Kuşanma ve attunement doğrulamalı resistance",category:"Düzeltme"},{text:"Adamantine armor ile critical hit'i normal hit'e çevirme",category:"Özellik"},{text:"Magic armor runtime için üç otomatik test",category:"Teknik"}]},
  {version:"2.54.0",date:"2026-07-16",title:"Magic Weapon Runtime",summary:"Elemental, slayer ve critical magic weapon hasarları hedef türüyle birlikte saldırı motoruna bağlandı.",changes:[{text:"10 yeni magic weapon seçeneği",category:"Özellik"},{text:"Flame Tongue ve Frost Brand otomatik elemental damage",category:"Özellik"},{text:"Dragon, Giant ve Undead/Fiend hedef türü seçimi",category:"Özellik"},{text:"Slayer silahlarında yalnızca eşleşen hedefe ek damage",category:"Düzeltme"},{text:"Vicious weapon için critical-only damage",category:"Özellik"},{text:"Magic weapon damage çözümü için üç otomatik test",category:"Teknik"}]},
  {version:"2.53.0",date:"2026-07-16",title:"Advanced Potion Rules",summary:"Heroism, Invisibility, Diminution ve Gaseous Form potion davranışları action ve roll motorlarına bağlandı.",changes:[{text:"Potion of Heroism ile 10 Temp HP",category:"Özellik"},{text:"Heroism boyunca attack ve saving throw sonuçlarına +1d4",category:"Özellik"},{text:"Potion of Invisibility etkisini saldırı veya spell sonrası otomatik bitirme",category:"Düzeltme"},{text:"Potion of Diminution ile weapon damage -1d4",category:"Özellik"},{text:"Gaseous Form sırasında weapon attack ve spell kullanımını engelleme",category:"Düzeltme"},{text:"İleri potion kuralları için dört otomatik test",category:"Teknik"}]},
  {version:"2.52.0",date:"2026-07-16",title:"Potion Mechanical Effects",summary:"Süreli potion kayıtları karakterin gerçek savaş, save, hareket ve hasar hesaplarına bağlandı.",changes:[{text:"Potion of Speed ile AC +2, iki kat speed ve DEX save advantage",category:"Özellik"},{text:"Potion of Invisibility ile weapon attack advantage",category:"Özellik"},{text:"Potion of Growth ile isabette +1d4 weapon damage",category:"Özellik"},{text:"Potion of Resistance ve Gaseous Form için seçilebilir hasar azaltma",category:"Özellik"},{text:"Flying speed ve water breathing runtime göstergeleri",category:"İyileştirme"},{text:"Potion modifier birleşimleri için üç otomatik test",category:"Teknik"}]},
  {version:"2.51.0",date:"2026-07-16",title:"Potion Effect Runtime",summary:"Süreli magic potion etkileri aktif effect ve round takip sistemine bağlandı.",changes:[{text:"10 süreli magic potion",category:"Özellik"},{text:"Potion kullanımında inventory miktarını güvenli azaltma",category:"Özellik"},{text:"Potion etkilerini active effect tracker'a ekleme",category:"Özellik"},{text:"Round ilerledikçe kalan süreyi otomatik azaltma",category:"İyileştirme"},{text:"Long Rest sırasında süreli etkileri temizleme",category:"İyileştirme"},{text:"Potion effect metadata regresyon testi",category:"Teknik"}]},
  {version:"2.50.0",date:"2026-07-16",title:"Spell Scroll Runtime",summary:"Spell scroll kataloğu tek kullanımlık, slot harcamayan spell runtime akışına bağlandı.",changes:[{text:"10 core spell scroll",category:"Özellik"},{text:"Scroll kullanımında envanter miktarını güvenli azaltma",category:"Özellik"},{text:"Character spell slotu harcamadan spell cast",category:"Özellik"},{text:"Damage, healing, concentration ve effect runtime entegrasyonu",category:"İyileştirme"},{text:"Action/Bonus Action/Reaction doluysa scroll'u tüketmeme",category:"Düzeltme"},{text:"Scroll metadata bütünlük testi",category:"Teknik"}]},
  {version:"2.49.0",date:"2026-07-16",title:"Wands, Staff & Pearl",summary:"Charged spellcasting item kataloğu ve Pearl of Power özel davranışı genişletildi.",changes:[{text:"Fireball, Lightning Bolt, Web, Fear, Paralysis ve Polymorph wand'ları",category:"Özellik"},{text:"Staff of Healing ile slot harcamadan Cure Wounds",category:"Özellik"},{text:"Pearl of Power ile level 3 veya altı en yüksek harcanmış slotu yenileme",category:"Özellik"},{text:"Attunement ve charge maliyeti kontrolleri",category:"Düzeltme"},{text:"Long Rest recharge sistemiyle tam entegrasyon",category:"İyileştirme"},{text:"Pearl slot recovery regresyon testi",category:"Teknik"}]},
  {version:"2.48.0",date:"2026-07-16",title:"Magic Item Recharge",summary:"Long Rest magic item charge yenilemesi eşya bazlı dice formüllerine bağlandı.",changes:[{text:"1d3, 1d6+1 ve benzeri recharge parser",category:"Özellik"},{text:"Long Rest sırasında gerçek charge recovery roll",category:"Özellik"},{text:"Geri kazanımı item maksimumunda sınırlama",category:"Düzeltme"},{text:"Kullanılmamış charge değerini aşmama",category:"Düzeltme"},{text:"Basit daily kayıtlarında tam yenileme",category:"Özellik"},{text:"Recharge edge-case otomatik testleri",category:"Teknik"}]},
  {version:"2.47.0",date:"2026-07-16",title:"Magic Item Spellcasting",summary:"Charged magic item kullanımı gerçek spell runtime akışına bağlandı.",changes:[{text:"Magic item spell adı ve charge cost metadata",category:"Özellik"},{text:"Wand of Magic Detection ile Detect Magic",category:"Özellik"},{text:"Wand of Magic Missiles ile Magic Missile",category:"Özellik"},{text:"Eyes of Charming ile Charm Person",category:"Özellik"},{text:"Item spell kullanımında character spell slotu harcamama",category:"Düzeltme"},{text:"Spell linkage regresyon testi",category:"Teknik"}]},
  {version:"2.46.0",date:"2026-07-16",title:"Magic Item Effects",summary:"Magic item kataloğu genişletildi ve attuned savunma bonusları karakter hesaplarına bağlandı.",changes:[{text:"10 yeni potion, ring, charged item, weapon ve armor",category:"Özellik"},{text:"Attuned Cloak/Ring of Protection AC bonusu",category:"Özellik"},{text:"Attuned protection saving throw bonusu",category:"Özellik"},{text:"+1 dagger, longbow, shield ve chain mail",category:"Özellik"},{text:"Charged charm/light item seçenekleri",category:"Özellik"},{text:"Attuned bonus regresyon testi",category:"Teknik"}]},
  {version:"2.45.0",date:"2026-07-16",title:"Magic Items & Attunement",summary:"İlk magic item kataloğu, attunement ve charge runtime sistemi eklendi.",changes:[{text:"10 telif-güvenli core magic item",category:"Özellik"},{text:"Rarity ve üç item attunement sınırı",category:"Özellik"},{text:"Charge harcama ve Long Rest günlük yenileme",category:"Özellik"},{text:"Play Mode Attunement & Charges paneli",category:"Özellik"},{text:"+1 magic weapon attack/damage entegrasyonu",category:"İyileştirme"},{text:"Magic item runtime için üç otomatik test",category:"Teknik"}]},
  {version:"2.44.0",date:"2026-07-16",title:"Core Equipment Expansion",summary:"Eksik normal silahlar, ammunition, tool ve adventuring gear kataloğa eklendi.",changes:[{text:"24 simple/martial weapon ile normal silah ailelerini genişletme",category:"Özellik"},{text:"Arrow, crossbow bolt ve blowgun needle ammunition",category:"Özellik"},{text:"Thieves', herbalism, disguise, poisoner ve navigator tools",category:"Özellik"},{text:"Backpack, bedroll, crowbar, tinderbox ve waterskin",category:"Özellik"},{text:"2024 Weapon Mastery metadata ve Inventory kategori filtreleri",category:"İyileştirme"},{text:"Ekipman genişlemesi için üç otomatik test",category:"Teknik"}]},
  {version:"2.43.0",date:"2026-07-16",title:"Core Spell Coverage",summary:"Kalan belirgin detection, illusion, ritual ve high-magic katalog boşlukları kapatıldı.",changes:[{text:"27 yeni spell ile toplam 334 benzersiz spell",category:"Özellik"},{text:"Detection, purification ve düşük seviye illusion seçenekleri",category:"Özellik"},{text:"Freezing Sphere, Magic Jar, Word of Recall ve Arcane Sword",category:"Özellik"},{text:"Power Word Stun, Telepathy, Tsunami, Time Stop ve Weird",category:"Özellik"},{text:"Ritual, reaction, material, condition ve scaling metadata",category:"İyileştirme"},{text:"Tüm spell levelleri ve benzersiz kimlik kapsam testi",category:"Teknik"}]},
  {version:"2.42.0",date:"2026-07-16",title:"Advanced Spell Library",summary:"Level 3–5 curse, summon, terrain, wall ve half-caster spell havuzları genişletildi.",changes:[{text:"40 yeni spell ile toplam 307 spell",category:"Özellik"},{text:"Bestow Curse, Fear, Remove Curse ve Glyph of Warding",category:"Özellik"},{text:"Elemental, woodland ve animal summon seçenekleri",category:"Özellik"},{text:"Ranger volley/quiver ve Paladin Banishing Smite seçenekleri",category:"Özellik"},{text:"Wall, terrain, ritual ve material metadata",category:"İyileştirme"},{text:"Level 3–5 kapsam regresyon testleri",category:"Teknik"}]},
  {version:"2.41.0",date:"2026-07-16",title:"Adventuring Spell Library",summary:"Level 1–3 exploration, utility ve half-caster spell havuzları genişletildi.",changes:[{text:"40 yeni spell ile toplam 267 spell",category:"Özellik"},{text:"Ranger için Hunter's Mark, Goodberry, Alarm ve keşif seçenekleri",category:"Özellik"},{text:"Paladin için Find Steed, Branding Smite ve savunma seçenekleri",category:"Özellik"},{text:"Warlock için Hex, Armor of Agathys ve Hellish Rebuke",category:"Özellik"},{text:"Ritual, reaction, summon, material ve scaling metadata",category:"İyileştirme"},{text:"Half-caster ve alt seviye spell kapsam testleri",category:"Teknik"}]},
  {version:"2.40.0",date:"2026-07-16",title:"High-Level Spell Library",summary:"Level 6–9 divine, primal ve arcane spell havuzları genişletildi.",changes:[{text:"40 yeni yüksek seviye spell ile toplam 227 spell",category:"Özellik"},{text:"Level 6 için 14 yeni spell",category:"Özellik"},{text:"Level 7 için 10 yeni spell",category:"Özellik"},{text:"Level 8 ve 9 için toplam 16 yeni spell",category:"Özellik"},{text:"Caster class, damage, save, concentration ve material metadata",category:"İyileştirme"},{text:"Yüksek seviye class kapsam regresyon testleri",category:"Teknik"}]},
  {version:"2.39.0",date:"2026-07-16",title:"Subclass Spell Integrity",summary:"Domain ve oath spell listelerinde bulunamayan katalog referansları kapatıldı.",changes:[{text:"59 yeni spell kaydıyla toplam 187 spell",category:"Özellik"},{text:"Domain, oath ve subclass bonus spell referansları tamamlama",category:"Düzeltme"},{text:"Level 1–5 caster listelerini genişletme",category:"Özellik"},{text:"Damage, healing, save, concentration ve scaling metadata",category:"İyileştirme"},{text:"2014 ve 2024 için ayrı ve benzersiz spell kimlikleri",category:"Teknik"},{text:"Subclass spell bütünlük regresyon testi",category:"Teknik"}]},
  {version:"2.38.0",date:"2026-07-16",title:"Consumables & Ammunition",summary:"Consumable item ve ammunition miktarları Play Mode'da kullanılabilir hale getirildi.",changes:[{text:"Consumable tag ve ammunition otomatik tespiti",category:"Özellik"},{text:"Potion of Healing dice formülü ve otomatik HP",category:"Özellik"},{text:"Kullanımda inventory quantity azaltma",category:"Özellik"},{text:"Miktarı sıfırlanan item'ı güvenli kaldırma",category:"Düzeltme"},{text:"Consumable ve ammunition masa paneli",category:"Özellik"},{text:"Item use için üç otomatik test",category:"Teknik"}]},
  {version:"2.37.0",date:"2026-07-16",title:"Feat Runtime Engine",summary:"Temel feat seçimleri karakterin masa değerlerine ve kullanım konsoluna bağlandı.",changes:[{text:"2014 +5 / 2024 PB bazlı Alert initiative",category:"Özellik"},{text:"Mobile +10 ft. speed ve exhaustion entegrasyonu",category:"Özellik"},{text:"Tough level başına +2 HP katkı görünümü",category:"Özellik"},{text:"Lucky 2014 üç / 2024 PB kadar kullanım",category:"Özellik"},{text:"Observant passive score bonusu",category:"Özellik"},{text:"Feat runtime için üç otomatik test",category:"Teknik"}]},
  {version:"2.36.0",date:"2026-07-16",title:"Ranger Hunter's Mark",summary:"Ranger av döngüsü ve 2024 Favored Enemy kullanımları Play Mode'a bağlandı.",changes:[{text:"Wisdom bazlı ücretsiz Favored Enemy kullanımları",category:"Özellik"},{text:"Bonus Action ve concentration entegrasyonu",category:"Özellik"},{text:"Level bazlı Hunter's Mark damage die",category:"Özellik"},{text:"2014 spell slot / 2024 ücretsiz kullanım ayrımı",category:"Düzeltme"},{text:"Deft Explorer, Roving, Tireless, Nature's Veil ve Foe Slayer",category:"Özellik"},{text:"Ranger progression için üç otomatik test",category:"Teknik"}]},
  {
    version:"2.35.0",date:"2026-07-16",title:"Wizard Arcane Recovery",
    summary:"Wizard Arcane Recovery, bütçe kontrollü çoklu spell slot seçimiyle Play Mode'a bağlandı.",
    changes:[
      {text:"Wizard level yarısı yukarı yuvarlanan recovery bütçesi",category:"Özellik"},
      {text:"Birden fazla spell slotu birlikte geri kazanma",category:"Özellik"},
      {text:"Level 6+ slot ve bütçe aşımı engeli",category:"Düzeltme"},
      {text:"Long Rest başına tek Arcane Recovery kullanımı",category:"Düzeltme"},
      {text:"Memorize Spell, Spell Mastery ve Signature Spells",category:"Özellik"},
      {text:"Wizard progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.34.0",date:"2026-07-16",title:"Sorcerer Font of Magic",
    summary:"Sorcery Points ve spell slotları arasındaki çift yönlü dönüşüm Play Mode kaynak sistemine bağlandı.",
    changes:[
      {text:"Level 1–5 slot yaratma için 2/3/5/6/7 SP maliyeti",category:"Özellik"},
      {text:"Spell slot harcayarak slot level kadar SP kazanma",category:"Özellik"},
      {text:"Sorcery Point maksimumu ve hazır/harcanmış slot kontrolleri",category:"Düzeltme"},
      {text:"Metamagic ile ortak Sorcery Point havuzu",category:"Düzeltme"},
      {text:"Sorcerous Restoration progression görünümü",category:"Özellik"},
      {text:"Font of Magic için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.33.0",date:"2026-07-16",title:"Cleric Channel Divinity",
    summary:"Cleric Channel Divinity seçenekleri, Turn Undead ve edition özellikleri Play Mode'a bağlandı.",
    changes:[
      {text:"Level bazlı 1–3 Channel Divinity kullanımı",category:"Özellik"},
      {text:"Turn Undead WIS Save DC ve Action harcaması",category:"Özellik"},
      {text:"2024 Divine Spark healing/radiant damage roll",category:"Özellik"},
      {text:"2014 Destroy Undead CR progression",category:"Özellik"},
      {text:"Blessed Strikes ve Divine Intervention görünümü",category:"Özellik"},
      {text:"Cleric progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.32.0",date:"2026-07-16",title:"Fighter Action Surge & Indomitable",
    summary:"Fighter'ın temel savaş kaynakları Action Economy ve save reroll akışına bağlandı.",
    changes:[
      {text:"Level 5/11/20 Extra Attack progression",category:"Özellik"},
      {text:"Action Surge ile Action ve attack sayacını yenileme",category:"Özellik"},
      {text:"Level 17'de ikinci Action Surge kullanımı",category:"Özellik"},
      {text:"Indomitable 1–3 kullanım ve save reroll",category:"Özellik"},
      {text:"2024 Indomitable Fighter level bonusu",category:"Düzeltme"},
      {text:"Fighter progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.31.0",date:"2026-07-16",title:"Bardic Inspiration & Support",
    summary:"Bardic Inspiration zarları, kaynak harcaması ve Bard destek progression'ı Play Mode'a bağlandı.",
    changes:[
      {text:"Level bazlı d6, d8, d10 ve d12 Bardic Inspiration",category:"Özellik"},
      {text:"Bonus Action ve kaynak harcaması entegrasyonu",category:"Düzeltme"},
      {text:"Level 5 Font of Inspiration short rest recovery",category:"Özellik"},
      {text:"2014 edition Song of Rest progression",category:"Özellik"},
      {text:"Countercharm, Magical Secrets ve Superior Inspiration",category:"Özellik"},
      {text:"Bard progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.30.0",date:"2026-07-16",title:"Monk Martial Arts & Focus",
    summary:"Monk Martial Arts saldırıları, Focus/Ki harcaması ve temel combat seçenekleri Action Economy'ye bağlandı.",
    changes:[
      {text:"2014 ve 2024 ayrı Martial Arts die progression",category:"Özellik"},
      {text:"Unarmed Strike otomatik attack ve damage roll",category:"Özellik"},
      {text:"Flurry of Blows, Patient Defense ve Step of the Wind",category:"Özellik"},
      {text:"Focus/Ki kaynağı ve Bonus Action harcaması",category:"Düzeltme"},
      {text:"Unarmored Movement ve ileri seviye Monk özellikleri",category:"Özellik"},
      {text:"Monk progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.29.0",date:"2026-07-16",title:"Barbarian Rage Combat",
    summary:"Barbarian Rage savunması ve 1–20 combat progression bilgileri Play Mode hasar motoruna bağlandı.",
    changes:[
      {text:"Level bazlı +2/+3/+4 Rage damage hesabı",category:"Özellik"},
      {text:"Rage sırasında fiziksel hasarı yarıya indirme",category:"Özellik"},
      {text:"STR melee weapon uygunluk kontrolü",category:"Düzeltme"},
      {text:"2014 ve 2024 Brutal Critical progression ayrımı",category:"Özellik"},
      {text:"Reckless Attack, Danger Sense, Relentless ve Persistent Rage paneli",category:"Özellik"},
      {text:"Barbarian combat kuralları için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.28.0",date:"2026-07-16",title:"Rogue Sneak Attack & Cunning Action",
    summary:"Rogue'un temel 1–20 savaş döngüsü Sneak Attack ve Action Economy entegrasyonuyla tamamlandı.",
    changes:[
      {text:"Level 1–20 için 1d6–10d6 Sneak Attack progression",category:"Özellik"},
      {text:"Finesse/ranged silah, advantage, ally ve disadvantage kontrolü",category:"Düzeltme"},
      {text:"Tur başına tek Sneak Attack ve critical dice doubling",category:"Özellik"},
      {text:"Cunning Action ile Bonus Action Dash, Disengage ve Hide",category:"Özellik"},
      {text:"Uncanny Dodge, Evasion, Reliable Talent ve Elusive görünümü",category:"Özellik"},
      {text:"Rogue savaş kuralları için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.27.0",date:"2026-07-16",title:"Turn Action Economy",
    summary:"Action, Bonus Action, Reaction, movement ve Extra Attack kullanımı Play Mode tur döngüsüne bağlandı.",
    changes:[
      {text:"Tek tıkla sıfırlanan yeni tur konsolu",category:"Özellik"},
      {text:"Action, Bonus Action ve Reaction bağımsız takibi",category:"Özellik"},
      {text:"Hareket hızına göre 5/10/15 ft. movement harcama",category:"Özellik"},
      {text:"Fighter ve martial class Extra Attack progression",category:"Özellik"},
      {text:"Weapon attack ve spell casting time otomatik kaynak harcaması",category:"Düzeltme"},
      {text:"Action economy için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.26.0",date:"2026-07-16",title:"Spell Target Resolution",
    summary:"Spell attack ve saving throw büyüleri hedef savunmasına karşı otomatik çözülür hale getirildi.",
    changes:[
      {text:"Spell attack için hedef AC, hit, miss ve critical çözümü",category:"Özellik"},
      {text:"Hedef saving throw bonusu ve Spell Save DC karşılaştırması",category:"Özellik"},
      {text:"Hedef rollarında normal, advantage ve disadvantage",category:"Özellik"},
      {text:"Başarılı save sonrası yarım hasar veya hasarsız seçenek",category:"Özellik"},
      {text:"Miss durumunda spell damage uygulanmaması",category:"Düzeltme"},
      {text:"Spell target resolution için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.25.0",date:"2026-07-16",title:"Edition-Aware Exhaustion Engine",
    summary:"Exhaustion artık yalnızca sayaç değil; 2014 ve 2024 mekanikleriyle saldırı, check, save, hız ve HP hesaplarını etkiliyor.",
    changes:[
      {text:"2014 level 1–6 disadvantage, speed ve max HP basamakları",category:"Özellik"},
      {text:"2024 her level için kümülatif D20 -2 ve Speed -5 ft.",category:"Özellik"},
      {text:"Weapon attack, skill check ve saving throw entegrasyonu",category:"Düzeltme"},
      {text:"Play Mode exhaustion artırma/azaltma konsolu",category:"Özellik"},
      {text:"Level 6 ölüm durumu ve eylem kilidi",category:"Özellik"},
      {text:"İki edition için üç otomatik exhaustion testi",category:"Teknik"},
    ],
  },
  {
    version:"2.24.0",date:"2026-07-16",title:"Skill & Saving Throw Console",
    summary:"Tüm skill check ve saving throw sonuçları gerçek proficiency katmanları ve roll modlarıyla Play Mode'a taşındı.",
    changes:[
      {text:"Altı ability saving throw için class proficiency bonusu",category:"Özellik"},
      {text:"On sekiz skill için ability, proficiency ve expertise hesabı",category:"Özellik"},
      {text:"Skill ve save atışlarında normal, advantage ve disadvantage",category:"Özellik"},
      {text:"Bard level 2+ Jack of All Trades yarım proficiency",category:"Özellik"},
      {text:"Roll geçmişinde iki d20 ve seçilen sonuç görünümü",category:"İyileştirme"},
      {text:"Jack of All Trades regresyon testi",category:"Teknik"},
    ],
  },
  {
    version:"2.23.0",date:"2026-07-16",title:"Standard Conditions Engine",
    summary:"Standart koşul kapsamı tamamlandı ve aktif durumların mekanik etkileri saldırı konsoluna bağlandı.",
    changes:[
      {text:"Blinded, Charmed, Deafened, Frightened, Grappled ve Incapacitated",category:"Özellik"},
      {text:"Paralyzed, Petrified ve Unconscious condition desteği",category:"Özellik"},
      {text:"Condition kaynaklı attack advantage/disadvantage",category:"Özellik"},
      {text:"Advantage ve disadvantage birbirini götürme kuralı",category:"Düzeltme"},
      {text:"Incapacitated ailesinde weapon action engeli ve speed 0 özeti",category:"Özellik"},
      {text:"Condition mechanics için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.22.0",date:"2026-07-16",title:"Weapon Attack Resolution",
    summary:"Silah saldırıları hedef AC, advantage/disadvantage, natural sonuçlar ve kritik hasarla tek tıkta çözülür hale geldi.",
    changes:[
      {text:"Normal, advantage ve disadvantage d20 seçim motoru",category:"Özellik"},
      {text:"Ayarlanabilir hedef Armor Class kontrolü",category:"Özellik"},
      {text:"Natural 1 otomatik miss ve Natural 20 otomatik critical",category:"Düzeltme"},
      {text:"İsabette otomatik weapon damage roll",category:"Özellik"},
      {text:"Kritikte yalnızca damage dice sayısının ikiye katlanması",category:"Düzeltme"},
      {text:"Attack resolution için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.21.0",date:"2026-07-16",title:"Damage & Survival Engine",
    summary:"Hasar, temporary HP, concentration ve death save akışı tek bir kurallı masa konsolunda birleştirildi.",
    changes:[
      {text:"Temporary HP'yi önce tüketen merkezi hasar motoru",category:"Düzeltme"},
      {text:"Alınan hasardan otomatik DC 10 veya yarı hasar concentration kontrolü",category:"Özellik"},
      {text:"Normal ve kritik hasarın 0 HP'de death save failure işlemesi",category:"Özellik"},
      {text:"Natural 1, Natural 20, başarı ve başarısızlık death save kuralları",category:"Özellik"},
      {text:"Massive damage ile anlık üç başarısızlık kontrolü",category:"Özellik"},
      {text:"Survival lifecycle için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.20.0",date:"2026-07-16",title:"Concentration & Active Spell Effects",
    summary:"Kalıcı spell etkileri, concentration değişimi, süre ilerletme ve CON save yönetimi Play Mode'a eklendi.",
    changes:[
      {text:"Aktif spell effect kimliği ve save/reload persistence",category:"Özellik"},
      {text:"Yeni concentration spell cast edilince önceki etkinin bitmesi",category:"Düzeltme"},
      {text:"Round, minute ve hour duration dönüşümü",category:"Özellik"},
      {text:"Play Mode'da round ilerletme ve manuel effect bitirme",category:"Özellik"},
      {text:"DC 10/15/20 concentration CON save kontrolleri",category:"Özellik"},
      {text:"Spell effect lifecycle için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.19.0",date:"2026-07-16",title:"Spell Resolution Core",
    summary:"Spell cast akışı uygun üst slot seçimi, scaling ve otomatik attack/damage/healing roll ile genişletildi.",
    changes:[
      {text:"Aynı veya daha yüksek uygun slotla cast seçimi",category:"Düzeltme"},
      {text:"Slot level bazlı damage ve healing upcast scaling",category:"Özellik"},
      {text:"Level 5, 11 ve 17 cantrip dice scaling",category:"Özellik"},
      {text:"Spell attack için otomatik d20 + spell attack bonus roll",category:"Özellik"},
      {text:"Saving throw spell'lerinde ability ve Save DC görünümü",category:"Özellik"},
      {text:"Compound dice formula ve çözümleme için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.18.0",date:"2026-07-16",title:"Guided Level-Up & Choice Debt",
    summary:"Level progression sırasında eksik kalan zorunlu class seçimleri tespit edilip karakter sayfasında çözülebilir hale getirildi.",
    changes:[
      {text:"Dokuz seçim ailesi için merkezi Choice Debt motoru",category:"Özellik"},
      {text:"Subclass, style, mastery, Metamagic, Invocation ve Maneuver çözümleyici",category:"Özellik"},
      {text:"Wild Shape, companion ve Mystic Arcanum borç çözümleyici",category:"Özellik"},
      {text:"Play Readiness içinde eksik zorunlu seçim engeli",category:"Düzeltme"},
      {text:"ASI milestone sırasında gerçek feat seçimi ve kayıt",category:"Özellik"},
      {text:"Choice Debt için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.17.0",date:"2026-07-16",title:"Paladin Smite & Aura System",
    summary:"Divine Smite slot harcaması, otomatik hasar zarı ve Paladin aura progression masa moduna eklendi.",
    changes:[
      {text:"Spell slot seçerek otomatik Divine Smite damage roll",category:"Özellik"},
      {text:"2014 ve 2024 için ayrı Smite dice sınırları",category:"Özellik"},
      {text:"Fiend/Undead hedefler için ilave radiant die seçeneği",category:"Özellik"},
      {text:"Aura of Protection ve Aura of Courage level/radius takibi",category:"Özellik"},
      {text:"Level 11 Radiant Strikes Character Sheet ve Play Mode bilgisi",category:"Özellik"},
      {text:"Paladin/Ranger slotlarının yeniden yüklemede silinmesi düzeltildi",category:"Düzeltme"},
    ],
  },
  {
    version:"2.16.0",date:"2026-07-16",title:"Warlock Pact Magic & Mystic Arcanum",
    summary:"Warlock'ın ayrı slot progression'ı, Short Rest yenilemesi ve üst seviye Arcanum seçimleri tamamlandı.",
    changes:[
      {text:"Level 1–20 Pact Magic slot seviyesi ve adet tablosu",category:"Düzeltme"},
      {text:"Short Rest sırasında Pact Magic slotlarının yenilenmesi",category:"Özellik"},
      {text:"Level 11, 13, 15 ve 17 Mystic Arcanum seçimleri",category:"Özellik"},
      {text:"Builder'da her açılan spell level için zorunlu Arcanum doğrulaması",category:"Düzeltme"},
      {text:"Character Sheet ve Play Mode tek kullanımlık Arcanum takibi",category:"Özellik"},
      {text:"Warlock level 8 spell seçenekleri ve üç otomatik Pact Magic testi",category:"Teknik"},
    ],
  },
  {
    version:"2.15.0",date:"2026-07-16",title:"Core Class Action Console",
    summary:"Temel class kaynakları Play Mode'da kullanılabilir eylemlere ve dinlenme yenilemesine bağlandı.",
    changes:[
      {text:"Rage, Bardic Inspiration, Channel Divinity ve Fighter kaynak eylemleri",category:"Özellik"},
      {text:"Focus/Ki, Lay on Hands, Favored Enemy ve Arcane Recovery kullanımı",category:"Özellik"},
      {text:"Second Wind için otomatik d10 + Fighter level healing",category:"Özellik"},
      {text:"Lay on Hands için 1, 5 ve 10 puanlık healing kontrolleri",category:"Özellik"},
      {text:"Short/Long Rest sırasında class kaynaklarının otomatik yenilenmesi",category:"Düzeltme"},
      {text:"Cleric ve Druid kaynaklarının erken level'da açılması düzeltildi",category:"Düzeltme"},
    ],
  },
  {
    version:"2.14.0",date:"2026-07-16",title:"Beast Master Companion System",
    summary:"Ranger companion seçimi, level ölçekli statlar ve masa modu HP takibi Beast Master akışına eklendi.",
    changes:[
      {text:"2014 için üç classic beast companion seçeneği",category:"Özellik"},
      {text:"2024 için Land, Sea ve Sky primal companion seçenekleri",category:"Özellik"},
      {text:"Level, proficiency ve Wisdom ile ölçeklenen statlar",category:"Özellik"},
      {text:"Builder zorunlu seçim ve ruleset doğrulaması",category:"Düzeltme"},
      {text:"Character Sheet stat özeti ve Play Mode HP yönetimi",category:"Özellik"},
      {text:"Companion kuralları için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version:"2.13.0",date:"2026-07-16",title:"Battle Master Maneuvers",
    summary:"Battle Master maneuver seçimleri ve Superiority Dice yönetimi karakter oluşturma ile masa moduna bağlandı.",
    changes:[
      {text:"On altı açık kural temelli maneuver ve özgün kısa açıklamalar",category:"Özellik"},
      {text:"Level 3, 7, 10 ve 15 maneuver progression",category:"Özellik"},
      {text:"Level ile büyüyen Superiority Dice sayısı ve die türü",category:"Özellik"},
      {text:"Builder seçim kotası ve kayıt doğrulaması",category:"Düzeltme"},
      {text:"Character Sheet ve Play Mode zar harcama entegrasyonu",category:"Özellik"},
      {text:"Maneuver progression için üç otomatik test",category:"Teknik"},
    ],
  },
  {
    version: "2.12.0", date: "2026-07-16", title: "Druid Wild Shape System",
    summary: "Wild Shape form uygunluğu, bilinen/favori formlar ve masada kullanım takibi Druid akışına eklendi.",
    changes: [
      { text: "On iki açık kural temelli beast formu ve özgün kısa açıklamalar", category: "Özellik" },
      { text: "CR, yüzme ve uçuş limitleri için level/ruleset kontrolü", category: "Düzeltme" },
      { text: "Circle of the Moon 2014 için genişleyen CR progression", category: "Özellik" },
      { text: "2024 bilinen form kotası ve artan Wild Shape kullanımları", category: "Özellik" },
      { text: "Builder, Character Sheet ve Play Mode dönüşüm entegrasyonu", category: "Özellik" },
      { text: "Wild Shape kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.11.0", date: "2026-07-16", title: "Warlock Eldritch Invocations",
    summary: "Warlock Invocation seçimleri level progression, prerequisite kontrolü ve karakter ekranlarına bağlandı.",
    changes: [
      { text: "Yirmi açık kural temelli Invocation ve özgün kısa açıklamalar", category: "Özellik" },
      { text: "2014 ve 2024 için ayrı Level 1–20 seçim progression", category: "Özellik" },
      { text: "Minimum level ve Eldritch Blast prerequisite kontrolü", category: "Düzeltme" },
      { text: "Builder, Character Sheet ve Play Mode entegrasyonu", category: "Özellik" },
      { text: "Eski kayıtlar ve taslaklar için güvenli veri migration", category: "Teknik" },
      { text: "Invocation kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.10.0", date: "2026-07-16", title: "Sorcerer Metamagic System",
    summary: "Sorcerer Metamagic seçimleri level kotası, Sorcery Point maliyeti ve Play Mode kullanımıyla eklendi.",
    changes: [
      { text: "Sekiz açık lisanslı Metamagic seçeneği ve özgün özetler", category: "Özellik" },
      { text: "2014 Level 3, 10, 17 seçim progression", category: "Özellik" },
      { text: "2024 Level 2 başlangıç progression", category: "Özellik" },
      { text: "Sorcery Point maliyet metadata ve Character Sheet özellikleri", category: "Özellik" },
      { text: "Play Mode'da puan kontrollü Metamagic kullanımı", category: "Özellik" },
      { text: "Eksik veya geçersiz seçimde Builder kayıt engeli", category: "Düzeltme" },
      { text: "Metamagic kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.9.0", date: "2026-07-16", title: "Level 1–20 Progression Audit",
    summary: "Tüm class progression tabloları level, ASI/feat, capstone, subclass ve spell slot bütünlüğü açısından otomatik denetleniyor.",
    changes: [
      { text: "12 class için 1–20 level satırı bütünlük kontrolü", category: "Teknik" },
      { text: "Fighter level 6/14 ve Rogue level 10 ilave ASI işaretleri", category: "Düzeltme" },
      { text: "2014 Level 19 ASI ve 2024 Epic Boon ayrımı", category: "Düzeltme" },
      { text: "Boş progression satırlarına kayıpsız ASI/feat enrichment", category: "İyileştirme" },
      { text: "Subclass seçimi, capstone ve spell slot audit kontrolleri", category: "Teknik" },
      { text: "Progression audit için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.8.0", date: "2026-07-16", title: "Fighting Style Combat Integration",
    summary: "Fighting Style seçimleri Character Sheet ve Play Mode savaş hesaplarına bağlandı.",
    changes: [
      { text: "Archery ile ranged weapon attack rollarına +2", category: "Özellik" },
      { text: "Defense ile kuşanılmış armor üzerinde +1 otomatik AC", category: "Özellik" },
      { text: "Dueling ile tek elli melee weapon damage bonusu", category: "Özellik" },
      { text: "Thrown Weapon Fighting damage bonusu", category: "Özellik" },
      { text: "Character Sheet ve Play Mode attack/damage özetlerine otomatik yansıma", category: "İyileştirme" },
      { text: "Combat entegrasyonu için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.7.0", date: "2026-07-16", title: "Cantrip Expansion & Class Coverage",
    summary: "Caster class cantrip havuzları açık lisanslı seçenekler ve yapılandırılmış mekanik metadata ile genişletildi.",
    changes: [
      { text: "Blade Ward, Dancing Lights, Friends, Message ve True Strike", category: "Özellik" },
      { text: "Warlock için Eldritch Blast; Bard için Vicious Mockery", category: "Özellik" },
      { text: "Damage, save, attack ve character-level scaling metadata", category: "Teknik" },
      { text: "2014 ve 2024 için edition ayrımlı cantrip kayıtları", category: "Teknik" },
      { text: "Caster class kapsamı için otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.6.0", date: "2026-07-16", title: "Weapon Mastery System",
    summary: "2024 class progression içindeki Weapon Mastery kotaları Builder ve kalıcı karakter verisine bağlandı.",
    changes: [
      { text: "Class ve level progression tablosundan mastery seçim kotası", category: "Özellik" },
      { text: "Weapon item verisinden Slow, Nick, Topple, Sap, Vex ve Graze eşleştirmeleri", category: "Özellik" },
      { text: "Builder Equipment adımında mastery silah seçimi", category: "Özellik" },
      { text: "Eksik veya geçersiz mastery seçiminde kayıt engeli", category: "Düzeltme" },
      { text: "Eski karakterler için mastered weapon migration", category: "Teknik" },
      { text: "Mastery kotası için otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.5.0", date: "2026-07-16", title: "Fighter Fighting Styles & Combat Choices",
    summary: "Fighting Style seçimleri edition, class, level ve subclass kurallarıyla kalıcı karakter verisine bağlandı.",
    changes: [
      { text: "2014 için altı temel Fighting Style", category: "Özellik" },
      { text: "2024 için Blind Fighting, Interception, Thrown Weapon ve Unarmed seçenekleri", category: "Özellik" },
      { text: "Fighter, Paladin ve Ranger level bazlı seçim kotası", category: "Özellik" },
      { text: "Champion level 10 Additional Fighting Style desteği", category: "Özellik" },
      { text: "Eski karakter kayıtları için fighting style migration", category: "Teknik" },
      { text: "Fighting style kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.4.0", date: "2026-07-16", title: "Granted Spell Database Completion",
    summary: "Domain ve oath paketlerinin ihtiyaç duyduğu eksik büyüler 2014 ve 2024 spell veritabanlarına eklendi.",
    changes: [
      { text: "Domain ve oath listeleri için 29 yeni spell kaydı", category: "Özellik" },
      { text: "Spell level, class, school, duration ve temel mekanik metadata", category: "Teknik" },
      { text: "Arcane Eye, Moonbeam, Scrying, Wall of Fire ve Zone of Truth dahil tamamlama", category: "Özellik" },
      { text: "Paladin oath spell listelerinin gerçek veriyle görünür hâle gelmesi", category: "Düzeltme" },
      { text: "Granted spell veri kapsamı için otomatik regresyon testi", category: "Teknik" },
    ],
  },
  {
    version: "2.3.0", date: "2026-07-16", title: "Paladin Oath Spells",
    summary: "Always Prepared sistemi 2014 ve 2024 Paladin yemin büyülerine genişletildi.",
    changes: [
      { text: "2014 ve 2024 Oath of Devotion spell progression", category: "Özellik" },
      { text: "2014 ve 2024 Oath of the Ancients spell progression", category: "Özellik" },
      { text: "Paladin spell slot seviyesine göre otomatik oath spell açılması", category: "Özellik" },
      { text: "Oath büyülerinin normal prepared kotasından bağımsız tutulması", category: "Düzeltme" },
      { text: "Paladin oath spell kapsamı için otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.2.0", date: "2026-07-16", title: "Cleric Domain Spells Expansion",
    summary: "Always Prepared altyapısı Life Domain dışındaki Cleric domainlerine genişletildi.",
    changes: [
      { text: "13 genişletilmiş 2014 Cleric domaini için seviye 1–5 bonus spell listeleri", category: "Özellik" },
      { text: "2024 Light, Trickery ve War Domain bonus spell listeleri", category: "Özellik" },
      { text: "Mevcut spell verisinde bulunan domain büyülerinin otomatik eşleştirilmesi", category: "Teknik" },
      { text: "Domain spell kapsamı için otomatik regresyon testi", category: "Teknik" },
    ],
  },
  {
    version: "2.1.0", date: "2026-07-15", title: "Always Prepared Spells",
    summary: "Subclass tarafından verilen büyüler normal prepared kotasını tüketmeden Builder, Editor ve Play Mode akışına bağlandı.",
    changes: [
      { text: "2014 ve 2024 Life Domain bonus spell listeleri", category: "Özellik" },
      { text: "Character level ve erişilebilir spell level bazlı otomatik açılma", category: "Özellik" },
      { text: "Always Prepared büyülerin known ve prepared listelerine otomatik eklenmesi", category: "Özellik" },
      { text: "Normal prepared kotasından subclass büyülerinin çıkarılması", category: "Düzeltme" },
      { text: "Spell Selector içinde ayrı Always Prepared durumu", category: "İyileştirme" },
      { text: "Subclass spell unlock davranışı için otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.0.3", date: "2026-07-15", title: "Ability Generation Rules",
    summary: "Character Builder artık tekil skor tavanının yanında Standard Array, Point Buy ve ASI toplam bütçesini de doğruluyor.",
    changes: [
      { text: "Standard Array, Point Buy ve Rolled/Manual oluşturma yöntemleri", category: "Özellik" },
      { text: "Class ve level bazlı ASI puan bütçesi", category: "Özellik" },
      { text: "Feat seçildiğinde ilgili ASI bütçesinin otomatik düşürülmesi", category: "Düzeltme" },
      { text: "Kurala aykırı toplam dağılımda Review kayıt engeli", category: "Düzeltme" },
      { text: "Ability generation bütçeleri için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "2.0.2", date: "2026-07-15", title: "Player Ability Cap Fix",
    summary: "Character Builder ve Editor içindeki oyuncu ability skorları normal 20 tavanıyla sınırlandı.",
    changes: [
      { text: "Builder ability alanlarında maksimum skor 20", category: "Düzeltme" },
      { text: "Character Editor ability alanlarında maksimum skor 20", category: "Düzeltme" },
      { text: "Origin bonusu sonrası nihai skor 20'yi aşarsa kayıt engeli", category: "Düzeltme" },
      { text: "Ability tavanı için otomatik regresyon testi", category: "Teknik" },
    ],
  },
  {
    version: "2.0.1", date: "2026-07-15", title: "Legacy Draft Recovery Fix",
    summary: "Eski sürümlerden kalan Character Builder taslakları yeni alanlarla güvenli biçimde tamamlanarak açılış çökmesi giderildi.",
    changes: [
      { text: "Eski autosave taslakları için geriye uyumlu alan normalizasyonu", category: "Düzeltme" },
      { text: "Eksik feat, skill, spell, inventory ve equipment listelerine güvenli varsayılanlar", category: "Düzeltme" },
      { text: "İç içe ability, death save ve condition verilerini kaybetmeden birleştirme", category: "Teknik" },
      { text: "Legacy draft migration için üç otomatik regresyon testi", category: "Teknik" },
    ],
  },
  {
    version: "2.0.0", date: "2026-07-15", title: "Playable Character Release",
    summary: "Karakter oluşturma, doğrulama, Character Sheet, Play Mode, level-up ve rest akışları oynanabilir tek bir v2 deneyiminde birleşti.",
    changes: [
      { text: "Kayıtlı karakterler için yüzde bazlı Playable Character Check", category: "Özellik" },
      { text: "Kimlik, HP, ability, equipment, spell ve ruleset bütünlük kontrolleri", category: "Özellik" },
      { text: "Dashboard üzerinde oynamaya hazır durum göstergesi", category: "İyileştirme" },
      { text: "Dashboard ve Character Sheet'ten seçili karakterle doğrudan Play Mode açılışı", category: "İyileştirme" },
      { text: "Play Mode içinde eksiklerden Character Editor'a hızlı dönüş", category: "İyileştirme" },
      { text: "Playable readiness motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.35.0", date: "2026-07-15", title: "Character Creation Polish",
    summary: "Character Builder, adım durumları, doğrudan hata yönlendirmesi, ilerleme görünümü ve mobil kullanım iyileştirmeleriyle v2.0 öncesi son hazırlığını tamamladı.",
    changes: [
      { text: "Her Builder adımı için hata, uyarı, tamam ve bekliyor durumu", category: "İyileştirme" },
      { text: "Review hatasından ilgili adıma tek tık dönüş", category: "Özellik" },
      { text: "İlk zorunlu hataya hızlı yönlendirme", category: "Özellik" },
      { text: "Ruleset, subclass, skill, expertise ve feat içeren genişletilmiş Review özeti", category: "İyileştirme" },
      { text: "Taslak kurtarma bildirimi, ilerleme çubuğu ve yatay mobil stepper", category: "İyileştirme" },
      { text: "Builder progress yönlendirmeleri için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.34.0", date: "2026-07-15", title: "Level-Up Automation V2",
    summary: "Level-up akışı class progression, spell slotları, kaynak scaling, class-specific ASI ve geri alma geçmişiyle yenilendi.",
    changes: [
      { text: "Yeni level class ve subclass feature ön izlemesi", category: "Özellik" },
      { text: "Class progression tablosundan full/half/pact spell slot güncellemesi", category: "Özellik" },
      { text: "Level ile artan class resource maksimumlarını güvenli birleştirme", category: "Özellik" },
      { text: "Fighter ve Rogue ilave ASI/feat kilometre taşları", category: "Düzeltme" },
      { text: "Kalıcı level-up geçmişi ve son işlemi geri alma", category: "Özellik" },
      { text: "Level-up history için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.33.0", date: "2026-07-15", title: "Character Sheet V2",
    summary: "Saving throws, skill/expertise rolları, passive skorlar ve birleşik feature/proficiency görünümü oynanabilir Character Sheet'e eklendi.",
    changes: [
      { text: "Altı saving throw için class proficiency hesaplama ve hızlı roll", category: "Özellik" },
      { text: "18 skill için ability, proficiency ve expertise bonusları", category: "Özellik" },
      { text: "Passive Perception, Investigation ve Insight hesapları", category: "Özellik" },
      { text: "Class, subclass ve feat feature'larını tek listede birleştirme", category: "Özellik" },
      { text: "Armor, weapon, tool, language ve speed özeti", category: "İyileştirme" },
      { text: "Character Sheet kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.32.0", date: "2026-07-15", title: "Spellcasting Rules Engine",
    summary: "Class progression tabanlı spell seçim limitleri, ritual casting ve full/half/pact slot ayrımı Builder'a bağlandı.",
    changes: [
      { text: "Class ve level bazlı cantrip, known ve prepared spell limitleri", category: "Özellik" },
      { text: "Spellcasting ability modifier kullanan prepared spell hesabı", category: "Özellik" },
      { text: "Full caster, half caster ve Pact Magic slot progression ayrımı", category: "Özellik" },
      { text: "Bilinen ritual büyüler için Ritual Ready durumu", category: "İyileştirme" },
      { text: "Limit dolduğunda Builder seçimlerini güvenli engelleme", category: "İyileştirme" },
      { text: "Spellcasting engine için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.31.0", date: "2026-07-15", title: "Spell Database V2",
    summary: "Cleric level 0–9 kapsamı başta olmak üzere 2014 ve 2024 spell havuzları gelişmiş mekanik metadata ile büyütüldü.",
    changes: [
      { text: "Her edition için 32 yeni yüksek seviye spell", category: "Özellik" },
      { text: "Cleric spell seviyeleri 4, 6, 7, 8 ve 9 için geniş paket", category: "Özellik" },
      { text: "Heal, Heroes' Feast, Death Ward, Resurrection ve Mass Heal dahil destek büyüleri", category: "Özellik" },
      { text: "Material cost, consumed material ve reaction trigger veri alanları", category: "Teknik" },
      { text: "Spellbook aramasında material ve reaction metadata desteği", category: "İyileştirme" },
      { text: "Spell Database V2 kapsamı için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.30.0", date: "2026-07-15", title: "Feat Expansion",
    summary: "2014 ve 2024 feat havuzları, prerequisite ve yapılandırılmış seçim metadata'sı ile genişletildi.",
    changes: [
      { text: "2014 için 23 ilave general feat", category: "Özellik" },
      { text: "2024 için 15 ilave general feat", category: "Özellik" },
      { text: "Ability, skill, tool, spell ve fighting style seçim metadata'sı", category: "Teknik" },
      { text: "Repeatable feat ve seçim adedi altyapısı", category: "Teknik" },
      { text: "Feat Catalog içinde ability ve choice metadata görünümü", category: "İyileştirme" },
      { text: "Feat paket kapsamı için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.29.0", date: "2026-07-15", title: "Subclass Expansion",
    summary: "Cleric domainleri başta olmak üzere 2014 ve 2024 subclass seçenekleri, özgün feature özetleri ve mekanik metadata ile genişletildi.",
    changes: [
      { text: "2014 Cleric için 13 yeni domain; Life Domain ile toplam 14 seçenek", category: "Özellik" },
      { text: "Light, Trickery ve War dahil genişletilmiş 2024 Cleric seçenekleri", category: "Özellik" },
      { text: "Her ana class için en az bir ilave 2014 ve 2024 subclass", category: "Özellik" },
      { text: "Level bazlı özgün feature özetleri ve resource/proficiency metadata", category: "İyileştirme" },
      { text: "Builder ve Subclass Catalog içinde genişletilmiş metadata görünümü", category: "İyileştirme" },
      { text: "Subclass paket kapsamı için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.28.0", date: "2026-07-15", title: "Class Features Engine",
    summary: "Temel class kaynakları level ve ability skorlarına göre otomatik oluşturulup Character Sheet ve Rest sistemine bağlandı.",
    changes: [
      { text: "12 ana class için level-aware resource üretimi", category: "Özellik" },
      { text: "Rage, Bardic Inspiration, Channel Divinity, Wild Shape, Second Wind ve Action Surge", category: "Özellik" },
      { text: "Focus/Ki, Lay on Hands, Sorcery Points, Mystic Arcanum ve Arcane Recovery", category: "Özellik" },
      { text: "Character Sheet üzerinde kullan/geri al kontrolleri ve action özetleri", category: "İyileştirme" },
      { text: "Eski karakterlere class resource migration ve rest recovery bağlantısı", category: "Teknik" },
      { text: "Class feature engine için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.27.0", date: "2026-07-15", title: "Character Builder Validation",
    summary: "Character Builder final kontrol motoru, adım bazlı hata listesi ve kuralsız kayıt engeli eklendi.",
    changes: [
      { text: "Identity, class, race/species, background ve subclass zorunlulukları", category: "Özellik" },
      { text: "Ability, 2024 origin bonusu ve class skill kotası doğrulaması", category: "Özellik" },
      { text: "Feat prerequisite, spell class/level ve prepared-known kontrolleri", category: "Özellik" },
      { text: "Inventory ile equipped item tutarlılık kontrolü", category: "Özellik" },
      { text: "Review ekranında hata/uyarı özeti ve hatalı kaydı engelleme", category: "İyileştirme" },
      { text: "Validation motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.26.0", date: "2026-07-15", title: "Skills + Proficiencies Builder",
    summary: "Class ve background tabanlı skill seçimleri, duplicate kontrolü, expertise, tool ve language kayıtları Character Builder'a eklendi.",
    changes: [
      { text: "18 temel skill için class seçim havuzu ve kota kontrolü", category: "Özellik" },
      { text: "Background skilllerini otomatik ekleme ve duplicate engelleme", category: "Özellik" },
      { text: "Bard ve Rogue için level bazlı Expertise seçimi", category: "Özellik" },
      { text: "Tool proficiency ve language kayıt alanları", category: "Özellik" },
      { text: "Eski karakterler için güvenli proficiency migration", category: "Teknik" },
      { text: "Proficiency kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.25.0", date: "2026-07-15", title: "Equipment + Items Expansion",
    summary: "2014 ve 2024 equipment verileri, genişletilmiş item şeması ve 2024 Weapon Mastery bağlantısı eklendi.",
    changes: [
      { text: "2024 ruleset için weapon, armor, shield ve adventuring gear veri paketi", category: "Özellik" },
      { text: "Tool, pack ve ammunition item kategorileri", category: "Özellik" },
      { text: "2024 silahları için Weapon Mastery çözümleme altyapısı", category: "Özellik" },
      { text: "Inventory aramasında property, damage type ve mastery desteği", category: "İyileştirme" },
      { text: "Equipment kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.24.0", date: "2026-07-15", title: "Spell Database Expansion",
    summary: "2014 ve 2024 büyü veri şeması, mekanik alanlar, gelişmiş filtreler ve level uyumlu Builder seçimi eklendi.",
    changes: [
      { text: "Damage, healing, save, attack, area ve scaling alanları", category: "Özellik" },
      { text: "2024 için ayrı başlangıç spell veri paketi", category: "Özellik" },
      { text: "School ve etki türü filtreleri", category: "İyileştirme" },
      { text: "Karakter levelına göre erişilemeyen spell seviyelerini gizleme", category: "Düzeltme" },
      { text: "Spell kuralları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.23.0", date: "2026-07-15", title: "Feats",
    summary: "2014 ve 2024 feat veri katmanı, origin feat aktarımı, prerequisite kontrolü ve Builder seçimi eklendi.",
    changes: [
      { text: "2014 ve 2024 için ayrı feat veri setleri", category: "Özellik" },
      { text: "Origin, General ve Epic Boon kategori ayrımı", category: "Özellik" },
      { text: "Level, ability ve spellcasting prerequisite kontrolü", category: "Özellik" },
      { text: "Class ve level bazlı feat kotası", category: "İyileştirme" },
      { text: "Yeni Feats katalog ekranı", category: "Özellik" },
      { text: "Feat helperları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.22.0", date: "2026-07-15", title: "Subclasses",
    summary: "2014 ve 2024 subclass veri katmanı, Builder seçimi, level kilidi ve feature progression görünümü eklendi.",
    changes: [
      { text: "2014 ve 2024 için class bağlantılı subclass veri setleri", category: "Özellik" },
      { text: "Builder içinde class ve level uyumlu subclass seçimi", category: "Özellik" },
      { text: "Level bazlı açılan subclass feature görünümü", category: "Özellik" },
      { text: "Yeni Subclasses katalog ekranı", category: "Özellik" },
      { text: "Subclass helperları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.21.0",
    date: "2026-07-15",
    title: "Races, species ve backgrounds",
    summary: "2014 race/subrace bonusları ile 2024 species, origin background, origin feat ve ability bonus seçimleri Character Builder'a bağlandı.",
    changes: [
      { text: "2014 için dokuz temel race ve subrace veri setleri", category: "Özellik" },
      { text: "2024 için on species veri seti", category: "Özellik" },
      { text: "2014 background feature ve proficiency paketleri", category: "Özellik" },
      { text: "2024 origin background, origin feat ve +2/+1 ability seçimi", category: "Özellik" },
      { text: "Yeni Species & Backgrounds katalog ekranı", category: "Özellik" },
      { text: "Origin ability bonus helperları için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.20.0",
    date: "2026-07-15",
    title: "Classes ve level tabloları",
    summary: "2014 ve 2024 için on iki ana class; level progression, proficiency, subclass seviyesi, spell slotları ve feature akışıyla ayrı veri katmanlarında hazır.",
    changes: [
      { text: "2014 ve 2024 için 12 ana class veri seti", category: "Özellik" },
      { text: "Level 1-20 proficiency bonus ve feature progression tabloları", category: "Özellik" },
      { text: "Full caster, half caster, pact magic ve martial progression ayrımı", category: "Teknik" },
      { text: "2024 martial classları için Weapon Mastery adet altyapısı", category: "Özellik" },
      { text: "Yeni Classes + Level Tables katalog ekranı", category: "Özellik" },
      { text: "Builder class ön izlemesine subclass ve progression bilgisi", category: "İyileştirme" },
      { text: "Class progression helperları için otomatik testler", category: "Teknik" },
    ],
  },
  {
    version: "1.19.0",
    date: "2026-07-15",
    title: "Ruleset Foundation",
    summary: "2014, 2024 ve Homebrew karakterleri ayrı ruleset kimliği, terminology ve veri yükleme katmanıyla yönetiliyor.",
    changes: [
      { text: "Yeni Ruleset Center ve varsayılan edition ayarı", category: "Özellik" },
      { text: "2014, 2024 ve Homebrew için merkezi ruleset registry", category: "Teknik" },
      { text: "Builder ve Character Editor içinde edition-aware veri yükleme", category: "Özellik" },
      { text: "Ruleset değişiminde uyumsuz class, spell ve equipment seçimlerini güvenli temizleme", category: "İyileştirme" },
      { text: "Eski karakterleri otomatik D&D 2014 ruleset kimliğine taşıyan migration", category: "Teknik" },
      { text: "2024 veri klasörü ve sonraki class/species/background paketleri için hazır altyapı", category: "Teknik" },
    ],
  },
  {
    version: "1.18.0",
    date: "2026-07-15",
    title: "Downtime ve campaign calendar",
    summary: "Oyun içi zaman, yaklaşan olaylar, seyahatler ve karakter downtime faaliyetleri campaign bazında tek takvimde yönetiliyor.",
    changes: [
      { text: "Campaign bağlantılı yeni Downtime + Campaign Calendar sayfası", category: "Özellik" },
      { text: "Oyun içi günü toplu ilerletme ve yaklaşan olayları sıralama", category: "Özellik" },
      { text: "Karakter bağlantılı downtime faaliyetleri ve otomatik ilerleme yüzdesi", category: "Özellik" },
      { text: "Oturum, seyahat, son tarih, festival ve çatışma olay türleri", category: "İyileştirme" },
      { text: "Eski ve bozuk kayıtlar için güvenli calendar sanitizasyonu", category: "Teknik" },
      { text: "Campaign calendar motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.17.0",
    date: "2026-07-14",
    title: "Rest ve resource automation",
    summary: "Short Rest ve Long Rest işlemleri; HP, spell slot, Hit Dice, exhaustion ve özel sınıf kaynaklarıyla toplu ve geri alınabilir biçimde yönetiliyor.",
    changes: [
      { text: "Seçili karakterlere toplu Short Rest ve Long Rest uygulama", category: "Özellik" },
      { text: "HP, spell slot, Hit Dice, death save, temp HP ve exhaustion otomasyonu", category: "Özellik" },
      { text: "Short Rest, Long Rest veya manuel yenilenen özel sınıf kaynakları", category: "Özellik" },
      { text: "Dinlenme geçmişi ve son işlemi geri alma güvenliği", category: "İyileştirme" },
      { text: "Combat Tracker savaşçılarını senkronize etme ve combat log kaydı", category: "İyileştirme" },
      { text: "Rest motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.16.0",
    date: "2026-07-14",
    title: "Battlefield zones ve area effects",
    summary: "Aura, hazard, spell area ve difficult terrain bölgeleri savaşçı bağlantıları ve round sayaçlarıyla Combat Tracker içinde yönetiliyor.",
    changes: [
      { text: "Savaş alanına aura, hazard, spell area, cover ve difficult terrain ekleme", category: "Özellik" },
      { text: "Alan şekli, boyutu, kaynak, hasar, save DC ve koşul bilgisi", category: "Özellik" },
      { text: "Alanlardan etkilenen savaşçıları işaretleme", category: "Özellik" },
      { text: "Yeni round başladığında alan sürelerini otomatik azaltma ve bitenleri kaldırma", category: "İyileştirme" },
      { text: "Eski savaş kayıtları için geriye uyumlu zone sanitizasyonu", category: "Teknik" },
      { text: "Battlefield zone motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.15.0",
    date: "2026-07-14",
    title: "Encounter bridge ve savaş şablonları",
    summary: "Campaign encounter kayıtları canlı savaşa aktarılabiliyor; savaş dizilimleri tekrar kullanılabilir şablonlara dönüştürülebiliyor.",
    changes: [
      { text: "Campaign encounter katılımcılarını Combat Tracker'a tek tıkla aktarma", category: "Özellik" },
      { text: "Mevcut savaş dizilimini tekrar kullanılabilir şablon olarak kaydetme", category: "Özellik" },
      { text: "Şablondan tam HP ile yeni savaş oluşturma", category: "İyileştirme" },
      { text: "Şablon seçme ve silme kontrolleri", category: "İyileştirme" },
      { text: "Campaign encounter ve template dönüşümleri için iki yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.14.0",
    date: "2026-07-14",
    title: "Combat log ve encounter özeti",
    summary: "Savaş içindeki sıra, hasar, iyileştirme, etki ve manuel notlar otomatik bir olay günlüğünde toplanıyor.",
    changes: [
      { text: "Hasar, iyileştirme, sıra ve etki işlemlerini otomatik kaydetme", category: "Özellik" },
      { text: "Round ve aktif savaşçı geçişlerini savaş günlüğünde gösterme", category: "Özellik" },
      { text: "Toplam hasar, iyileştirme, yenilen savaşçı ve olay özeti", category: "İyileştirme" },
      { text: "Manuel combat notu ekleme ve günlüğü temizleme", category: "İyileştirme" },
      { text: "Eski combat kayıtları için geriye uyumlu log sanitizasyonu", category: "Teknik" },
      { text: "Combat log ve özet motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.13.0",
    date: "2026-07-14",
    title: "Combat effects ve süre otomasyonu",
    summary: "Savaş koşulları artık kaynak ve round süresiyle takip ediliyor; yeni round başladığında sayaçlar otomatik azalıyor.",
    changes: [
      { text: "Savaşçılara kaynak bilgili süreli etki ekleme", category: "Özellik" },
      { text: "Round geçişinde etki sürelerini otomatik azaltma", category: "Özellik" },
      { text: "Süresi biten etkileri otomatik kaldırma", category: "İyileştirme" },
      { text: "Kalıcı koşullar ile süreli etkileri birlikte gösterme", category: "İyileştirme" },
      { text: "Eski combat kayıtları için geriye uyumlu veri sanitizasyonu", category: "Teknik" },
      { text: "Etki motoru için iki yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.12.0",
    date: "2026-07-14",
    title: "Initiative ve combat tracker",
    summary: "Karakter, NPC ve canavarlar; sıra, round, HP, geçici HP ve koşullarıyla canlı bir savaş ekranında toplandı.",
    changes: [
      { text: "Yeni Initiative + Combat Tracker sayfası", category: "Özellik" },
      { text: "Karakter, NPC, canavar ve özel savaşçı ekleme", category: "Özellik" },
      { text: "Initiative sıralaması, aktif sıra ve otomatik round ilerletme", category: "Özellik" },
      { text: "Hasar, iyileştirme, geçici HP ve yenilgi durumu takibi", category: "İyileştirme" },
      { text: "On farklı koşulu savaşçı bazında yönetme", category: "İyileştirme" },
      { text: "Combat veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.11.0",
    date: "2026-07-14",
    title: "Loot ve treasure tracker",
    summary: "Campaign ganimetleri, görev ödülleri, sahiplik ve paylaştırma durumlarıyla ayrı bir hazine takibinde toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni Loot + Treasure Tracker sayfası", category: "Özellik" },
      { text: "Para, eşya, büyülü eşya, mücevher, belge ve diğer ganimet türleri", category: "Özellik" },
      { text: "Görev bağlantısı, karakter sahipliği ve parti havuzu takibi", category: "Özellik" },
      { text: "Adet, birim değer ve otomatik toplam gp hesaplama", category: "İyileştirme" },
      { text: "Paylaştırma durumu ile oyuncu ve DM notlarının ayrılması", category: "İyileştirme" },
      { text: "Loot veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.10.0",
    date: "2026-07-14",
    title: "Quest journal ve plot threads",
    summary:
      "Campaign görevleri; durum, öncelik, hedefler, ödüller, bağlantılar ve DM sırlarıyla ayrı bir görev günlüğünde toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni Quest Journal + Plot Threads sayfası", category: "Özellik" },
      { text: "Görev durumu, önceliği, etiketleri ve tamamlanabilir hedefleri", category: "Özellik" },
      { text: "Görevleri NPC, World Atlas mekânı ve faction ile bağlama", category: "Özellik" },
      { text: "Oyuncu özeti, DM gizli notu ve ödül alanlarının ayrılması", category: "İyileştirme" },
      { text: "Görev ilerleme yüzdesi ile campaign ve durum filtreleri", category: "İyileştirme" },
      { text: "Quest journal veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.9.0",
    date: "2026-07-14",
    title: "Factions ve organizations",
    summary:
      "Campaign oluşumları; türleri, üyeleri, merkezleri, açık ve gizli hedefleri ile diplomatik ilişkileriyle ayrı bir yönetim ekranında toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni Factions + Organizations sayfası", category: "Özellik" },
      { text: "Krallık, lonca, tarikat, korsan tayfası, şirket ve gizli örgüt türleri", category: "Özellik" },
      { text: "Oluşumlara NPC üyesi ve World Atlas merkezi bağlama", category: "Özellik" },
      { text: "Müttefik, tarafsız, gergin ve düşman ilişki takibi", category: "Özellik" },
      { text: "Bilinen hedef ile DM gizli hedefinin ayrılması", category: "İyileştirme" },
      { text: "Faction veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.8.0",
    date: "2026-07-14",
    title: "Locations ve world atlas",
    summary:
      "Campaign mekânları; hiyerarşi, türler, açıklamalar, gizli notlar ve bağlı NPC'lerle ayrı bir dünya atlasında toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni Locations + World Atlas sayfası", category: "Özellik" },
      { text: "Bölge, şehir, kasaba, bina, zindan ve doğa türleri", category: "Özellik" },
      { text: "Üst mekân bağlantılarıyla hiyerarşik dünya yapısı", category: "Özellik" },
      { text: "Mekânlara NPC bağlama, etiketleme ve campaign filtreleme", category: "İyileştirme" },
      { text: "Oyuncu açıklaması ile DM gizli notlarının ayrılması", category: "İyileştirme" },
      { text: "World atlas veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.7.0",
    date: "2026-07-14",
    title: "NPC manager ve ilişki takibi",
    summary:
      "Campaign NPC'leri; roller, konumlar, tutumlar, gizli notlar ve birbirleriyle ilişkileriyle ayrı bir yönetim merkezinde toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni NPC Manager sayfası", category: "Özellik" },
      { text: "NPC rolü, konumu, durumu, tutumu ve etiket alanları", category: "Özellik" },
      { text: "Oyuncu bilgisi ile DM gizli notlarının ayrı tutulması", category: "Özellik" },
      { text: "NPC'ler arasında adlandırılabilir ilişki bağlantıları", category: "Özellik" },
      { text: "Campaign filtresi ve kapsamlı NPC araması", category: "İyileştirme" },
      { text: "NPC veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.6.0",
    date: "2026-07-14",
    title: "Session planner ve hızlı notlar",
    summary:
      "DM hazırlığı; oturum hedefi, sahne akışı, görev listesi, hızlı notlar ve session recap alanlarıyla tek çalışma ekranında toplandı.",
    changes: [
      { text: "Campaign bağlantılı yeni Session Planner sayfası", category: "Özellik" },
      { text: "Tamamlanabilir sahne akışı ve hazırlık görevleri", category: "Özellik" },
      { text: "Oturum içi hızlı not ve session recap alanları", category: "Özellik" },
      { text: "Oturum ilerleme yüzdesi ve son güncellenene göre sıralama", category: "İyileştirme" },
      { text: "Session planlarının güvenli localStorage saklaması", category: "Teknik" },
      { text: "Session planner veri motoru için üç otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.5.0",
    date: "2026-07-14",
    title: "Etiketler ve akıllı koleksiyonlar",
    summary:
      "Global arama kayıtları özel etiketlerle gruplanabiliyor; koleksiyonlar otomatik oluşuyor ve tek ekrandan yönetilebiliyor.",
    changes: [
      { text: "Global Arama sonuçlarına özel etiket ekleme ve kaldırma", category: "Özellik" },
      { text: "Etiketlerden otomatik oluşan Koleksiyonlar sayfası", category: "Özellik" },
      { text: "Koleksiyon yeniden adlandırma ve topluca silme", category: "İyileştirme" },
      { text: "Favori kayıtların koleksiyonlarda görünür rozeti", category: "İyileştirme" },
      { text: "Etiket verilerinin güvenli localStorage saklaması", category: "Teknik" },
      { text: "Etiket motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.4.0",
    date: "2026-07-14",
    title: "Favoriler ve son açılanlar",
    summary:
      "Global arama kayıtları favorilenebiliyor; son açılan içerikler ve favoriler Dashboard üzerinden hızlıca erişilebilir durumda.",
    changes: [
      { text: "Karakter, campaign, büyü, eşya ve canavar sonuçlarını favorileme", category: "Özellik" },
      { text: "Dashboard üzerinde favoriler ve son açılanlar alanı", category: "Özellik" },
      { text: "Global Arama sonuçlarında favori rozeti ve yıldız düğmesi", category: "İyileştirme" },
      { text: "Son açılan kayıtların tekrar açıldığında listenin başına taşınması", category: "İyileştirme" },
      { text: "Favori ve geçmiş verilerinin güvenli localStorage saklaması", category: "Teknik" },
      { text: "Favori motoru için üç yeni otomatik test", category: "Teknik" },
    ],
  },
  {
    version: "1.3.0",
    date: "2026-07-14",
    title: "Global arama merkezi",
    summary:
      "Karakter, campaign, büyü, eşya, canavar, sayfa ve yardım içerikleri artık tek ayrıntılı arama ekranından bulunabiliyor.",
    changes: [
      { text: "Yeni Global Arama sayfası", category: "Özellik" },
      { text: "Yedi içerik türünde kategori filtreleme ve sonuç sayıları", category: "Özellik" },
      { text: "Campaign notları, NPC'ler, questler ve timeline içinde derin arama", category: "İyileştirme" },
      { text: "Homebrew içeriklerin sonuçlarda ayrı rozetle gösterilmesi", category: "İyileştirme" },
      { text: "Arama sorgularının URL üzerinden korunması ve paylaşılabilmesi", category: "İyileştirme" },
      { text: "Arama sıralama helper'ları için otomatik testler", category: "Teknik" },
    ],
  },
  {
    version: "1.2.0",
    date: "2026-07-14",
    title: "Yardım merkezi ve yönlendirmeli başlangıç",
    summary:
      "Yeni yardım merkezi; oyuncu, DM, veri güvenliği ve PWA akışlarını aranabilir kısa rehberlerde topluyor.",
    changes: [
      { text: "Aranabilir ve kategori filtreli Yardım Merkezi", category: "Özellik" },
      { text: "Yerel olarak saklanan hızlı başlangıç kontrol listesi", category: "Özellik" },
      { text: "Karakter, Play Mode, campaign, encounter, homebrew ve backup rehberleri", category: "İyileştirme" },
      { text: "PWA kurulumu, çevrimdışı kullanım ve klavye kısayolu açıklamaları", category: "İyileştirme" },
      { text: "Sorun anında yedek ve kurtarma ekranına hızlı erişim", category: "Düzeltme" },
      { text: "Yardım sayfasının ayrı lazy-loaded route olarak eklenmesi", category: "Teknik" },
    ],
  },
  {
    version: "1.1.0",
    date: "2026-07-14",
    title: "Sürüm geçmişi ve güncelleme detayları",
    summary:
      "Sürüm notları artık aranabilir, filtrelenebilir ve uygulama içinde kalıcı bir geçmiş ekranından incelenebilir.",
    changes: [
      { text: "Yeni Sürüm Geçmişi sayfası", category: "Özellik" },
      { text: "Sürüm ve değişiklik metninde arama", category: "Özellik" },
      { text: "Özellik, iyileştirme, düzeltme ve teknik filtreleri", category: "İyileştirme" },
      { text: "Mevcut sürüm ve build tarihinin görünür özeti", category: "İyileştirme" },
      { text: "Windows dosya adı casing çakışmasının kalıcı olarak ayrıştırılması", category: "Düzeltme" },
      { text: "Public npm registry zorlaması ve temiz lockfile", category: "Teknik" },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-07-14",
    title: "İlk kararlı sürüm",
    summary:
      "E4 D&D artık karakter, campaign, encounter, homebrew, Play Mode, yedekleme ve PWA akışlarını tek pakette sunan kararlı bir masa yardımcısı.",
    changes: [
      { text: "Karakter oluşturma, düzenleme, karşılaştırma ve level-up yardımcısı", category: "Özellik" },
      { text: "Spellbook, inventory, monster library ve homebrew araçları", category: "Özellik" },
      { text: "Campaign dashboard, encounter tracker ve isteğe bağlı DM modülleri", category: "Özellik" },
      { text: "Play Mode, autosave, güvenli veri kurtarma ve seçmeli backup import", category: "İyileştirme" },
      { text: "PWA kurulumu, çevrimdışı kullanım ve kontrollü güncelleme bildirimi", category: "İyileştirme" },
      { text: "Route splitting, performans iyileştirmeleri, testler ve otomatik deploy", category: "Teknik" },
    ],
  },
];

export const RELEASE_CATEGORIES: readonly ReleaseCategory[] = [
  "Özellik",
  "İyileştirme",
  "Düzeltme",
  "Teknik",
];

export function getCurrentRelease() {
  return (
    RELEASE_NOTES.find((release) => release.version === __APP_VERSION__) ??
    RELEASE_NOTES[0]
  );
}
